configured_endpoints: 11
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/supermemory--inc%2Fsupermemory-new-0293efeddbd48f43b5336c0d87e7862d61de0ad5b5da8c3c17f93da5d8a8edca.yml
openapi_spec_hash: e94bf330ad1fa4adeea8533abed19be8
config_hash: 942fcc7bc84d7351016cee303ff7ddd6
