configured_endpoints: 15
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/supermemory--inc%2Fsupermemory-new-ed398f5eafd7dffae0725ec2f42f2a2b0db528292cee661e9f1cdb1063e6eb7b.yml
openapi_spec_hash: c09b2e00932fc1762acabbe9e5c41390
config_hash: 2d016ffc303fca68275d9c094a28f418
