configured_endpoints: 26
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/supermemory--inc%2Fsupermemory-new-3856961a8959b60dbf0b6912d69c23390fbbca1c5e31028dd0decc85234dd285.yml
openapi_spec_hash: 988a7d6d7cef81ceb4acda3ef9f8c21e
config_hash: b6ef9b4dc6a01f799e46a04dd24becc7
