configured_endpoints: 18
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/supermemory--inc%2Fsupermemory-new-6453f22c5b02f00d5656b9fbef9a4c70999ed890c95ddbfd363c7ddba2cef59f.yml
openapi_spec_hash: bb200bfe2a4fa307beaa119b54efeeb2
config_hash: 2737bce9823a13e0263c0fa2701821fa
