configured_endpoints: 18
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/supermemory--inc%2Fsupermemory-new-16a67abae0e57e099ae0786c0eadfabd081893721b660d50afe2ab0265d52c1a.yml
openapi_spec_hash: f371b0de53a247eeab88d71cc1edb6ca
config_hash: a478b24249ee4f53abfb5787ca4daf8b
