configured_endpoints: 12
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/supermemory--inc%2Fsupermemory-new-101f86a36ccd7f0652cfb6cac5d8f49e45ce3bee2b96692e8decd1eda3419604.yml
openapi_spec_hash: b6c08c22ab103285c7ada4eff95cfd0a
config_hash: 852562a0f8690b3d0a56def09aeec2a1
