import { Supermemory } from "./dist/esm/index.js";
const sm = new Supermemory({ apiKey: process.env.SM_KEY });
const ns = "mtd_fern_ts_e2e";
const sleep = (ms) => new Promise(r => setTimeout(r, ms));
const t = async (n, f) => { try { const r = await f(); console.log("✔", n, typeof r === "string" ? r : JSON.stringify(r).slice(0, 120)); return r; } catch (e) { console.log("✘", n, e?.statusCode ?? e?.name ?? "", String(e?.message ?? e).slice(0, 160)); } };
await t("surface", async () => `add=${typeof sm.add} search=${typeof sm.search} documents.get=${typeof sm.documents?.get} connectors.create=${typeof sm.connectors?.create} connectors.listProviders=${typeof sm.connectors?.listProviders} connectors.listAll=${typeof sm.connectors?.listAll} replaceWithFile=${typeof sm.documents?.replaceWithFile}`);
await t("add (dreaming instant)", () => sm.add({ namespace: ns, dreaming: "instant", body: { id: "sarah-1", content: "Sarah Chen was promoted to VP of Product. She is based in Berlin and prefers async updates." } }));
let st; for (let i = 0; i < 12; i++) { await sleep(5000); const d = await sm.documents.get({ namespace: ns, id: "sarah-1" }); st = d.system?.status; if (st === "done" || st === "failed") break; } console.log("  processed:", st);
await t("search default", async () => { const r = await sm.search({ namespace: ns, body: { query: "who leads product?" } }); return `${r.results.length} results, top=${(r.results[0]?.chunk ?? r.results[0]?.memory ?? "").slice(0,40)}`; });
await t("search + filter", () => sm.search({ namespace: ns, body: { query: "Berlin", filter: { field: "source", operator: "eq", value: "nope" } } }));
await t("list documents", async () => { const r = await sm.list({ namespace: ns, type: "documents" }); return `${r.pagination.totalItems} docs`; });
await t("documents.update metadata", () => sm.documents.update({ namespace: ns, id: "sarah-1", body: { metadata: { source: "e2e" } } }));
const file = new File([new TextEncoder().encode("hello file")], "a.txt", { type: "text/plain" });
await t("documents.uploadFile", () => sm.documents.uploadFile({ namespace: ns, body: { file, metadata: JSON.stringify({ source: "upload" }) } }));
await t("profile (no body)", () => sm.profile({ namespace: ns }));
await t("profiles.setBuckets", () => sm.profiles.setBuckets({ namespace: ns, body: { buckets: { location: "Where the user lives" } } }));
await t("profiles.deleteBuckets", () => sm.profiles.deleteBuckets({ namespace: ns, body: { buckets: ["location"] } }));
await t("memories.forgetMatching dryRun", () => sm.memories.forgetMatching({ namespace: ns, body: { query: "async updates", dryRun: true } }));
await t("namespaces.get", () => sm.namespaces.get({ namespace: ns }));
await t("namespaces.list", async () => `${(await sm.namespaces.list()).length} namespaces`);
await t("organization.get", () => sm.organization.get());
await t("connectors.list", () => sm.connectors.list({ namespace: ns }));
await t("connectors (org-wide)", async () => { const r = await (sm.connectors.listAll ?? sm.connectors.listProviders).call(sm.connectors, { limit: 2 }); return `${r.connectors.length} returned`; });
await t("documents.delete", () => sm.documents.delete({ namespace: ns, body: { ids: ["sarah-1"] } }));
await t("namespaces.delete (no body)", () => sm.namespaces.delete({ namespace: ns }));
