/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: fe3a294bfb46
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import {
  ErrorResponse,
  ErrorResponse$inboundSchema,
} from "./error-response.js";
import { SDKValidationError } from "./sdk-validation-error.js";
import {
  ValidationErrorResponse,
  ValidationErrorResponse$inboundSchema,
} from "./validation-error-response.js";

/**
 * Invalid request
 */
export type DeleteNsByNamespaceConnectorsByIdBadRequest =
  | ErrorResponse
  | ValidationErrorResponse;

/** @internal */
export const DeleteNsByNamespaceConnectorsByIdBadRequest$inboundSchema:
  z.ZodMiniType<DeleteNsByNamespaceConnectorsByIdBadRequest, unknown> =
    smartUnion([
      ErrorResponse$inboundSchema,
      ValidationErrorResponse$inboundSchema,
    ]);

export function deleteNsByNamespaceConnectorsByIdBadRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  DeleteNsByNamespaceConnectorsByIdBadRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DeleteNsByNamespaceConnectorsByIdBadRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'DeleteNsByNamespaceConnectorsByIdBadRequest' from JSON`,
  );
}
