/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9163eec14ca4
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import {
  ErrorResponse,
  ErrorResponse$inboundSchema,
} from "./error-response.js";
import { SDKValidationError } from "./sdk-validation-error.js";
import {
  ValidationErrorResponse,
  ValidationErrorResponse$inboundSchema,
} from "./validation-error-response.js";

/**
 * Invalid request
 */
export type DeleteNsByNamespaceMemoriesBadRequest =
  | ErrorResponse
  | ValidationErrorResponse;

/** @internal */
export const DeleteNsByNamespaceMemoriesBadRequest$inboundSchema: z.ZodMiniType<
  DeleteNsByNamespaceMemoriesBadRequest,
  unknown
> = smartUnion([
  ErrorResponse$inboundSchema,
  ValidationErrorResponse$inboundSchema,
]);

export function deleteNsByNamespaceMemoriesBadRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteNsByNamespaceMemoriesBadRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      DeleteNsByNamespaceMemoriesBadRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteNsByNamespaceMemoriesBadRequest' from JSON`,
  );
}
