/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b3c249d3afb5
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import {
  ErrorResponse,
  ErrorResponse$inboundSchema,
} from "./error-response.js";
import { SDKValidationError } from "./sdk-validation-error.js";
import {
  ValidationErrorResponse,
  ValidationErrorResponse$inboundSchema,
} from "./validation-error-response.js";

/**
 * Invalid request
 */
export type DeleteNsByNamespaceMemoriesSemanticBadRequest =
  | ErrorResponse
  | ValidationErrorResponse;

/** @internal */
export const DeleteNsByNamespaceMemoriesSemanticBadRequest$inboundSchema:
  z.ZodMiniType<DeleteNsByNamespaceMemoriesSemanticBadRequest, unknown> =
    smartUnion([
      ErrorResponse$inboundSchema,
      ValidationErrorResponse$inboundSchema,
    ]);

export function deleteNsByNamespaceMemoriesSemanticBadRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  DeleteNsByNamespaceMemoriesSemanticBadRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DeleteNsByNamespaceMemoriesSemanticBadRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'DeleteNsByNamespaceMemoriesSemanticBadRequest' from JSON`,
  );
}
