/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 458061dab702
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import {
  ErrorResponse,
  ErrorResponse$inboundSchema,
} from "./error-response.js";
import { SDKValidationError } from "./sdk-validation-error.js";
import {
  ValidationErrorResponse,
  ValidationErrorResponse$inboundSchema,
} from "./validation-error-response.js";

/**
 * Invalid delete request
 */
export type DeleteNsByNamespaceDocumentBadRequest =
  | ErrorResponse
  | ValidationErrorResponse;

/** @internal */
export const DeleteNsByNamespaceDocumentBadRequest$inboundSchema: z.ZodMiniType<
  DeleteNsByNamespaceDocumentBadRequest,
  unknown
> = smartUnion([
  ErrorResponse$inboundSchema,
  ValidationErrorResponse$inboundSchema,
]);

export function deleteNsByNamespaceDocumentBadRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteNsByNamespaceDocumentBadRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      DeleteNsByNamespaceDocumentBadRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteNsByNamespaceDocumentBadRequest' from JSON`,
  );
}
