/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 81a7e88393f8
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import {
  ErrorResponse,
  ErrorResponse$inboundSchema,
} from "./error-response.js";
import { SDKValidationError } from "./sdk-validation-error.js";
import {
  ValidationErrorResponse,
  ValidationErrorResponse$inboundSchema,
} from "./validation-error-response.js";

/**
 * Invalid request
 */
export type GetNsByNamespaceProfileBucketsBadRequest =
  | ErrorResponse
  | ValidationErrorResponse;

/** @internal */
export const GetNsByNamespaceProfileBucketsBadRequest$inboundSchema:
  z.ZodMiniType<GetNsByNamespaceProfileBucketsBadRequest, unknown> = smartUnion(
    [ErrorResponse$inboundSchema, ValidationErrorResponse$inboundSchema],
  );

export function getNsByNamespaceProfileBucketsBadRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  GetNsByNamespaceProfileBucketsBadRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetNsByNamespaceProfileBucketsBadRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetNsByNamespaceProfileBucketsBadRequest' from JSON`,
  );
}
