/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 136eb56e3881
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import {
  ErrorResponse,
  ErrorResponse$inboundSchema,
} from "./error-response.js";
import { SDKValidationError } from "./sdk-validation-error.js";
import {
  ValidationErrorResponse,
  ValidationErrorResponse$inboundSchema,
} from "./validation-error-response.js";

/**
 * Invalid request
 */
export type GetNsByNamespaceConnectorsBadRequest =
  | ErrorResponse
  | ValidationErrorResponse;

/** @internal */
export const GetNsByNamespaceConnectorsBadRequest$inboundSchema: z.ZodMiniType<
  GetNsByNamespaceConnectorsBadRequest,
  unknown
> = smartUnion([
  ErrorResponse$inboundSchema,
  ValidationErrorResponse$inboundSchema,
]);

export function getNsByNamespaceConnectorsBadRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetNsByNamespaceConnectorsBadRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetNsByNamespaceConnectorsBadRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetNsByNamespaceConnectorsBadRequest' from JSON`,
  );
}
