/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e3d5c1c88e71
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import {
  ErrorResponse,
  ErrorResponse$inboundSchema,
} from "./error-response.js";
import { SDKValidationError } from "./sdk-validation-error.js";
import {
  ValidationErrorResponse,
  ValidationErrorResponse$inboundSchema,
} from "./validation-error-response.js";

/**
 * Invalid request parameters
 */
export type PatchNsByNamespaceDocumentByIdBadRequest =
  | ErrorResponse
  | ValidationErrorResponse;

/** @internal */
export const PatchNsByNamespaceDocumentByIdBadRequest$inboundSchema:
  z.ZodMiniType<PatchNsByNamespaceDocumentByIdBadRequest, unknown> = smartUnion(
    [ErrorResponse$inboundSchema, ValidationErrorResponse$inboundSchema],
  );

export function patchNsByNamespaceDocumentByIdBadRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  PatchNsByNamespaceDocumentByIdBadRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PatchNsByNamespaceDocumentByIdBadRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PatchNsByNamespaceDocumentByIdBadRequest' from JSON`,
  );
}
