/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 52aab5dd0086
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import {
  ErrorResponse,
  ErrorResponse$inboundSchema,
} from "./error-response.js";
import { SDKValidationError } from "./sdk-validation-error.js";
import {
  ValidationErrorResponse,
  ValidationErrorResponse$inboundSchema,
} from "./validation-error-response.js";

/**
 * Invalid organization settings
 */
export type PatchOrganizationBadRequest =
  | ErrorResponse
  | ValidationErrorResponse;

/** @internal */
export const PatchOrganizationBadRequest$inboundSchema: z.ZodMiniType<
  PatchOrganizationBadRequest,
  unknown
> = smartUnion([
  ErrorResponse$inboundSchema,
  ValidationErrorResponse$inboundSchema,
]);

export function patchOrganizationBadRequestFromJSON(
  jsonString: string,
): SafeParseResult<PatchOrganizationBadRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchOrganizationBadRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchOrganizationBadRequest' from JSON`,
  );
}
