/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a80f85362116
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import {
  ErrorResponse,
  ErrorResponse$inboundSchema,
} from "./error-response.js";
import { SDKValidationError } from "./sdk-validation-error.js";
import {
  ValidationErrorResponse,
  ValidationErrorResponse$inboundSchema,
} from "./validation-error-response.js";

/**
 * Invalid file request
 */
export type PatchNsByNamespaceDocumentFileByIdBadRequest =
  | ErrorResponse
  | ValidationErrorResponse;

/** @internal */
export const PatchNsByNamespaceDocumentFileByIdBadRequest$inboundSchema:
  z.ZodMiniType<PatchNsByNamespaceDocumentFileByIdBadRequest, unknown> =
    smartUnion([
      ErrorResponse$inboundSchema,
      ValidationErrorResponse$inboundSchema,
    ]);

export function patchNsByNamespaceDocumentFileByIdBadRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  PatchNsByNamespaceDocumentFileByIdBadRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PatchNsByNamespaceDocumentFileByIdBadRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PatchNsByNamespaceDocumentFileByIdBadRequest' from JSON`,
  );
}
