/*
 * Generated by scripts/surface/generate.ts from fern/openapi.json. DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { ErrorResponse, ErrorResponse$inboundSchema } from "./error-response.js";
import { SDKValidationError } from "./sdk-validation-error.js";
import { ValidationErrorResponse, ValidationErrorResponse$inboundSchema } from "./validation-error-response.js";

export type PostNsByNamespaceDocumentFileBadRequest =
  | ErrorResponse
  | ValidationErrorResponse
;

/** @internal */
export const PostNsByNamespaceDocumentFileBadRequest$inboundSchema: z.ZodMiniType<PostNsByNamespaceDocumentFileBadRequest, unknown> = smartUnion([
  z.lazy(() => ErrorResponse$inboundSchema),
  z.lazy(() => ValidationErrorResponse$inboundSchema),
]);

export function postNsByNamespaceDocumentFileBadRequestFromJSON(
  jsonString: string,
): SafeParseResult<PostNsByNamespaceDocumentFileBadRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostNsByNamespaceDocumentFileBadRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostNsByNamespaceDocumentFileBadRequest' from JSON`,
  );
}
