/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 149d5e161614
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import {
  ErrorResponse,
  ErrorResponse$inboundSchema,
} from "./error-response.js";
import { SDKValidationError } from "./sdk-validation-error.js";
import {
  ValidationErrorResponse,
  ValidationErrorResponse$inboundSchema,
} from "./validation-error-response.js";

/**
 * Invalid file request
 */
export type PostNsByNamespaceDocumentFileBadRequest =
  | ErrorResponse
  | ValidationErrorResponse;

/** @internal */
export const PostNsByNamespaceDocumentFileBadRequest$inboundSchema:
  z.ZodMiniType<PostNsByNamespaceDocumentFileBadRequest, unknown> = smartUnion([
    ErrorResponse$inboundSchema,
    ValidationErrorResponse$inboundSchema,
  ]);

export function postNsByNamespaceDocumentFileBadRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  PostNsByNamespaceDocumentFileBadRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostNsByNamespaceDocumentFileBadRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PostNsByNamespaceDocumentFileBadRequest' from JSON`,
  );
}
