/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5d6c0212071c
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import {
  ErrorResponse,
  ErrorResponse$inboundSchema,
} from "./error-response.js";
import { SDKValidationError } from "./sdk-validation-error.js";
import {
  ValidationErrorResponse,
  ValidationErrorResponse$inboundSchema,
} from "./validation-error-response.js";

/**
 * Invalid request
 */
export type PostNsByNamespaceConnectorsByIdSyncBadRequest =
  | ErrorResponse
  | ValidationErrorResponse;

/** @internal */
export const PostNsByNamespaceConnectorsByIdSyncBadRequest$inboundSchema:
  z.ZodMiniType<PostNsByNamespaceConnectorsByIdSyncBadRequest, unknown> =
    smartUnion([
      ErrorResponse$inboundSchema,
      ValidationErrorResponse$inboundSchema,
    ]);

export function postNsByNamespaceConnectorsByIdSyncBadRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  PostNsByNamespaceConnectorsByIdSyncBadRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostNsByNamespaceConnectorsByIdSyncBadRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PostNsByNamespaceConnectorsByIdSyncBadRequest' from JSON`,
  );
}
