/*
 * Generated by scripts/surface/generate.ts from fern/openapi.json. DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SupermemoryCore } from "../core.js";
import { OperationSpec, invoke } from "../lib/invoke.js";
import * as M from "../lib/matchers.js";
import { RequestOptions } from "../lib/sdks.js";
import { ErrorResponse, ErrorResponse$inboundSchema } from "../models/errors/error-response.js";
import { ConnectionError, InvalidRequestError, RequestAbortedError, RequestTimeoutError, UnexpectedClientError } from "../models/errors/http-client-errors.js";
import { PostNsByNamespaceDocumentBadRequest, PostNsByNamespaceDocumentBadRequest$inboundSchema } from "../models/errors/post-ns-by-namespace-document.js";
import { ResponseValidationError } from "../models/errors/response-validation-error.js";
import { SDKValidationError } from "../models/errors/sdk-validation-error.js";
import { SupermemoryError } from "../models/errors/supermemory-error.js";
import { PostNsByNamespaceDocumentRequest, PostNsByNamespaceDocumentRequest$outboundSchema, PostNsByNamespaceDocumentResponse, PostNsByNamespaceDocumentResponse$inboundSchema } from "../models/operations/post-ns-by-namespace-document.js";
import { APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

const spec: OperationSpec = {
  operationID: "postNsByNamespaceDocument",
  method: "POST",
  path: "/ns/{namespace}/document",
  fern: [
    "add"
  ],
  params: [
    {
      name: "namespace",
      in: "path"
    },
    {
      name: "taskType",
      in: "query"
    },
    {
      name: "dreaming",
      in: "query"
    }
  ],
  body: {
    key: "body",
    contentType: "application/json",
    fernWrapped: false
  },
  accept: "application/json"
};

/**
 * Turn text or a supported URL into searchable, evolving memory. Supply a new ID to create a document, or reuse an existing ID to append new information while preserving its history.
 */
export function add(
  client: SupermemoryCore,
  request: PostNsByNamespaceDocumentRequest,
  options?: RequestOptions,
): APIPromise<
  Result<
    PostNsByNamespaceDocumentResponse,
    | PostNsByNamespaceDocumentBadRequest
    | ErrorResponse
    | SupermemoryError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >
> {
  return invoke(client, spec, request, PostNsByNamespaceDocumentRequest$outboundSchema, options, [
    M.json(200, z.lazy(() => PostNsByNamespaceDocumentResponse$inboundSchema)),
    M.jsonErr(400, PostNsByNamespaceDocumentBadRequest$inboundSchema),
    M.jsonErr([401, 402, 403, 409], ErrorResponse$inboundSchema),
    M.jsonErr(500, ErrorResponse$inboundSchema),
    M.fail("4XX"),
    M.fail("5XX"),
  ]);
}
