/*
 * Generated by scripts/surface/generate.ts from fern/openapi.json. DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SupermemoryCore } from "../core.js";
import { OperationSpec, invoke } from "../lib/invoke.js";
import * as M from "../lib/matchers.js";
import { RequestOptions } from "../lib/sdks.js";
import { ErrorResponse, ErrorResponse$inboundSchema } from "../models/errors/error-response.js";
import { GetNsByNamespaceConnectorsBadRequest, GetNsByNamespaceConnectorsBadRequest$inboundSchema } from "../models/errors/get-ns-by-namespace-connectors.js";
import { ConnectionError, InvalidRequestError, RequestAbortedError, RequestTimeoutError, UnexpectedClientError } from "../models/errors/http-client-errors.js";
import { ResponseValidationError } from "../models/errors/response-validation-error.js";
import { SDKValidationError } from "../models/errors/sdk-validation-error.js";
import { SupermemoryError } from "../models/errors/supermemory-error.js";
import { GetNsByNamespaceConnectorsRequest, GetNsByNamespaceConnectorsRequest$outboundSchema, GetNsByNamespaceConnectorsResponse, GetNsByNamespaceConnectorsResponse$inboundSchema } from "../models/operations/get-ns-by-namespace-connectors.js";
import { APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

const spec: OperationSpec = {
  operationID: "getNsByNamespaceConnectors",
  method: "GET",
  path: "/ns/{namespace}/connectors",
  fern: [
    "connectors",
    "list"
  ],
  params: [
    {
      name: "namespace",
      in: "path"
    },
    {
      name: "provider",
      in: "query"
    },
    {
      name: "page",
      in: "query"
    },
    {
      name: "limit",
      in: "query"
    }
  ],
  body: null,
  accept: "application/json"
};

/**
 * List the connectors that sync into this namespace.
 */
export function connectorsList(
  client: SupermemoryCore,
  request: GetNsByNamespaceConnectorsRequest,
  options?: RequestOptions,
): APIPromise<
  Result<
    GetNsByNamespaceConnectorsResponse,
    | GetNsByNamespaceConnectorsBadRequest
    | ErrorResponse
    | SupermemoryError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >
> {
  return invoke(client, spec, request, GetNsByNamespaceConnectorsRequest$outboundSchema, options, [
    M.json(200, z.lazy(() => GetNsByNamespaceConnectorsResponse$inboundSchema)),
    M.jsonErr(400, GetNsByNamespaceConnectorsBadRequest$inboundSchema),
    M.jsonErr([401, 403], ErrorResponse$inboundSchema),
    M.jsonErr(500, ErrorResponse$inboundSchema),
    M.fail("4XX"),
    M.fail("5XX"),
  ]);
}
