/*
 * Generated by scripts/surface/generate.ts from fern/openapi.json. DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SupermemoryCore } from "../core.js";
import { OperationSpec, invoke } from "../lib/invoke.js";
import * as M from "../lib/matchers.js";
import { RequestOptions } from "../lib/sdks.js";
import { ErrorResponse, ErrorResponse$inboundSchema } from "../models/errors/error-response.js";
import { ConnectionError, InvalidRequestError, RequestAbortedError, RequestTimeoutError, UnexpectedClientError } from "../models/errors/http-client-errors.js";
import { PostNsByNamespaceConnectorsByIdSyncBadRequest, PostNsByNamespaceConnectorsByIdSyncBadRequest$inboundSchema } from "../models/errors/post-ns-by-namespace-connectors-by-id-sync.js";
import { ResponseValidationError } from "../models/errors/response-validation-error.js";
import { SDKValidationError } from "../models/errors/sdk-validation-error.js";
import { SupermemoryError } from "../models/errors/supermemory-error.js";
import { PostNsByNamespaceConnectorsByIdSyncRequest, PostNsByNamespaceConnectorsByIdSyncRequest$outboundSchema, PostNsByNamespaceConnectorsByIdSyncResponse, PostNsByNamespaceConnectorsByIdSyncResponse$inboundSchema } from "../models/operations/post-ns-by-namespace-connectors-by-id-sync.js";
import { APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

const spec: OperationSpec = {
  operationID: "postNsByNamespaceConnectorsByIdSync",
  method: "POST",
  path: "/ns/{namespace}/connectors/{id}/sync",
  fern: [
    "connectors",
    "sync"
  ],
  params: [
    {
      name: "namespace",
      in: "path"
    },
    {
      name: "id",
      in: "path"
    }
  ],
  body: null,
  accept: "application/json"
};

/**
 * Start a sync now. Returns 409 while a sync for this connector is already running.
 */
export function connectorsSync(
  client: SupermemoryCore,
  request: PostNsByNamespaceConnectorsByIdSyncRequest,
  options?: RequestOptions,
): APIPromise<
  Result<
    PostNsByNamespaceConnectorsByIdSyncResponse,
    | PostNsByNamespaceConnectorsByIdSyncBadRequest
    | ErrorResponse
    | SupermemoryError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >
> {
  return invoke(client, spec, request, PostNsByNamespaceConnectorsByIdSyncRequest$outboundSchema, options, [
    M.json(202, z.lazy(() => PostNsByNamespaceConnectorsByIdSyncResponse$inboundSchema)),
    M.jsonErr(400, PostNsByNamespaceConnectorsByIdSyncBadRequest$inboundSchema),
    M.jsonErr([401, 402, 403, 404, 409], ErrorResponse$inboundSchema),
    M.jsonErr([500, 503], ErrorResponse$inboundSchema),
    M.fail("4XX"),
    M.fail("5XX"),
  ]);
}
