/*
 * Generated by scripts/surface/generate.ts from fern/openapi.json. DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SupermemoryCore } from "../core.js";
import { OperationSpec, invoke } from "../lib/invoke.js";
import * as M from "../lib/matchers.js";
import { RequestOptions } from "../lib/sdks.js";
import { ErrorResponse, ErrorResponse$inboundSchema } from "../models/errors/error-response.js";
import { ConnectionError, InvalidRequestError, RequestAbortedError, RequestTimeoutError, UnexpectedClientError } from "../models/errors/http-client-errors.js";
import { PatchNsByNamespaceDocumentFileByIdBadRequest, PatchNsByNamespaceDocumentFileByIdBadRequest$inboundSchema } from "../models/errors/patch-ns-by-namespace-document-file-by-id.js";
import { ResponseValidationError } from "../models/errors/response-validation-error.js";
import { SDKValidationError } from "../models/errors/sdk-validation-error.js";
import { SupermemoryError } from "../models/errors/supermemory-error.js";
import { PatchNsByNamespaceDocumentFileByIdRequest, PatchNsByNamespaceDocumentFileByIdRequest$outboundSchema, PatchNsByNamespaceDocumentFileByIdResponse, PatchNsByNamespaceDocumentFileByIdResponse$inboundSchema } from "../models/operations/patch-ns-by-namespace-document-file-by-id.js";
import { APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

const spec: OperationSpec = {
  operationID: "patchNsByNamespaceDocumentFileById",
  method: "PATCH",
  path: "/ns/{namespace}/document/file/{id}",
  fern: [
    "documents",
    "updateFile"
  ],
  params: [
    {
      name: "namespace",
      in: "path"
    },
    {
      name: "id",
      in: "path"
    },
    {
      name: "taskType",
      in: "query"
    },
    {
      name: "dreaming",
      in: "query"
    },
    {
      name: "fileType",
      in: "query"
    },
    {
      name: "mimeType",
      in: "query"
    }
  ],
  body: {
    key: "body",
    contentType: "multipart/form-data",
    fernWrapped: false,
    fileFields: [
      "file"
    ]
  },
  accept: "application/json"
};

/**
 * Refresh only the file-backed fields you provide. Supplying a file replaces the canonical content; omitted metadata and processing context remain unchanged.
 */
export function documentsUpdateFile(
  client: SupermemoryCore,
  request: PatchNsByNamespaceDocumentFileByIdRequest,
  options?: RequestOptions,
): APIPromise<
  Result<
    PatchNsByNamespaceDocumentFileByIdResponse,
    | PatchNsByNamespaceDocumentFileByIdBadRequest
    | ErrorResponse
    | SupermemoryError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >
> {
  return invoke(client, spec, request, PatchNsByNamespaceDocumentFileByIdRequest$outboundSchema, options, [
    M.json(200, z.lazy(() => PatchNsByNamespaceDocumentFileByIdResponse$inboundSchema)),
    M.jsonErr(400, PatchNsByNamespaceDocumentFileByIdBadRequest$inboundSchema),
    M.jsonErr([401, 402, 403, 404, 409], ErrorResponse$inboundSchema),
    M.jsonErr(500, ErrorResponse$inboundSchema),
    M.fail("4XX"),
    M.fail("5XX"),
  ]);
}
