/*
 * Generated by scripts/surface/generate.ts from fern/openapi.json. DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SupermemoryCore } from "../core.js";
import { OperationSpec, invoke } from "../lib/invoke.js";
import * as M from "../lib/matchers.js";
import { RequestOptions } from "../lib/sdks.js";
import { ErrorResponse, ErrorResponse$inboundSchema } from "../models/errors/error-response.js";
import { GetNsByNamespaceDocumentByIdBadRequest, GetNsByNamespaceDocumentByIdBadRequest$inboundSchema } from "../models/errors/get-ns-by-namespace-document-by-id.js";
import { ConnectionError, InvalidRequestError, RequestAbortedError, RequestTimeoutError, UnexpectedClientError } from "../models/errors/http-client-errors.js";
import { ResponseValidationError } from "../models/errors/response-validation-error.js";
import { SDKValidationError } from "../models/errors/sdk-validation-error.js";
import { SupermemoryError } from "../models/errors/supermemory-error.js";
import { GetNsByNamespaceDocumentByIdRequest, GetNsByNamespaceDocumentByIdRequest$outboundSchema, GetNsByNamespaceDocumentByIdResponse, GetNsByNamespaceDocumentByIdResponse$inboundSchema } from "../models/operations/get-ns-by-namespace-document-by-id.js";
import { APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

const spec: OperationSpec = {
  operationID: "getNsByNamespaceDocumentById",
  method: "GET",
  path: "/ns/{namespace}/document/{id}",
  fern: [
    "documents",
    "get"
  ],
  params: [
    {
      name: "namespace",
      in: "path"
    },
    {
      name: "id",
      in: "path"
    },
    {
      name: "attach",
      in: "query"
    }
  ],
  body: null,
  accept: "application/json"
};

/**
 * Retrieve a document's canonical content, metadata, and processing state by document ID or caller-defined ID. Optionally attach its source chunks, derived memories, or both in the same response.
 */
export function documentsGet(
  client: SupermemoryCore,
  request: GetNsByNamespaceDocumentByIdRequest,
  options?: RequestOptions,
): APIPromise<
  Result<
    GetNsByNamespaceDocumentByIdResponse,
    | GetNsByNamespaceDocumentByIdBadRequest
    | ErrorResponse
    | SupermemoryError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >
> {
  return invoke(client, spec, request, GetNsByNamespaceDocumentByIdRequest$outboundSchema, options, [
    M.json(200, z.lazy(() => GetNsByNamespaceDocumentByIdResponse$inboundSchema)),
    M.jsonErr(400, GetNsByNamespaceDocumentByIdBadRequest$inboundSchema),
    M.jsonErr([401, 403, 404], ErrorResponse$inboundSchema),
    M.jsonErr(500, ErrorResponse$inboundSchema),
    M.fail("4XX"),
    M.fail("5XX"),
  ]);
}
