/*
 * Generated by scripts/surface/generate.ts from fern/openapi.json. DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SupermemoryCore } from "../core.js";
import { OperationSpec, invoke } from "../lib/invoke.js";
import * as M from "../lib/matchers.js";
import { RequestOptions } from "../lib/sdks.js";
import { ErrorResponse, ErrorResponse$inboundSchema } from "../models/errors/error-response.js";
import { ConnectionError, InvalidRequestError, RequestAbortedError, RequestTimeoutError, UnexpectedClientError } from "../models/errors/http-client-errors.js";
import { PostNsByNamespaceDocumentBatchBadRequest, PostNsByNamespaceDocumentBatchBadRequest$inboundSchema } from "../models/errors/post-ns-by-namespace-document-batch.js";
import { ResponseValidationError } from "../models/errors/response-validation-error.js";
import { SDKValidationError } from "../models/errors/sdk-validation-error.js";
import { SupermemoryError } from "../models/errors/supermemory-error.js";
import { PostNsByNamespaceDocumentBatchRequest, PostNsByNamespaceDocumentBatchRequest$outboundSchema, PostNsByNamespaceDocumentBatchResponse, PostNsByNamespaceDocumentBatchResponse$inboundSchema } from "../models/operations/post-ns-by-namespace-document-batch.js";
import { APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

const spec: OperationSpec = {
  operationID: "postNsByNamespaceDocumentBatch",
  method: "POST",
  path: "/ns/{namespace}/document/batch",
  fern: [
    "documents",
    "batchAdd"
  ],
  params: [
    {
      name: "namespace",
      in: "path"
    },
    {
      name: "taskType",
      in: "query"
    },
    {
      name: "dreaming",
      in: "query"
    }
  ],
  body: {
    key: "body",
    contentType: "application/json",
    fernWrapped: false
  },
  accept: "application/json"
};

/**
 * Build a knowledge base efficiently by ingesting up to 600 text or URL documents at once. Existing caller-defined IDs append new information using the same semantics as single-document ingestion.
 */
export function documentsBatchAdd(
  client: SupermemoryCore,
  request: PostNsByNamespaceDocumentBatchRequest,
  options?: RequestOptions,
): APIPromise<
  Result<
    PostNsByNamespaceDocumentBatchResponse,
    | PostNsByNamespaceDocumentBatchBadRequest
    | ErrorResponse
    | SupermemoryError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >
> {
  return invoke(client, spec, request, PostNsByNamespaceDocumentBatchRequest$outboundSchema, options, [
    M.json(200, z.lazy(() => PostNsByNamespaceDocumentBatchResponse$inboundSchema)),
    M.jsonErr(400, PostNsByNamespaceDocumentBatchBadRequest$inboundSchema),
    M.jsonErr([401, 402, 403], ErrorResponse$inboundSchema),
    M.jsonErr(500, ErrorResponse$inboundSchema),
    M.fail("4XX"),
    M.fail("5XX"),
  ]);
}
