/*
 * Generated by scripts/surface/generate.ts from fern/openapi.json. DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SupermemoryCore } from "../core.js";
import { OperationSpec, invoke } from "../lib/invoke.js";
import * as M from "../lib/matchers.js";
import { RequestOptions } from "../lib/sdks.js";
import { DeleteNsByNamespaceMemoriesSemanticBadRequest, DeleteNsByNamespaceMemoriesSemanticBadRequest$inboundSchema } from "../models/errors/delete-ns-by-namespace-memories-semantic.js";
import { ErrorResponse, ErrorResponse$inboundSchema } from "../models/errors/error-response.js";
import { ConnectionError, InvalidRequestError, RequestAbortedError, RequestTimeoutError, UnexpectedClientError } from "../models/errors/http-client-errors.js";
import { ResponseValidationError } from "../models/errors/response-validation-error.js";
import { SDKValidationError } from "../models/errors/sdk-validation-error.js";
import { SupermemoryError } from "../models/errors/supermemory-error.js";
import { DeleteNsByNamespaceMemoriesSemanticRequest, DeleteNsByNamespaceMemoriesSemanticRequest$outboundSchema, DeleteNsByNamespaceMemoriesSemanticResponse, DeleteNsByNamespaceMemoriesSemanticResponse$inboundSchema } from "../models/operations/delete-ns-by-namespace-memories-semantic.js";
import { APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

const spec: OperationSpec = {
  operationID: "deleteNsByNamespaceMemoriesSemantic",
  method: "DELETE",
  path: "/ns/{namespace}/memories/semantic",
  fern: [
    "memories",
    "forgetMatching"
  ],
  params: [
    {
      name: "namespace",
      in: "path"
    }
  ],
  body: {
    key: "body",
    contentType: "application/json",
    fernWrapped: false
  },
  accept: "application/json"
};

/**
 * Describe what should be forgotten in natural language, then preview or apply the matching set. Use dry-run results with the exact-ID endpoint when you need a reviewable, drift-free workflow.
 */
export function memoriesForgetMatching(
  client: SupermemoryCore,
  request: DeleteNsByNamespaceMemoriesSemanticRequest,
  options?: RequestOptions,
): APIPromise<
  Result<
    DeleteNsByNamespaceMemoriesSemanticResponse,
    | DeleteNsByNamespaceMemoriesSemanticBadRequest
    | ErrorResponse
    | SupermemoryError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >
> {
  return invoke(client, spec, request, DeleteNsByNamespaceMemoriesSemanticRequest$outboundSchema, options, [
    M.json(200, z.lazy(() => DeleteNsByNamespaceMemoriesSemanticResponse$inboundSchema)),
    M.jsonErr(400, DeleteNsByNamespaceMemoriesSemanticBadRequest$inboundSchema),
    M.jsonErr([401, 403], ErrorResponse$inboundSchema),
    M.jsonErr(500, ErrorResponse$inboundSchema),
    M.fail("4XX"),
    M.fail("5XX"),
  ]);
}
