/*
 * Generated by scripts/surface/generate.ts from fern/openapi.json. DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SupermemoryCore } from "../core.js";
import { OperationSpec, invoke } from "../lib/invoke.js";
import * as M from "../lib/matchers.js";
import { RequestOptions } from "../lib/sdks.js";
import { ErrorResponse, ErrorResponse$inboundSchema } from "../models/errors/error-response.js";
import { ConnectionError, InvalidRequestError, RequestAbortedError, RequestTimeoutError, UnexpectedClientError } from "../models/errors/http-client-errors.js";
import { ResponseValidationError } from "../models/errors/response-validation-error.js";
import { SDKValidationError } from "../models/errors/sdk-validation-error.js";
import { SupermemoryError } from "../models/errors/supermemory-error.js";
import { GetNsResponse, GetNsResponse$inboundSchema } from "../models/operations/get-ns.js";
import { APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

const spec: OperationSpec = {
  operationID: "getNs",
  method: "GET",
  path: "/ns",
  fern: [
    "namespaces",
    "list"
  ],
  params: [],
  body: null,
  accept: "application/json"
};

/**
 * Discover every namespace available to the caller, including its purpose, document volume, memory count, and lifecycle timestamps.
 */
export function namespacesList(
  client: SupermemoryCore,
  options?: RequestOptions,
): APIPromise<
  Result<
    Array<GetNsResponse>,
    | ErrorResponse
    | SupermemoryError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >
> {
  return invoke(client, spec, undefined, undefined, options, [
    M.json(200, z.array(z.lazy(() => GetNsResponse$inboundSchema))),
    M.jsonErr([401, 403], ErrorResponse$inboundSchema),
    M.jsonErr(500, ErrorResponse$inboundSchema),
    M.fail("4XX"),
    M.fail("5XX"),
  ]);
}
