/*
 * Generated by scripts/surface/generate.ts from fern/openapi.json. DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SupermemoryCore } from "../core.js";
import { OperationSpec, invoke } from "../lib/invoke.js";
import * as M from "../lib/matchers.js";
import { RequestOptions } from "../lib/sdks.js";
import { ErrorResponse, ErrorResponse$inboundSchema } from "../models/errors/error-response.js";
import { ConnectionError, InvalidRequestError, RequestAbortedError, RequestTimeoutError, UnexpectedClientError } from "../models/errors/http-client-errors.js";
import { PatchNsByNamespaceBadRequest, PatchNsByNamespaceBadRequest$inboundSchema } from "../models/errors/patch-ns-by-namespace.js";
import { ResponseValidationError } from "../models/errors/response-validation-error.js";
import { SDKValidationError } from "../models/errors/sdk-validation-error.js";
import { SupermemoryError } from "../models/errors/supermemory-error.js";
import { PatchNsByNamespaceRequest, PatchNsByNamespaceRequest$outboundSchema, PatchNsByNamespaceResponse, PatchNsByNamespaceResponse$inboundSchema } from "../models/operations/patch-ns-by-namespace.js";
import { APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

const spec: OperationSpec = {
  operationID: "patchNsByNamespace",
  method: "PATCH",
  path: "/ns/{namespace}",
  fern: [
    "namespaces",
    "update"
  ],
  params: [
    {
      name: "namespace",
      in: "path"
    }
  ],
  body: {
    key: "body",
    contentType: "application/json",
    fernWrapped: false
  },
  accept: "application/json"
};

/**
 * Shape how Supermemory understands an existing namespace by updating the background context used during ingestion and memory formation.
 */
export function namespacesUpdate(
  client: SupermemoryCore,
  request: PatchNsByNamespaceRequest,
  options?: RequestOptions,
): APIPromise<
  Result<
    PatchNsByNamespaceResponse,
    | PatchNsByNamespaceBadRequest
    | ErrorResponse
    | SupermemoryError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >
> {
  return invoke(client, spec, request, PatchNsByNamespaceRequest$outboundSchema, options, [
    M.json(200, z.lazy(() => PatchNsByNamespaceResponse$inboundSchema)),
    M.jsonErr(400, PatchNsByNamespaceBadRequest$inboundSchema),
    M.jsonErr([401, 403, 404], ErrorResponse$inboundSchema),
    M.jsonErr(500, ErrorResponse$inboundSchema),
    M.fail("4XX"),
    M.fail("5XX"),
  ]);
}
