/*
 * Generated by scripts/surface/generate.ts from fern/openapi.json. DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SupermemoryCore } from "../core.js";
import { OperationSpec, invoke } from "../lib/invoke.js";
import * as M from "../lib/matchers.js";
import { RequestOptions } from "../lib/sdks.js";
import { ErrorResponse, ErrorResponse$inboundSchema } from "../models/errors/error-response.js";
import { ConnectionError, InvalidRequestError, RequestAbortedError, RequestTimeoutError, UnexpectedClientError } from "../models/errors/http-client-errors.js";
import { PatchOrganizationBadRequest, PatchOrganizationBadRequest$inboundSchema } from "../models/errors/patch-organization.js";
import { ResponseValidationError } from "../models/errors/response-validation-error.js";
import { SDKValidationError } from "../models/errors/sdk-validation-error.js";
import { SupermemoryError } from "../models/errors/supermemory-error.js";
import { PatchOrganizationRequest, PatchOrganizationRequest$outboundSchema, PatchOrganizationResponse, PatchOrganizationResponse$inboundSchema } from "../models/operations/patch-organization.js";
import { APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

const spec: OperationSpec = {
  operationID: "patchOrganization",
  method: "PATCH",
  path: "/organization",
  fern: [
    "organization",
    "update"
  ],
  params: [],
  body: {
    key: null,
    contentType: "application/json",
    fernWrapped: false
  },
  accept: "application/json"
};

/**
 * Give Supermemory organization-wide background that improves how content is interpreted across every namespace. Send null to remove the existing context.
 */
export function organizationUpdate(
  client: SupermemoryCore,
  request: PatchOrganizationRequest,
  options?: RequestOptions,
): APIPromise<
  Result<
    PatchOrganizationResponse,
    | PatchOrganizationBadRequest
    | ErrorResponse
    | SupermemoryError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >
> {
  return invoke(client, spec, request, PatchOrganizationRequest$outboundSchema, options, [
    M.json(200, z.lazy(() => PatchOrganizationResponse$inboundSchema)),
    M.jsonErr(400, PatchOrganizationBadRequest$inboundSchema),
    M.jsonErr([401, 403], ErrorResponse$inboundSchema),
    M.jsonErr(500, ErrorResponse$inboundSchema),
    M.fail("4XX"),
    M.fail("5XX"),
  ]);
}
