/*
 * Generated by scripts/surface/generate.ts from fern/openapi.json. DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SupermemoryCore } from "../core.js";
import { OperationSpec, invoke } from "../lib/invoke.js";
import * as M from "../lib/matchers.js";
import { RequestOptions } from "../lib/sdks.js";
import { ErrorResponse, ErrorResponse$inboundSchema } from "../models/errors/error-response.js";
import { ConnectionError, InvalidRequestError, RequestAbortedError, RequestTimeoutError, UnexpectedClientError } from "../models/errors/http-client-errors.js";
import { PutNsByNamespaceProfileBucketsBadRequest, PutNsByNamespaceProfileBucketsBadRequest$inboundSchema } from "../models/errors/put-ns-by-namespace-profile-buckets.js";
import { ResponseValidationError } from "../models/errors/response-validation-error.js";
import { SDKValidationError } from "../models/errors/sdk-validation-error.js";
import { SupermemoryError } from "../models/errors/supermemory-error.js";
import { PutNsByNamespaceProfileBucketsRequest, PutNsByNamespaceProfileBucketsRequest$outboundSchema, PutNsByNamespaceProfileBucketsResponse, PutNsByNamespaceProfileBucketsResponse$inboundSchema } from "../models/operations/put-ns-by-namespace-profile-buckets.js";
import { APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

const spec: OperationSpec = {
  operationID: "putNsByNamespaceProfileBuckets",
  method: "PUT",
  path: "/ns/{namespace}/profile/buckets",
  fern: [
    "profiles",
    "setBuckets"
  ],
  params: [
    {
      name: "namespace",
      in: "path"
    }
  ],
  body: {
    key: "body",
    contentType: "application/json",
    fernWrapped: false
  },
  accept: "application/json"
};

/**
 * Teach Supermemory new ways to organize this namespace's profile, or refine how existing namespace-owned buckets are classified. Omitted buckets remain unchanged and organization-wide buckets stay protected.
 */
export function profilesSetBuckets(
  client: SupermemoryCore,
  request: PutNsByNamespaceProfileBucketsRequest,
  options?: RequestOptions,
): APIPromise<
  Result<
    PutNsByNamespaceProfileBucketsResponse,
    | PutNsByNamespaceProfileBucketsBadRequest
    | ErrorResponse
    | SupermemoryError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >
> {
  return invoke(client, spec, request, PutNsByNamespaceProfileBucketsRequest$outboundSchema, options, [
    M.json(200, z.lazy(() => PutNsByNamespaceProfileBucketsResponse$inboundSchema)),
    M.jsonErr(400, PutNsByNamespaceProfileBucketsBadRequest$inboundSchema),
    M.jsonErr([401, 403, 404, 409], ErrorResponse$inboundSchema),
    M.jsonErr(500, ErrorResponse$inboundSchema),
    M.fail("4XX"),
    M.fail("5XX"),
  ]);
}
