/*
 * Generated by scripts/surface/generate.ts from fern/openapi.json. DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SupermemoryCore } from "../core.js";
import { OperationSpec, invoke } from "../lib/invoke.js";
import * as M from "../lib/matchers.js";
import { RequestOptions } from "../lib/sdks.js";
import { ErrorResponse, ErrorResponse$inboundSchema } from "../models/errors/error-response.js";
import { ConnectionError, InvalidRequestError, RequestAbortedError, RequestTimeoutError, UnexpectedClientError } from "../models/errors/http-client-errors.js";
import { PostNsByNamespaceSearchBadRequest, PostNsByNamespaceSearchBadRequest$inboundSchema } from "../models/errors/post-ns-by-namespace-search.js";
import { ResponseValidationError } from "../models/errors/response-validation-error.js";
import { SDKValidationError } from "../models/errors/sdk-validation-error.js";
import { SupermemoryError } from "../models/errors/supermemory-error.js";
import { PostNsByNamespaceSearchRequest, PostNsByNamespaceSearchRequest$outboundSchema, PostNsByNamespaceSearchResponse, PostNsByNamespaceSearchResponse$inboundSchema } from "../models/operations/post-ns-by-namespace-search.js";
import { APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

const spec: OperationSpec = {
  operationID: "postNsByNamespaceSearch",
  method: "POST",
  path: "/ns/{namespace}/search",
  fern: [
    "search"
  ],
  params: [
    {
      name: "namespace",
      in: "path"
    },
    {
      name: "limit",
      in: "query"
    },
    {
      name: "searchMode",
      in: "query"
    }
  ],
  body: {
    key: "body",
    contentType: "application/json",
    fernWrapped: false
  },
  accept: "application/json"
};

/**
 * Recall the most relevant learned context and source passages from a namespace. Hybrid search combines memories with document chunks by default, with optional query rewriting, reranking, and supporting context attachments.
 */
export function search(
  client: SupermemoryCore,
  request: PostNsByNamespaceSearchRequest,
  options?: RequestOptions,
): APIPromise<
  Result<
    PostNsByNamespaceSearchResponse,
    | PostNsByNamespaceSearchBadRequest
    | ErrorResponse
    | SupermemoryError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >
> {
  return invoke(client, spec, request, PostNsByNamespaceSearchRequest$outboundSchema, options, [
    M.json(200, z.lazy(() => PostNsByNamespaceSearchResponse$inboundSchema)),
    M.jsonErr(400, PostNsByNamespaceSearchBadRequest$inboundSchema),
    M.jsonErr([401, 402, 403], ErrorResponse$inboundSchema),
    M.jsonErr(500, ErrorResponse$inboundSchema),
    M.fail("4XX"),
    M.fail("5XX"),
  ]);
}
