/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 2dda252d574b
 */

import { connectorsDeleteNsByNamespaceConnectorsById } from "../funcs/connectors-delete-ns-by-namespace-connectors-by-id.js";
import { connectorsGetConnectors } from "../funcs/connectors-get-connectors.js";
import { connectorsGetNsByNamespaceConnectorsById } from "../funcs/connectors-get-ns-by-namespace-connectors-by-id.js";
import { connectorsGetNsByNamespaceConnectors } from "../funcs/connectors-get-ns-by-namespace-connectors.js";
import { connectorsPatchNsByNamespaceConnectorsById } from "../funcs/connectors-patch-ns-by-namespace-connectors-by-id.js";
import { connectorsPostNsByNamespaceConnectorsByIdSync } from "../funcs/connectors-post-ns-by-namespace-connectors-by-id-sync.js";
import { connectorsPostNsByNamespaceConnectors } from "../funcs/connectors-post-ns-by-namespace-connectors.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Connectors extends ClientSDK {
  /**
   * List all connectors
   *
   * @remarks
   * List connectors across every namespace this key can read. Use it for admin views that span users or projects.
   */
  async getConnectors(
    request?: operations.GetConnectorsRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetConnectorsResponse> {
    return unwrapAsync(connectorsGetConnectors(
      this,
      request,
      options,
    ));
  }

  /**
   * Create connector
   *
   * @remarks
   * Connect an external source to this namespace. OAuth providers return an authUrl to send the user to; providers that authenticate with config start syncing right away.
   */
  async postNsByNamespaceConnectors(
    request: operations.PostNsByNamespaceConnectorsRequest,
    options?: RequestOptions,
  ): Promise<operations.PostNsByNamespaceConnectorsResponse> {
    return unwrapAsync(connectorsPostNsByNamespaceConnectors(
      this,
      request,
      options,
    ));
  }

  /**
   * List connectors
   *
   * @remarks
   * List the connectors that sync into this namespace.
   */
  async getNsByNamespaceConnectors(
    request: operations.GetNsByNamespaceConnectorsRequest,
    options?: RequestOptions,
  ): Promise<operations.GetNsByNamespaceConnectorsResponse> {
    return unwrapAsync(connectorsGetNsByNamespaceConnectors(
      this,
      request,
      options,
    ));
  }

  /**
   * Get connector
   *
   * @remarks
   * Read one connector. Add attach=syncs to include its recent sync runs and the items that failed. attach=picker needs an admin with write access, since the link changes what syncs.
   */
  async getNsByNamespaceConnectorsById(
    request: operations.GetNsByNamespaceConnectorsByIdRequest,
    options?: RequestOptions,
  ): Promise<operations.GetNsByNamespaceConnectorsByIdResponse> {
    return unwrapAsync(connectorsGetNsByNamespaceConnectorsById(
      this,
      request,
      options,
    ));
  }

  /**
   * Update connector
   *
   * @remarks
   * Change what a connector syncs. A new selection replaces the old one and starts a sync.
   */
  async patchNsByNamespaceConnectorsById(
    request: operations.PatchNsByNamespaceConnectorsByIdRequest,
    options?: RequestOptions,
  ): Promise<operations.PatchNsByNamespaceConnectorsByIdResponse> {
    return unwrapAsync(connectorsPatchNsByNamespaceConnectorsById(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete connector
   *
   * @remarks
   * Disconnect a connector and stop its webhooks. Its imported documents are deleted too unless deleteDocuments is false.
   */
  async deleteNsByNamespaceConnectorsById(
    request: operations.DeleteNsByNamespaceConnectorsByIdRequest,
    options?: RequestOptions,
  ): Promise<operations.DeleteNsByNamespaceConnectorsByIdResponse> {
    return unwrapAsync(connectorsDeleteNsByNamespaceConnectorsById(
      this,
      request,
      options,
    ));
  }

  /**
   * Sync connector
   *
   * @remarks
   * Start a sync now. Returns 409 while a sync for this connector is already running.
   */
  async postNsByNamespaceConnectorsByIdSync(
    request: operations.PostNsByNamespaceConnectorsByIdSyncRequest,
    options?: RequestOptions,
  ): Promise<operations.PostNsByNamespaceConnectorsByIdSyncResponse> {
    return unwrapAsync(connectorsPostNsByNamespaceConnectorsByIdSync(
      this,
      request,
      options,
    ));
  }
}
