/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c9dc1603c4f8
 */

import { connectionsConfigure } from "../funcs/connections-configure.js";
import { connectionsCreate } from "../funcs/connections-create.js";
import { connectionsDeleteByID } from "../funcs/connections-delete-by-id.js";
import { connectionsDeleteByProvider } from "../funcs/connections-delete-by-provider.js";
import { connectionsGetByID } from "../funcs/connections-get-by-id.js";
import { connectionsGetByTag } from "../funcs/connections-get-by-tag.js";
import { connectionsImport } from "../funcs/connections-import.js";
import { connectionsListDocuments } from "../funcs/connections-list-documents.js";
import { connectionsList } from "../funcs/connections-list.js";
import { connectionsResources } from "../funcs/connections-resources.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Connections extends ClientSDK {
  /**
   * List connections
   *
   * @remarks
   * List all connections
   */
  async list(
    request: operations.PostV3ConnectionsListRequest,
    options?: RequestOptions,
  ): Promise<Array<operations.PostV3ConnectionsListResponse>> {
    return unwrapAsync(connectionsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create connection
   *
   * @remarks
   * Initialize connection and get authorization URL
   */
  async create(
    request: operations.PostV3ConnectionsByProviderRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV3ConnectionsByProviderResponse> {
    return unwrapAsync(connectionsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete connection
   *
   * @remarks
   * Delete connection for a specific provider and container tags
   */
  async deleteByProvider(
    request: operations.DeleteV3ConnectionsByProviderRequest,
    options?: RequestOptions,
  ): Promise<Array<operations.DeleteV3ConnectionsByProviderResponse>> {
    return unwrapAsync(connectionsDeleteByProvider(
      this,
      request,
      options,
    ));
  }

  /**
   * Fetch resources
   *
   * @remarks
   * Fetch resources for a connection (supported providers: GitHub for now)
   */
  async resources(
    request: operations.GetV3ConnectionsByConnectionIdResourcesRequest,
    options?: RequestOptions,
  ): Promise<operations.GetV3ConnectionsByConnectionIdResourcesResponse> {
    return unwrapAsync(connectionsResources(
      this,
      request,
      options,
    ));
  }

  /**
   * Configure connection
   *
   * @remarks
   * Configure resources for a connection (supported providers: GitHub for now)
   */
  async configure(
    request: operations.PostV3ConnectionsByConnectionIdConfigureRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV3ConnectionsByConnectionIdConfigureResponse> {
    return unwrapAsync(connectionsConfigure(
      this,
      request,
      options,
    ));
  }

  /**
   * Get connection (by id)
   *
   * @remarks
   * Get connection details with id
   */
  async getByID(
    request: operations.GetV3ConnectionsByConnectionIdRequest,
    options?: RequestOptions,
  ): Promise<operations.GetV3ConnectionsByConnectionIdResponse> {
    return unwrapAsync(connectionsGetByID(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete connection by ID
   *
   * @remarks
   * Delete a specific connection by ID
   */
  async deleteByID(
    request: operations.DeleteV3ConnectionsByConnectionIdRequest,
    options?: RequestOptions,
  ): Promise<Array<operations.DeleteV3ConnectionsByConnectionIdResponse>> {
    return unwrapAsync(connectionsDeleteByID(
      this,
      request,
      options,
    ));
  }

  /**
   * Get connection (by provider)
   *
   * @remarks
   * Get connection details with provider and container tags
   */
  async getByTag(
    request: operations.PostV3ConnectionsByProviderConnectionRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV3ConnectionsByProviderConnectionResponse> {
    return unwrapAsync(connectionsGetByTag(
      this,
      request,
      options,
    ));
  }

  /**
   * List documents
   *
   * @remarks
   * List documents indexed for a provider and container tags
   */
  async listDocuments(
    request: operations.PostV3ConnectionsByProviderDocumentsRequest,
    options?: RequestOptions,
  ): Promise<Array<operations.PostV3ConnectionsByProviderDocumentsResponse>> {
    return unwrapAsync(connectionsListDocuments(
      this,
      request,
      options,
    ));
  }

  /**
   * Sync connection
   *
   * @remarks
   * Initiate a manual sync of connections
   */
  async import(
    request: operations.PostV3ConnectionsByProviderImportRequest,
    options?: RequestOptions,
  ): Promise<string> {
    return unwrapAsync(connectionsImport(
      this,
      request,
      options,
    ));
  }
}
