/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { documentsGetV3DocumentsByIdChunks } from "../funcs/documents-get-v3-documents-by-id-chunks.js";
import { documentsGetV3DocumentsByIdFileUrl } from "../funcs/documents-get-v3-documents-by-id-file-url.js";
import { documentsGetV3DocumentsById } from "../funcs/documents-get-v3-documents-by-id.js";
import { documentsGetV3DocumentsProcessing } from "../funcs/documents-get-v3-documents-processing.js";
import { documentsPostV3DocumentsList } from "../funcs/documents-post-v3-documents-list.js";
import { documentsPostV3Search } from "../funcs/documents-post-v3-search.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Documents extends ClientSDK {
  /**
   * Get document
   *
   * @remarks
   * Get a document by ID
   */
  async getV3DocumentsById(
    request: operations.GetV3DocumentsByIdRequest,
    options?: RequestOptions,
  ): Promise<operations.GetV3DocumentsByIdResponse> {
    return unwrapAsync(documentsGetV3DocumentsById(
      this,
      request,
      options,
    ));
  }

  /**
   * List documents
   *
   * @remarks
   * Retrieves a paginated list of documents with their metadata and workflow status
   */
  async postV3DocumentsList(
    request: operations.PostV3DocumentsListRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV3DocumentsListResponse> {
    return unwrapAsync(documentsPostV3DocumentsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Get processing documents
   *
   * @remarks
   * Get documents that are currently being processed
   */
  async getV3DocumentsProcessing(
    options?: RequestOptions,
  ): Promise<operations.GetV3DocumentsProcessingResponse> {
    return unwrapAsync(documentsGetV3DocumentsProcessing(
      this,
      options,
    ));
  }

  /**
   * Get document chunks
   *
   * @remarks
   * Get all chunks for a document, ordered by position
   */
  async getV3DocumentsByIdChunks(
    request: operations.GetV3DocumentsByIdChunksRequest,
    options?: RequestOptions,
  ): Promise<operations.GetV3DocumentsByIdChunksResponse> {
    return unwrapAsync(documentsGetV3DocumentsByIdChunks(
      this,
      request,
      options,
    ));
  }

  /**
   * Get presigned file URL
   *
   * @remarks
   * Get a fresh presigned URL for a document's file. Returns a time-limited URL (24h) that can be used to download the file.
   */
  async getV3DocumentsByIdFileUrl(
    request: operations.GetV3DocumentsByIdFileUrlRequest,
    options?: RequestOptions,
  ): Promise<operations.GetV3DocumentsByIdFileUrlResponse> {
    return unwrapAsync(documentsGetV3DocumentsByIdFileUrl(
      this,
      request,
      options,
    ));
  }

  /**
   * Search documents
   *
   * @remarks
   * Search memories with advanced filtering
   */
  async postV3Search(
    request: operations.PostV3SearchRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV3SearchResponse> {
    return unwrapAsync(documentsPostV3Search(
      this,
      request,
      options,
    ));
  }
}
