/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ingestDeleteV3DocumentsBulk } from "../funcs/ingest-delete-v3-documents-bulk.js";
import { ingestDeleteV3DocumentsById } from "../funcs/ingest-delete-v3-documents-by-id.js";
import { ingestPatchV3DocumentsById } from "../funcs/ingest-patch-v3-documents-by-id.js";
import { ingestPostV3DocumentsBatch } from "../funcs/ingest-post-v3-documents-batch.js";
import { ingestPostV3DocumentsFile } from "../funcs/ingest-post-v3-documents-file.js";
import { ingestPostV3Documents } from "../funcs/ingest-post-v3-documents.js";
import { ingestPostV4Conversations } from "../funcs/ingest-post-v4-conversations.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Ingest extends ClientSDK {
  /**
   * Add document
   *
   * @remarks
   * Add a document with any content type (text, url, file, etc.) and metadata
   */
  async postV3Documents(
    request: operations.PostV3DocumentsRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV3DocumentsResponse> {
    return unwrapAsync(ingestPostV3Documents(
      this,
      request,
      options,
    ));
  }

  /**
   * Batch add documents
   *
   * @remarks
   * Add multiple documents in a single request. Each document can have any content type (text, url, file, etc.) and metadata
   */
  async postV3DocumentsBatch(
    request: operations.PostV3DocumentsBatchRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV3DocumentsBatchResponse> {
    return unwrapAsync(ingestPostV3DocumentsBatch(
      this,
      request,
      options,
    ));
  }

  /**
   * Update document
   *
   * @remarks
   * Update a document with any content type (text, url, file, etc.) and metadata
   */
  async patchV3DocumentsById(
    request: operations.PatchV3DocumentsByIdRequest,
    options?: RequestOptions,
  ): Promise<operations.PatchV3DocumentsByIdResponse> {
    return unwrapAsync(ingestPatchV3DocumentsById(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete document by ID or customId
   *
   * @remarks
   * Delete a document by ID or customId
   */
  async deleteV3DocumentsById(
    request: operations.DeleteV3DocumentsByIdRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(ingestDeleteV3DocumentsById(
      this,
      request,
      options,
    ));
  }

  /**
   * Upload a file
   *
   * @remarks
   * Upload a file to be processed
   */
  async postV3DocumentsFile(
    request: operations.PostV3DocumentsFileRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV3DocumentsFileResponse> {
    return unwrapAsync(ingestPostV3DocumentsFile(
      this,
      request,
      options,
    ));
  }

  /**
   * Bulk delete documents
   *
   * @remarks
   * Bulk delete documents by IDs or container tags
   */
  async deleteV3DocumentsBulk(
    request: operations.DeleteV3DocumentsBulkRequest,
    options?: RequestOptions,
  ): Promise<operations.DeleteV3DocumentsBulkResponse> {
    return unwrapAsync(ingestDeleteV3DocumentsBulk(
      this,
      request,
      options,
    ));
  }

  /**
   * Ingest or update conversation
   *
   * @remarks
   * Ingest or update a conversation
   */
  async postV4Conversations(
    request: operations.PostV4ConversationsRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(ingestPostV4Conversations(
      this,
      request,
      options,
    ));
  }
}
