/*
 * Generated by scripts/surface/generate.ts from fern/openapi.json. DO NOT EDIT.
 */

import { memoriesForgetMatching } from "../funcs/memories-forget-matching.js";
import { memoriesForget } from "../funcs/memories-forget.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import { DeleteNsByNamespaceMemoriesSemanticRequest, DeleteNsByNamespaceMemoriesSemanticResponse } from "../models/operations/delete-ns-by-namespace-memories-semantic.js";
import { DeleteNsByNamespaceMemoriesRequest, DeleteNsByNamespaceMemoriesResponse } from "../models/operations/delete-ns-by-namespace-memories.js";
import { unwrapAsync } from "../types/fp.js";

export class Memories extends ClientSDK {
  /**
   * Remove exact memories from normal recall while preserving their audit history. Each ID is handled independently and any missing or ineligible memory is reported without rolling back successful changes.
   */
  async forget(
    request: DeleteNsByNamespaceMemoriesRequest,
    options?: RequestOptions,
  ): Promise<DeleteNsByNamespaceMemoriesResponse> {
    return unwrapAsync(memoriesForget(
      this,
      request,
      options,
    ));
  }

  /**
   * Describe what should be forgotten in natural language, then preview or apply the matching set. Use dry-run results with the exact-ID endpoint when you need a reviewable, drift-free workflow.
   */
  async forgetMatching(
    request: DeleteNsByNamespaceMemoriesSemanticRequest,
    options?: RequestOptions,
  ): Promise<DeleteNsByNamespaceMemoriesSemanticResponse> {
    return unwrapAsync(memoriesForgetMatching(
      this,
      request,
      options,
    ));
  }
}
