/*
 * Generated by scripts/surface/generate.ts from fern/openapi.json. DO NOT EDIT.
 */

import { organizationGet } from "../funcs/organization-get.js";
import { organizationUpdate } from "../funcs/organization-update.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import { GetOrganizationResponse } from "../models/operations/get-organization.js";
import { PatchOrganizationRequest, PatchOrganizationResponse } from "../models/operations/patch-organization.js";
import { unwrapAsync } from "../types/fp.js";

export class Organization extends ClientSDK {
  /**
   * Read the shared background that guides memory formation across the organization, together with the number of active namespaces.
   */
  async get(
    options?: RequestOptions,
  ): Promise<GetOrganizationResponse> {
    return unwrapAsync(organizationGet(
      this,
      options,
    ));
  }

  /**
   * Give Supermemory organization-wide background that improves how content is interpreted across every namespace. Send null to remove the existing context.
   */
  async update(
    request: PatchOrganizationRequest,
    options?: RequestOptions,
  ): Promise<PatchOrganizationResponse> {
    return unwrapAsync(organizationUpdate(
      this,
      request,
      options,
    ));
  }
}
