/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 976de6f449fe
 */

import { organizationGet } from "../funcs/organization-get.js";
import { organizationUpdate } from "../funcs/organization-update.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Organization extends ClientSDK {
  /**
   * Get organization settings
   *
   * @remarks
   * Read the shared background that guides memory formation across the organization, together with the number of active namespaces.
   */
  async get(
    options?: RequestOptions,
  ): Promise<operations.GetOrganizationResponse> {
    return unwrapAsync(organizationGet(
      this,
      options,
    ));
  }

  /**
   * Update organization settings
   *
   * @remarks
   * Give Supermemory organization-wide background that improves how content is interpreted across every namespace. Send null to remove the existing context.
   */
  async update(
    request: operations.PatchOrganizationRequest,
    options?: RequestOptions,
  ): Promise<operations.PatchOrganizationResponse> {
    return unwrapAsync(organizationUpdate(
      this,
      request,
      options,
    ));
  }
}
