/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9e030d2bcc0b
 */

import { profilesBuckets } from "../funcs/profiles-buckets.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Profiles extends ClientSDK {
  /**
   * Get profile buckets
   *
   * @remarks
   * Returns the effective profile bucket definitions for a given container tag — org-level buckets merged with any container-tag-level additions.
   */
  async buckets(
    request: operations.PostV4ProfileBucketsRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV4ProfileBucketsResponse> {
    return unwrapAsync(profilesBuckets(
      this,
      request,
      options,
    ));
  }
}
