/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3bf928ecff8f
 */

import { recallSearchSearch } from "../funcs/recall-search-search.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class RecallSearch extends ClientSDK {
  /**
   * Search memory entries
   *
   * @remarks
   * Search memory entries - Low latency for conversational
   */
  async search(
    request: operations.PostV4SearchRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV4SearchResponse> {
    return unwrapAsync(recallSearchSearch(
      this,
      request,
      options,
    ));
  }
}
