/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 47805ae255dd
 */

import { add } from "../funcs/add.js";
import { profile } from "../funcs/profile.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { Connections } from "./connections.js";
import { ContainerTags } from "./container-tags.js";
import { Conversations } from "./conversations.js";
import { Documents } from "./documents.js";
import { Memories } from "./memories.js";
import { Profiles } from "./profiles.js";
import { RecallSearch } from "./recall-search.js";
import { Settings } from "./settings.js";

export class Supermemory extends ClientSDK {
  private _documents?: Documents;
  get documents(): Documents {
    return (this._documents ??= new Documents(this._options));
  }

  private _settings?: Settings;
  get settings(): Settings {
    return (this._settings ??= new Settings(this._options));
  }

  private _containerTags?: ContainerTags;
  get containerTags(): ContainerTags {
    return (this._containerTags ??= new ContainerTags(this._options));
  }

  private _memories?: Memories;
  get memories(): Memories {
    return (this._memories ??= new Memories(this._options));
  }

  private _profiles?: Profiles;
  get profiles(): Profiles {
    return (this._profiles ??= new Profiles(this._options));
  }

  private _recallSearch?: RecallSearch;
  get recallSearch(): RecallSearch {
    return (this._recallSearch ??= new RecallSearch(this._options));
  }

  private _conversations?: Conversations;
  get conversations(): Conversations {
    return (this._conversations ??= new Conversations(this._options));
  }

  private _connections?: Connections;
  get connections(): Connections {
    return (this._connections ??= new Connections(this._options));
  }

  /**
   * Add document
   *
   * @remarks
   * Add a document with any content type (text, url, file, etc.) and metadata
   */
  async add(
    request: operations.PostV3DocumentsRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV3DocumentsResponse> {
    return unwrapAsync(add(
      this,
      request,
      options,
    ));
  }

  /**
   * Get user profile
   *
   * @remarks
   * Get user profile with optional search results
   */
  async profile(
    request: operations.PostV4ProfileRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV4ProfileResponse> {
    return unwrapAsync(profile(
      this,
      request,
      options,
    ));
  }
}
