/*
 * Generated by scripts/surface/generate.ts from fern/openapi.json. DO NOT EDIT.
 */

import { add } from "../funcs/add.js";
import { list } from "../funcs/list.js";
import { profile } from "../funcs/profile.js";
import { search } from "../funcs/search.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import { PostNsByNamespaceDocumentRequest, PostNsByNamespaceDocumentResponse } from "../models/operations/post-ns-by-namespace-document.js";
import { PostNsByNamespaceListByTypeRequest, PostNsByNamespaceListByTypeResponse } from "../models/operations/post-ns-by-namespace-list-by-type.js";
import { PostNsByNamespaceProfileRequest, PostNsByNamespaceProfileResponse } from "../models/operations/post-ns-by-namespace-profile.js";
import { PostNsByNamespaceSearchRequest, PostNsByNamespaceSearchResponse } from "../models/operations/post-ns-by-namespace-search.js";
import { unwrapAsync } from "../types/fp.js";
import { Connectors } from "./connectors.js";
import { Documents } from "./documents.js";
import { Memories } from "./memories.js";
import { Namespaces } from "./namespaces.js";
import { Organization } from "./organization.js";
import { Profiles } from "./profiles.js";

export class Supermemory extends ClientSDK {
  private _documents?: Documents;
  get documents(): Documents {
    return (this._documents ??= new Documents(this._options));
  }

  private _profiles?: Profiles;
  get profiles(): Profiles {
    return (this._profiles ??= new Profiles(this._options));
  }

  private _memories?: Memories;
  get memories(): Memories {
    return (this._memories ??= new Memories(this._options));
  }

  private _connectors?: Connectors;
  get connectors(): Connectors {
    return (this._connectors ??= new Connectors(this._options));
  }

  private _namespaces?: Namespaces;
  get namespaces(): Namespaces {
    return (this._namespaces ??= new Namespaces(this._options));
  }

  private _organization?: Organization;
  get organization(): Organization {
    return (this._organization ??= new Organization(this._options));
  }

  /**
   * Turn text or a supported URL into searchable, evolving memory. Supply a new ID to create a document, or reuse an existing ID to append new information while preserving its history.
   */
  async add(
    request: PostNsByNamespaceDocumentRequest,
    options?: RequestOptions,
  ): Promise<PostNsByNamespaceDocumentResponse> {
    return unwrapAsync(add(
      this,
      request,
      options,
    ));
  }

  /**
   * Recall the most relevant learned context and source passages from a namespace. Hybrid search combines memories with document chunks by default, with optional query rewriting, reranking, and supporting context attachments.
   */
  async search(
    request: PostNsByNamespaceSearchRequest,
    options?: RequestOptions,
  ): Promise<PostNsByNamespaceSearchResponse> {
    return unwrapAsync(search(
      this,
      request,
      options,
    ));
  }

  /**
   * Read a continuously maintained understanding of the subject represented by this namespace. Stable facts, evolving context, and selected custom buckets are returned together without requiring a search query.
   */
  async profile(
    request: PostNsByNamespaceProfileRequest,
    options?: RequestOptions,
  ): Promise<PostNsByNamespaceProfileResponse> {
    return unwrapAsync(profile(
      this,
      request,
      options,
    ));
  }

  /**
   * Browse documents, source chunks, or learned memories through one predictable paginated contract. Choose the collection in the path; the other collection arrays remain empty for a stable response shape.
   */
  async list(
    request: PostNsByNamespaceListByTypeRequest,
    options?: RequestOptions,
  ): Promise<PostNsByNamespaceListByTypeResponse> {
    return unwrapAsync(list(
      this,
      request,
      options,
    ));
  }
}
