/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Connections } from "./connections.js";
import { ContainerTags } from "./container-tags.js";
import { ContentManagement } from "./content-management.js";
import { Documents } from "./documents.js";
import { Ingest } from "./ingest.js";
import { Profiles } from "./profiles.js";
import { RecallSearch } from "./recall-search.js";
import { Settings } from "./settings.js";

export class Supermemory extends ClientSDK {
  private _ingest?: Ingest;
  get ingest(): Ingest {
    return (this._ingest ??= new Ingest(this._options));
  }

  private _documents?: Documents;
  get documents(): Documents {
    return (this._documents ??= new Documents(this._options));
  }

  private _settings?: Settings;
  get settings(): Settings {
    return (this._settings ??= new Settings(this._options));
  }

  private _containerTags?: ContainerTags;
  get containerTags(): ContainerTags {
    return (this._containerTags ??= new ContainerTags(this._options));
  }

  private _contentManagement?: ContentManagement;
  get contentManagement(): ContentManagement {
    return (this._contentManagement ??= new ContentManagement(this._options));
  }

  private _profiles?: Profiles;
  get profiles(): Profiles {
    return (this._profiles ??= new Profiles(this._options));
  }

  private _recallSearch?: RecallSearch;
  get recallSearch(): RecallSearch {
    return (this._recallSearch ??= new RecallSearch(this._options));
  }

  private _connections?: Connections;
  get connections(): Connections {
    return (this._connections ??= new Connections(this._options));
  }
}
