/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 447950dfa4e7
 */

import { searchExecute } from "../funcs/search-execute.js";
import { searchMemories } from "../funcs/search-memories.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Search extends ClientSDK {
  /**
   * Search documents
   *
   * @remarks
   * Search memories with advanced filtering
   */
  async execute(
    request: operations.PostV3SearchRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV3SearchResponse> {
    return unwrapAsync(searchExecute(
      this,
      request,
      options,
    ));
  }

  /**
   * Search memory entries
   *
   * @remarks
   * Search memory entries - Low latency for conversational
   */
  async memories(
    request: operations.PostV4SearchRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV4SearchResponse> {
    return unwrapAsync(searchMemories(
      this,
      request,
      options,
    ));
  }
}
