/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { settingsGetV3Settings } from "../funcs/settings-get-v3-settings.js";
import { settingsPatchV3Settings } from "../funcs/settings-patch-v3-settings.js";
import { settingsPostV3SettingsReset } from "../funcs/settings-post-v3-settings-reset.js";
import { settingsPostV3SettingsSuggestBuckets } from "../funcs/settings-post-v3-settings-suggest-buckets.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Settings extends ClientSDK {
  /**
   * Get settings
   *
   * @remarks
   * Get settings for an organization
   */
  async getV3Settings(
    options?: RequestOptions,
  ): Promise<operations.GetV3SettingsResponse> {
    return unwrapAsync(settingsGetV3Settings(
      this,
      options,
    ));
  }

  /**
   * Update settings
   *
   * @remarks
   * Update settings for an organization
   */
  async patchV3Settings(
    request: operations.PatchV3SettingsRequest,
    options?: RequestOptions,
  ): Promise<operations.PatchV3SettingsResponse> {
    return unwrapAsync(settingsPatchV3Settings(
      this,
      request,
      options,
    ));
  }

  /**
   * Reset organization data
   *
   * @remarks
   * Reset organization content: removes documents, memories, spaces (except default project), connections, and org settings. Preserves the org, members, and billing.
   */
  async postV3SettingsReset(
    request: operations.PostV3SettingsResetRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV3SettingsResetResponse> {
    return unwrapAsync(settingsPostV3SettingsReset(
      this,
      request,
      options,
    ));
  }

  /**
   * Suggest profile buckets
   *
   * @remarks
   * Suggest profile bucket definitions based on the organization context prompt. Returns 3–6 bucket suggestions tailored to the use-case described in the prompt.
   */
  async postV3SettingsSuggestBuckets(
    options?: RequestOptions,
  ): Promise<operations.PostV3SettingsSuggestBucketsResponse> {
    return unwrapAsync(settingsPostV3SettingsSuggestBuckets(
      this,
      options,
    ));
  }
}
