/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 46c8c35c56f2
 */

import { settingsGet } from "../funcs/settings-get.js";
import { settingsResetOrganizationData } from "../funcs/settings-reset-organization-data.js";
import { settingsSuggestBuckets } from "../funcs/settings-suggest-buckets.js";
import { settingsUpdate } from "../funcs/settings-update.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Settings extends ClientSDK {
  /**
   * Get settings
   *
   * @remarks
   * Get settings for an organization
   */
  async get(
    options?: RequestOptions,
  ): Promise<operations.GetV3SettingsResponse> {
    return unwrapAsync(settingsGet(
      this,
      options,
    ));
  }

  /**
   * Update settings
   *
   * @remarks
   * Update settings for an organization
   */
  async update(
    request: operations.PatchV3SettingsRequest,
    options?: RequestOptions,
  ): Promise<operations.PatchV3SettingsResponse> {
    return unwrapAsync(settingsUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Reset organization data
   *
   * @remarks
   * Reset organization content: removes documents, memories, spaces (except default project), connections, and org settings. Preserves the org, members, and billing.
   */
  async resetOrganizationData(
    request: operations.PostV3SettingsResetRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV3SettingsResetResponse> {
    return unwrapAsync(settingsResetOrganizationData(
      this,
      request,
      options,
    ));
  }

  /**
   * Suggest profile buckets
   *
   * @remarks
   * Suggest profile bucket definitions based on the organization context prompt. Returns 3–6 bucket suggestions tailored to the use-case described in the prompt.
   */
  async suggestBuckets(
    options?: RequestOptions,
  ): Promise<operations.PostV3SettingsSuggestBucketsResponse> {
    return unwrapAsync(settingsSuggestBuckets(
      this,
      options,
    ));
  }
}
