workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    supermemory API:
        inputs:
            - location: https://api.supermemory.ai/v4/openapi
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
            - location: .speakeasy/stainless-parity-overlay.yaml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/supermemory-hnj/supermemory/supermemory-api
targets:
    supermemory:
        target: typescript
        source: supermemory API
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/supermemory-hnj/supermemory/supermemory-api-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
