/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: cef15cfc98ca
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import * as discriminatedUnionTypes from "../../types/discriminated-union.js";
import { discriminatedUnion } from "../../types/discriminated-union.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type DeleteNsByNamespaceRequestBody = {
  /**
   * Destination namespace that should receive this namespace's content before deletion. Omit to permanently delete the content.
   */
  moveTo?: string | undefined;
};

export type DeleteNsByNamespaceRequest = {
  /**
   * Namespace identifier. This can be an ID for your user, a project ID, or any other identifier you wish to use to scope documents and memories.
   */
  namespace: string;
  body?: DeleteNsByNamespaceRequestBody | undefined;
};

/**
 * Namespace move queued
 */
export type DeleteNsByNamespaceResponseBodyQueued = {
  /**
   * Confirms the namespace move was accepted
   */
  success: true;
  /**
   * The move continues asynchronously after this response
   */
  status: "queued";
  /**
   * Identifier used to trace the asynchronous move operation
   */
  operationId: string;
  /**
   * Source namespace being removed
   */
  namespace: string;
  /**
   * Destination namespace receiving the content
   */
  moveTo: string;
};

export type Queued = {
  /**
   * Confirms the namespace move was accepted
   */
  success: true;
  /**
   * The move continues asynchronously after this response
   */
  status: "queued";
  /**
   * Identifier used to trace the asynchronous move operation
   */
  operationId: string;
  /**
   * Source namespace being removed
   */
  namespace: string;
  /**
   * Destination namespace receiving the content
   */
  moveTo: string;
};

export type Deleted = {
  /**
   * Confirms the namespace was deleted
   */
  success: true;
  /**
   * The namespace and its content are gone
   */
  status: "deleted";
  /**
   * Deleted namespace identifier
   */
  namespace: string;
  /**
   * Number of documents permanently removed
   */
  deletedDocumentsCount: number;
  /**
   * Number of memories permanently removed
   */
  deletedMemoriesCount: number;
};

/**
 * Namespace permanently deleted (status "deleted"). A move answers 202 with status "queued".
 */
export type DeleteNsByNamespaceResponseBody =
  | Deleted
  | Queued
  | discriminatedUnionTypes.Unknown<"status">;

export type DeleteNsByNamespaceResponse =
  | DeleteNsByNamespaceResponseBodyQueued
  | Deleted
  | Queued
  | discriminatedUnionTypes.Unknown<"status">;

/** @internal */
export type DeleteNsByNamespaceRequestBody$Outbound = {
  moveTo?: string | undefined;
};

/** @internal */
export const DeleteNsByNamespaceRequestBody$outboundSchema: z.ZodMiniType<
  DeleteNsByNamespaceRequestBody$Outbound,
  DeleteNsByNamespaceRequestBody
> = z.object({
  moveTo: z.optional(z.string()),
});

export function deleteNsByNamespaceRequestBodyToJSON(
  deleteNsByNamespaceRequestBody: DeleteNsByNamespaceRequestBody,
): string {
  return JSON.stringify(
    DeleteNsByNamespaceRequestBody$outboundSchema.parse(
      deleteNsByNamespaceRequestBody,
    ),
  );
}

/** @internal */
export type DeleteNsByNamespaceRequest$Outbound = {
  namespace: string;
  body?: DeleteNsByNamespaceRequestBody$Outbound | undefined;
};

/** @internal */
export const DeleteNsByNamespaceRequest$outboundSchema: z.ZodMiniType<
  DeleteNsByNamespaceRequest$Outbound,
  DeleteNsByNamespaceRequest
> = z.object({
  namespace: z.string(),
  body: z.optional(z.lazy(() => DeleteNsByNamespaceRequestBody$outboundSchema)),
});

export function deleteNsByNamespaceRequestToJSON(
  deleteNsByNamespaceRequest: DeleteNsByNamespaceRequest,
): string {
  return JSON.stringify(
    DeleteNsByNamespaceRequest$outboundSchema.parse(deleteNsByNamespaceRequest),
  );
}

/** @internal */
export const DeleteNsByNamespaceResponseBodyQueued$inboundSchema: z.ZodMiniType<
  DeleteNsByNamespaceResponseBodyQueued,
  unknown
> = z.object({
  success: types.literal(true),
  status: types.literal("queued"),
  operationId: types.string(),
  namespace: types.string(),
  moveTo: types.string(),
});

export function deleteNsByNamespaceResponseBodyQueuedFromJSON(
  jsonString: string,
): SafeParseResult<DeleteNsByNamespaceResponseBodyQueued, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      DeleteNsByNamespaceResponseBodyQueued$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteNsByNamespaceResponseBodyQueued' from JSON`,
  );
}

/** @internal */
export const Queued$inboundSchema: z.ZodMiniType<Queued, unknown> = z.object({
  success: types.literal(true),
  status: types.literal("queued"),
  operationId: types.string(),
  namespace: types.string(),
  moveTo: types.string(),
});

export function queuedFromJSON(
  jsonString: string,
): SafeParseResult<Queued, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Queued$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Queued' from JSON`,
  );
}

/** @internal */
export const Deleted$inboundSchema: z.ZodMiniType<Deleted, unknown> = z.object({
  success: types.literal(true),
  status: types.literal("deleted"),
  namespace: types.string(),
  deletedDocumentsCount: types.number(),
  deletedMemoriesCount: types.number(),
});

export function deletedFromJSON(
  jsonString: string,
): SafeParseResult<Deleted, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Deleted$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Deleted' from JSON`,
  );
}

/** @internal */
export const DeleteNsByNamespaceResponseBody$inboundSchema: z.ZodMiniType<
  DeleteNsByNamespaceResponseBody,
  unknown
> = discriminatedUnion("status", {
  deleted: z.lazy(() => Deleted$inboundSchema),
  queued: z.lazy(() => Queued$inboundSchema),
});

export function deleteNsByNamespaceResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<DeleteNsByNamespaceResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteNsByNamespaceResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteNsByNamespaceResponseBody' from JSON`,
  );
}

/** @internal */
export const DeleteNsByNamespaceResponse$inboundSchema: z.ZodMiniType<
  DeleteNsByNamespaceResponse,
  unknown
> = smartUnion([
  z.lazy(() => DeleteNsByNamespaceResponseBodyQueued$inboundSchema),
  discriminatedUnion("status", {
    deleted: z.lazy(() => Deleted$inboundSchema),
    queued: z.lazy(() => Queued$inboundSchema),
  }),
]);

export function deleteNsByNamespaceResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteNsByNamespaceResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteNsByNamespaceResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteNsByNamespaceResponse' from JSON`,
  );
}
