/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export const DeleteV3ConnectionsByProviderProvider = {
  Notion: "notion",
  GoogleDrive: "google-drive",
  Onedrive: "onedrive",
  Gmail: "gmail",
  Github: "github",
  WebCrawler: "web-crawler",
  S3: "s3",
  Granola: "granola",
} as const;
export type DeleteV3ConnectionsByProviderProvider = ClosedEnum<
  typeof DeleteV3ConnectionsByProviderProvider
>;

export type DeleteV3ConnectionsByProviderRequestBody = {
  /**
   * Optional comma-separated list of container tags to filter connections by
   */
  containerTags: Array<string>;
};

export type DeleteV3ConnectionsByProviderRequest = {
  provider: DeleteV3ConnectionsByProviderProvider;
  body: DeleteV3ConnectionsByProviderRequestBody;
};

/**
 * Connection deleted successfully
 */
export type DeleteV3ConnectionsByProviderResponse = {
  id: string;
  provider: string;
};

/** @internal */
export const DeleteV3ConnectionsByProviderProvider$outboundSchema:
  z.ZodMiniEnum<typeof DeleteV3ConnectionsByProviderProvider> = z.enum(
    DeleteV3ConnectionsByProviderProvider,
  );

/** @internal */
export type DeleteV3ConnectionsByProviderRequestBody$Outbound = {
  containerTags: Array<string>;
};

/** @internal */
export const DeleteV3ConnectionsByProviderRequestBody$outboundSchema:
  z.ZodMiniType<
    DeleteV3ConnectionsByProviderRequestBody$Outbound,
    DeleteV3ConnectionsByProviderRequestBody
  > = z.object({
    containerTags: z.array(z.string()),
  });

export function deleteV3ConnectionsByProviderRequestBodyToJSON(
  deleteV3ConnectionsByProviderRequestBody:
    DeleteV3ConnectionsByProviderRequestBody,
): string {
  return JSON.stringify(
    DeleteV3ConnectionsByProviderRequestBody$outboundSchema.parse(
      deleteV3ConnectionsByProviderRequestBody,
    ),
  );
}

/** @internal */
export type DeleteV3ConnectionsByProviderRequest$Outbound = {
  provider: string;
  body: DeleteV3ConnectionsByProviderRequestBody$Outbound;
};

/** @internal */
export const DeleteV3ConnectionsByProviderRequest$outboundSchema: z.ZodMiniType<
  DeleteV3ConnectionsByProviderRequest$Outbound,
  DeleteV3ConnectionsByProviderRequest
> = z.object({
  provider: DeleteV3ConnectionsByProviderProvider$outboundSchema,
  body: z.lazy(() => DeleteV3ConnectionsByProviderRequestBody$outboundSchema),
});

export function deleteV3ConnectionsByProviderRequestToJSON(
  deleteV3ConnectionsByProviderRequest: DeleteV3ConnectionsByProviderRequest,
): string {
  return JSON.stringify(
    DeleteV3ConnectionsByProviderRequest$outboundSchema.parse(
      deleteV3ConnectionsByProviderRequest,
    ),
  );
}

/** @internal */
export const DeleteV3ConnectionsByProviderResponse$inboundSchema: z.ZodMiniType<
  DeleteV3ConnectionsByProviderResponse,
  unknown
> = z.object({
  id: types.string(),
  provider: types.string(),
});

export function deleteV3ConnectionsByProviderResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteV3ConnectionsByProviderResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      DeleteV3ConnectionsByProviderResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteV3ConnectionsByProviderResponse' from JSON`,
  );
}
