/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0199fd2734d8
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type DeleteNsByNamespaceProfileBucketsRequestBody = {
  /**
   * Namespace-owned bucket names to delete. Organization-level buckets are protected and cannot be removed here.
   */
  buckets: Array<string>;
};

export type DeleteNsByNamespaceProfileBucketsRequest = {
  /**
   * The isolated namespace to search. This can be an ID for your user, a project ID, or any other identifier you wish to use to scope memories.
   */
  namespace: string;
  body: DeleteNsByNamespaceProfileBucketsRequestBody;
};

/**
 * Updated effective namespace profile bucket definitions
 */
export type DeleteNsByNamespaceProfileBucketsResponse = {
  /**
   * Effective bucket definitions keyed by name. Includes organization buckets and namespace-owned additions.
   */
  buckets: { [k: string]: string };
};

/** @internal */
export type DeleteNsByNamespaceProfileBucketsRequestBody$Outbound = {
  buckets: Array<string>;
};

/** @internal */
export const DeleteNsByNamespaceProfileBucketsRequestBody$outboundSchema:
  z.ZodMiniType<
    DeleteNsByNamespaceProfileBucketsRequestBody$Outbound,
    DeleteNsByNamespaceProfileBucketsRequestBody
  > = z.object({
    buckets: z.array(z.string()),
  });

export function deleteNsByNamespaceProfileBucketsRequestBodyToJSON(
  deleteNsByNamespaceProfileBucketsRequestBody:
    DeleteNsByNamespaceProfileBucketsRequestBody,
): string {
  return JSON.stringify(
    DeleteNsByNamespaceProfileBucketsRequestBody$outboundSchema.parse(
      deleteNsByNamespaceProfileBucketsRequestBody,
    ),
  );
}

/** @internal */
export type DeleteNsByNamespaceProfileBucketsRequest$Outbound = {
  namespace: string;
  body: DeleteNsByNamespaceProfileBucketsRequestBody$Outbound;
};

/** @internal */
export const DeleteNsByNamespaceProfileBucketsRequest$outboundSchema:
  z.ZodMiniType<
    DeleteNsByNamespaceProfileBucketsRequest$Outbound,
    DeleteNsByNamespaceProfileBucketsRequest
  > = z.object({
    namespace: z.string(),
    body: z.lazy(() =>
      DeleteNsByNamespaceProfileBucketsRequestBody$outboundSchema
    ),
  });

export function deleteNsByNamespaceProfileBucketsRequestToJSON(
  deleteNsByNamespaceProfileBucketsRequest:
    DeleteNsByNamespaceProfileBucketsRequest,
): string {
  return JSON.stringify(
    DeleteNsByNamespaceProfileBucketsRequest$outboundSchema.parse(
      deleteNsByNamespaceProfileBucketsRequest,
    ),
  );
}

/** @internal */
export const DeleteNsByNamespaceProfileBucketsResponse$inboundSchema:
  z.ZodMiniType<DeleteNsByNamespaceProfileBucketsResponse, unknown> = z.object({
    buckets: z.record(z.string(), types.string()),
  });

export function deleteNsByNamespaceProfileBucketsResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  DeleteNsByNamespaceProfileBucketsResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DeleteNsByNamespaceProfileBucketsResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'DeleteNsByNamespaceProfileBucketsResponse' from JSON`,
  );
}
