/*
 * Generated by scripts/surface/generate.ts from fern/openapi.json. DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as types from "../../types/primitives.js";

export const DeleteNsByNamespaceConnectorsByIdDeleteDocuments = {
  True: "true",
  False: "false",
} as const;
export type DeleteNsByNamespaceConnectorsByIdDeleteDocuments = ClosedEnum<typeof DeleteNsByNamespaceConnectorsByIdDeleteDocuments>;

/** @internal */
export const DeleteNsByNamespaceConnectorsByIdDeleteDocuments$outboundSchema: z.ZodMiniEnum<typeof DeleteNsByNamespaceConnectorsByIdDeleteDocuments> = z.enum(DeleteNsByNamespaceConnectorsByIdDeleteDocuments);

export type DeleteNsByNamespaceConnectorsByIdRequest = {
  namespace: string;
  id: string;
  deleteDocuments?: DeleteNsByNamespaceConnectorsByIdDeleteDocuments | undefined;
};

/** @internal */
export type DeleteNsByNamespaceConnectorsByIdRequest$Outbound = {
  namespace: string;
  id: string;
  deleteDocuments?: string | undefined;
};

/** @internal */
export const DeleteNsByNamespaceConnectorsByIdRequest$outboundSchema: z.ZodMiniType<DeleteNsByNamespaceConnectorsByIdRequest$Outbound, DeleteNsByNamespaceConnectorsByIdRequest> = z.object({
  namespace: z.string(),
  id: z.string(),
  deleteDocuments: z._default(DeleteNsByNamespaceConnectorsByIdDeleteDocuments$outboundSchema, "true"),
});

export function deleteNsByNamespaceConnectorsByIdRequestToJSON(
  deleteNsByNamespaceConnectorsByIdRequest: DeleteNsByNamespaceConnectorsByIdRequest,
): string {
  return JSON.stringify(DeleteNsByNamespaceConnectorsByIdRequest$outboundSchema.parse(deleteNsByNamespaceConnectorsByIdRequest));
}

export type DeleteNsByNamespaceConnectorsByIdResponse = {
  id: string;
  deleted: true;
};

/** @internal */
export const DeleteNsByNamespaceConnectorsByIdResponse$inboundSchema: z.ZodMiniType<DeleteNsByNamespaceConnectorsByIdResponse, unknown> = z.object({
  id: types.string(),
  deleted: types.literal(true),
});

export function deleteNsByNamespaceConnectorsByIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteNsByNamespaceConnectorsByIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteNsByNamespaceConnectorsByIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteNsByNamespaceConnectorsByIdResponse' from JSON`,
  );
}
