/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a356848dc711
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Also delete documents this connector imported. Defaults to true.
 */
export const DeleteDocuments = {
  True: "true",
  False: "false",
} as const;
/**
 * Also delete documents this connector imported. Defaults to true.
 */
export type DeleteDocuments = ClosedEnum<typeof DeleteDocuments>;

export type DeleteNsByNamespaceConnectorsByIdRequest = {
  /**
   * Namespace identifier. This can be an ID for your user, a project ID, or any other identifier you wish to use to scope documents and memories.
   */
  namespace: string;
  /**
   * Connector identifier returned when the connector was created
   */
  id: string;
  /**
   * Also delete documents this connector imported. Defaults to true.
   */
  deleteDocuments?: DeleteDocuments | undefined;
};

/**
 * Connector deleted
 */
export type DeleteNsByNamespaceConnectorsByIdResponse = {
  id: string;
  deleted: true;
};

/** @internal */
export const DeleteDocuments$outboundSchema: z.ZodMiniEnum<
  typeof DeleteDocuments
> = z.enum(DeleteDocuments);

/** @internal */
export type DeleteNsByNamespaceConnectorsByIdRequest$Outbound = {
  namespace: string;
  id: string;
  deleteDocuments: string;
};

/** @internal */
export const DeleteNsByNamespaceConnectorsByIdRequest$outboundSchema:
  z.ZodMiniType<
    DeleteNsByNamespaceConnectorsByIdRequest$Outbound,
    DeleteNsByNamespaceConnectorsByIdRequest
  > = z.object({
    namespace: z.string(),
    id: z.string(),
    deleteDocuments: z._default(DeleteDocuments$outboundSchema, "true"),
  });

export function deleteNsByNamespaceConnectorsByIdRequestToJSON(
  deleteNsByNamespaceConnectorsByIdRequest:
    DeleteNsByNamespaceConnectorsByIdRequest,
): string {
  return JSON.stringify(
    DeleteNsByNamespaceConnectorsByIdRequest$outboundSchema.parse(
      deleteNsByNamespaceConnectorsByIdRequest,
    ),
  );
}

/** @internal */
export const DeleteNsByNamespaceConnectorsByIdResponse$inboundSchema:
  z.ZodMiniType<DeleteNsByNamespaceConnectorsByIdResponse, unknown> = z.object({
    id: types.string(),
    deleted: types.literal(true),
  });

export function deleteNsByNamespaceConnectorsByIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  DeleteNsByNamespaceConnectorsByIdResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DeleteNsByNamespaceConnectorsByIdResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'DeleteNsByNamespaceConnectorsByIdResponse' from JSON`,
  );
}
