/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteV3DocumentsByIdRequest = {
  id: string;
};

/** @internal */
export type DeleteV3DocumentsByIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteV3DocumentsByIdRequest$outboundSchema: z.ZodMiniType<
  DeleteV3DocumentsByIdRequest$Outbound,
  DeleteV3DocumentsByIdRequest
> = z.object({
  id: z.string(),
});

export function deleteV3DocumentsByIdRequestToJSON(
  deleteV3DocumentsByIdRequest: DeleteV3DocumentsByIdRequest,
): string {
  return JSON.stringify(
    DeleteV3DocumentsByIdRequest$outboundSchema.parse(
      deleteV3DocumentsByIdRequest,
    ),
  );
}
