/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type DeleteV4MemoriesRequest = {
  /**
   * ID of the memory entry to operate on
   */
  id?: string | undefined;
  /**
   * Exact content match of the memory entry to operate on. Use this when you don't have the ID.
   */
  content?: string | undefined;
  /**
   * Container tag / space identifier. Required to scope the operation.
   */
  containerTag: string;
  /**
   * Optional reason for forgetting this memory
   */
  reason?: string | undefined;
};

/**
 * Response after forgetting a memory
 */
export type DeleteV4MemoriesResponse = {
  /**
   * ID of the memory that was forgotten
   */
  id: string;
  /**
   * Indicates the memory was successfully forgotten
   */
  forgotten: boolean;
};

/** @internal */
export type DeleteV4MemoriesRequest$Outbound = {
  id?: string | undefined;
  content?: string | undefined;
  containerTag: string;
  reason?: string | undefined;
};

/** @internal */
export const DeleteV4MemoriesRequest$outboundSchema: z.ZodMiniType<
  DeleteV4MemoriesRequest$Outbound,
  DeleteV4MemoriesRequest
> = z.object({
  id: z.optional(z.string()),
  content: z.optional(z.string()),
  containerTag: z.string(),
  reason: z.optional(z.string()),
});

export function deleteV4MemoriesRequestToJSON(
  deleteV4MemoriesRequest: DeleteV4MemoriesRequest,
): string {
  return JSON.stringify(
    DeleteV4MemoriesRequest$outboundSchema.parse(deleteV4MemoriesRequest),
  );
}

/** @internal */
export const DeleteV4MemoriesResponse$inboundSchema: z.ZodMiniType<
  DeleteV4MemoriesResponse,
  unknown
> = z.object({
  id: types.string(),
  forgotten: types.boolean(),
});

export function deleteV4MemoriesResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteV4MemoriesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteV4MemoriesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteV4MemoriesResponse' from JSON`,
  );
}
