/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 19ad2d8304d5
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type DeleteV3ContainerTagsByContainerTagRequest = {
  containerTag: string;
};

/**
 * Response after successfully deleting a container tag and all its associated data
 */
export type DeleteV3ContainerTagsByContainerTagResponse = {
  /**
   * Whether the deletion was successful
   */
  success: boolean;
  /**
   * The deleted container tag
   */
  containerTag: string;
  /**
   * Number of documents deleted
   */
  deletedDocumentsCount: number;
  /**
   * Number of memories marked as forgotten
   */
  deletedMemoriesCount: number;
};

/** @internal */
export type DeleteV3ContainerTagsByContainerTagRequest$Outbound = {
  containerTag: string;
};

/** @internal */
export const DeleteV3ContainerTagsByContainerTagRequest$outboundSchema:
  z.ZodMiniType<
    DeleteV3ContainerTagsByContainerTagRequest$Outbound,
    DeleteV3ContainerTagsByContainerTagRequest
  > = z.object({
    containerTag: z.string(),
  });

export function deleteV3ContainerTagsByContainerTagRequestToJSON(
  deleteV3ContainerTagsByContainerTagRequest:
    DeleteV3ContainerTagsByContainerTagRequest,
): string {
  return JSON.stringify(
    DeleteV3ContainerTagsByContainerTagRequest$outboundSchema.parse(
      deleteV3ContainerTagsByContainerTagRequest,
    ),
  );
}

/** @internal */
export const DeleteV3ContainerTagsByContainerTagResponse$inboundSchema:
  z.ZodMiniType<DeleteV3ContainerTagsByContainerTagResponse, unknown> = z
    .object({
      success: types.boolean(),
      containerTag: types.string(),
      deletedDocumentsCount: types.number(),
      deletedMemoriesCount: types.number(),
    });

export function deleteV3ContainerTagsByContainerTagResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  DeleteV3ContainerTagsByContainerTagResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DeleteV3ContainerTagsByContainerTagResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'DeleteV3ContainerTagsByContainerTagResponse' from JSON`,
  );
}
