/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5dc211ded1c6
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Request body for bulk deleting documents by IDs or container tags
 */
export type DeleteV3DocumentsBulkRequest = {
  /**
   * Array of document IDs to delete (max 100 at once)
   */
  ids?: Array<string> | undefined;
  /**
   * Array of container tags - all documents in these containers will be deleted
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  containerTags?: Array<string> | undefined;
  /**
   * Delete documents matching this filepath. Exact match for full paths, prefix match if ending with /
   */
  filepath?: string | undefined;
};

export type ErrorT = {
  id: string;
  error: string;
};

/**
 * Response for bulk document deletion
 */
export type DeleteV3DocumentsBulkResponse = {
  /**
   * Whether the bulk deletion was successful
   */
  success: boolean;
  /**
   * Number of documents successfully deleted
   */
  deletedCount: number;
  /**
   * Array of errors for documents that couldn't be deleted (only applicable when deleting by IDs)
   */
  errors?: Array<ErrorT> | undefined;
  /**
   * Container tags that were processed (only applicable when deleting by container tags)
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  containerTags?: Array<string> | undefined;
};

/** @internal */
export type DeleteV3DocumentsBulkRequest$Outbound = {
  ids?: Array<string> | undefined;
  containerTags?: Array<string> | undefined;
  filepath?: string | undefined;
};

/** @internal */
export const DeleteV3DocumentsBulkRequest$outboundSchema: z.ZodMiniType<
  DeleteV3DocumentsBulkRequest$Outbound,
  DeleteV3DocumentsBulkRequest
> = z.object({
  ids: z.optional(z.array(z.string())),
  containerTags: z.optional(z.array(z.string())),
  filepath: z.optional(z.string()),
});

export function deleteV3DocumentsBulkRequestToJSON(
  deleteV3DocumentsBulkRequest: DeleteV3DocumentsBulkRequest,
): string {
  return JSON.stringify(
    DeleteV3DocumentsBulkRequest$outboundSchema.parse(
      deleteV3DocumentsBulkRequest,
    ),
  );
}

/** @internal */
export const ErrorT$inboundSchema: z.ZodMiniType<ErrorT, unknown> = z.object({
  id: types.string(),
  error: types.string(),
});

export function errorFromJSON(
  jsonString: string,
): SafeParseResult<ErrorT, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorT$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorT' from JSON`,
  );
}

/** @internal */
export const DeleteV3DocumentsBulkResponse$inboundSchema: z.ZodMiniType<
  DeleteV3DocumentsBulkResponse,
  unknown
> = z.object({
  success: types.boolean(),
  deletedCount: types.number(),
  errors: types.optional(z.array(z.lazy(() => ErrorT$inboundSchema))),
  containerTags: types.optional(z.array(types.string())),
});

export function deleteV3DocumentsBulkResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteV3DocumentsBulkResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteV3DocumentsBulkResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteV3DocumentsBulkResponse' from JSON`,
  );
}
