/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0f88b1fa941f
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type DeleteV3ConnectionsByConnectionIdRequest = {
  connectionId: string;
  /**
   * Whether to also delete documents imported by this connection. Defaults to true.
   */
  deleteDocuments?: string | undefined;
};

/**
 * Connection deleted successfully
 */
export type DeleteV3ConnectionsByConnectionIdResponse = {
  id: string;
  provider: string;
};

/** @internal */
export type DeleteV3ConnectionsByConnectionIdRequest$Outbound = {
  connectionId: string;
  deleteDocuments: string;
};

/** @internal */
export const DeleteV3ConnectionsByConnectionIdRequest$outboundSchema:
  z.ZodMiniType<
    DeleteV3ConnectionsByConnectionIdRequest$Outbound,
    DeleteV3ConnectionsByConnectionIdRequest
  > = z.object({
    connectionId: z.string(),
    deleteDocuments: z._default(z.string(), "true"),
  });

export function deleteV3ConnectionsByConnectionIdRequestToJSON(
  deleteV3ConnectionsByConnectionIdRequest:
    DeleteV3ConnectionsByConnectionIdRequest,
): string {
  return JSON.stringify(
    DeleteV3ConnectionsByConnectionIdRequest$outboundSchema.parse(
      deleteV3ConnectionsByConnectionIdRequest,
    ),
  );
}

/** @internal */
export const DeleteV3ConnectionsByConnectionIdResponse$inboundSchema:
  z.ZodMiniType<DeleteV3ConnectionsByConnectionIdResponse, unknown> = z.object({
    id: types.string(),
    provider: types.string(),
  });

export function deleteV3ConnectionsByConnectionIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  DeleteV3ConnectionsByConnectionIdResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DeleteV3ConnectionsByConnectionIdResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'DeleteV3ConnectionsByConnectionIdResponse' from JSON`,
  );
}
