/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f3cbb2efcba1
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { ClosedEnum, OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Only return connectors for this provider
 */
export const GetNsByNamespaceConnectorsQueryParamProvider = {
  Notion: "notion",
  GoogleDrive: "google-drive",
  Onedrive: "onedrive",
  Gmail: "gmail",
  Github: "github",
  WebCrawler: "web-crawler",
  S3: "s3",
  Granola: "granola",
} as const;
/**
 * Only return connectors for this provider
 */
export type GetNsByNamespaceConnectorsQueryParamProvider = ClosedEnum<
  typeof GetNsByNamespaceConnectorsQueryParamProvider
>;

export type GetNsByNamespaceConnectorsRequest = {
  /**
   * Namespace identifier. This can be an ID for your user, a project ID, or any other identifier you wish to use to scope documents and memories.
   */
  namespace: string;
  /**
   * Only return connectors for this provider
   */
  provider?: GetNsByNamespaceConnectorsQueryParamProvider | undefined;
  /**
   * One-based page number
   */
  page?: number | undefined;
  /**
   * Maximum connectors to return per page
   */
  limit?: number | undefined;
};

/**
 * External source
 */
export const GetNsByNamespaceConnectorsConnectorProvider = {
  Notion: "notion",
  GoogleDrive: "google-drive",
  Onedrive: "onedrive",
  Gmail: "gmail",
  Github: "github",
  WebCrawler: "web-crawler",
  S3: "s3",
  Granola: "granola",
} as const;
/**
 * External source
 */
export type GetNsByNamespaceConnectorsConnectorProvider = OpenEnum<
  typeof GetNsByNamespaceConnectorsConnectorProvider
>;

/**
 * pending_authorization until the user finishes the provider login at authUrl; DELETE cancels it. Pending connectors are not listed.
 */
export const GetNsByNamespaceConnectorsStatus = {
  PendingAuthorization: "pending_authorization",
  Active: "active",
} as const;
/**
 * pending_authorization until the user finishes the provider login at authUrl; DELETE cancels it. Pending connectors are not listed.
 */
export type GetNsByNamespaceConnectorsStatus = OpenEnum<
  typeof GetNsByNamespaceConnectorsStatus
>;

export type GetNsByNamespaceConnectorsCapabilities = {
  /**
   * Supports choosing what to sync via the hosted picker
   */
  selectable: boolean;
  /**
   * Receives change notifications instead of only polling
   */
  webhooks: boolean;
};

export type GetNsByNamespaceConnectorsConfig = string | number | boolean;

export type GetNsByNamespaceConnectorsSelection = {
  id: string;
  name: string;
};

export const GetNsByNamespaceConnectorsLastSyncStatus = {
  Running: "running",
  Completed: "completed",
  Failed: "failed",
} as const;
export type GetNsByNamespaceConnectorsLastSyncStatus = OpenEnum<
  typeof GetNsByNamespaceConnectorsLastSyncStatus
>;

export const GetNsByNamespaceConnectorsLastSyncErrorCode = {
  AuthExpired: "auth_expired",
  RateLimited: "rate_limited",
  PlanRequired: "plan_required",
  ProviderUnavailable: "provider_unavailable",
  Internal: "internal",
} as const;
export type GetNsByNamespaceConnectorsLastSyncErrorCode = OpenEnum<
  typeof GetNsByNamespaceConnectorsLastSyncErrorCode
>;

export type GetNsByNamespaceConnectorsLastSync = {
  status: GetNsByNamespaceConnectorsLastSyncStatus;
  errorCode: GetNsByNamespaceConnectorsLastSyncErrorCode | null;
  /**
   * Customer-safe error message
   */
  error: string | null;
  startedAt: Date;
  completedAt: Date | null;
};

export const GetNsByNamespaceConnectorsSyncStatus = {
  Running: "running",
  Completed: "completed",
  Failed: "failed",
} as const;
export type GetNsByNamespaceConnectorsSyncStatus = OpenEnum<
  typeof GetNsByNamespaceConnectorsSyncStatus
>;

export const GetNsByNamespaceConnectorsSyncErrorCode = {
  AuthExpired: "auth_expired",
  RateLimited: "rate_limited",
  PlanRequired: "plan_required",
  ProviderUnavailable: "provider_unavailable",
  Internal: "internal",
} as const;
export type GetNsByNamespaceConnectorsSyncErrorCode = OpenEnum<
  typeof GetNsByNamespaceConnectorsSyncErrorCode
>;

export const GetNsByNamespaceConnectorsTrigger = {
  Event: "event",
  Cron: "cron",
  Manual: "manual",
} as const;
export type GetNsByNamespaceConnectorsTrigger = OpenEnum<
  typeof GetNsByNamespaceConnectorsTrigger
>;

export type GetNsByNamespaceConnectorsFailure = {
  documentId: string;
  title: string | null;
  errorCode: string;
  errorMessage: string;
  failedAt: string;
};

export type GetNsByNamespaceConnectorsSync = {
  status: GetNsByNamespaceConnectorsSyncStatus;
  errorCode: GetNsByNamespaceConnectorsSyncErrorCode | null;
  /**
   * Customer-safe error message
   */
  error: string | null;
  startedAt: Date;
  completedAt: Date | null;
  id: string;
  trigger: GetNsByNamespaceConnectorsTrigger;
  itemsProcessed: number;
  itemsFailed: number;
  /**
   * Failed items, capped. itemsFailed is the true count.
   */
  failures: Array<GetNsByNamespaceConnectorsFailure>;
};

export type GetNsByNamespaceConnectorsPicker = {
  /**
   * Send the user here to choose what syncs. Works once, in any browser.
   */
  url: string;
  expiresAt: Date;
};

export type GetNsByNamespaceConnectorsConnector = {
  id: string;
  /**
   * External source
   */
  provider: GetNsByNamespaceConnectorsConnectorProvider;
  /**
   * pending_authorization until the user finishes the provider login at authUrl; DELETE cancels it. Pending connectors are not listed.
   */
  status: GetNsByNamespaceConnectorsStatus;
  /**
   * Present while pending, when the caller can create connectors in this namespace: where to send the user to authorize
   */
  authUrl?: string | undefined;
  /**
   * Present while pending: when authUrl stops working
   */
  authUrlExpiresAt?: Date | undefined;
  /**
   * Namespace the connector syncs into. Null only for connectors created before namespaces were required.
   */
  namespace: string | null;
  /**
   * Account on the provider side, usually an email
   */
  account: string | null;
  capabilities: GetNsByNamespaceConnectorsCapabilities;
  /**
   * Non-secret setup, such as the S3 bucket, crawler start URL or Notion workspace. Credentials are never returned.
   */
  config: { [k: string]: string | number | boolean } | null;
  /**
   * What syncs, grouped by kind, in the same shape PATCH takes. Null for connectors that sync everything.
   */
  selection: { [k: string]: Array<GetNsByNamespaceConnectorsSelection> } | null;
  documentLimit: number;
  documentCount: number;
  /**
   * Most recent sync run
   */
  lastSync: GetNsByNamespaceConnectorsLastSync | null;
  /**
   * When content last finished syncing
   */
  lastSyncedAt: Date | null;
  createdAt: Date;
  /**
   * Present when attach=syncs
   */
  syncs?: Array<GetNsByNamespaceConnectorsSync> | undefined;
  /**
   * Present when attach=picker. Null for connectors that sync everything.
   */
  picker?: GetNsByNamespaceConnectorsPicker | null | undefined;
};

/**
 * Pagination metadata
 */
export type GetNsByNamespaceConnectorsPagination = {
  currentPage: number;
  limit: number;
  totalItems: number;
  totalPages: number;
};

/**
 * Connectors in this namespace
 */
export type GetNsByNamespaceConnectorsResponse = {
  connectors: Array<GetNsByNamespaceConnectorsConnector>;
  /**
   * Pagination metadata
   */
  pagination: GetNsByNamespaceConnectorsPagination;
};

/** @internal */
export const GetNsByNamespaceConnectorsQueryParamProvider$outboundSchema:
  z.ZodMiniEnum<typeof GetNsByNamespaceConnectorsQueryParamProvider> = z.enum(
    GetNsByNamespaceConnectorsQueryParamProvider,
  );

/** @internal */
export type GetNsByNamespaceConnectorsRequest$Outbound = {
  namespace: string;
  provider?: string | undefined;
  page: number;
  limit: number;
};

/** @internal */
export const GetNsByNamespaceConnectorsRequest$outboundSchema: z.ZodMiniType<
  GetNsByNamespaceConnectorsRequest$Outbound,
  GetNsByNamespaceConnectorsRequest
> = z.object({
  namespace: z.string(),
  provider: z.optional(
    GetNsByNamespaceConnectorsQueryParamProvider$outboundSchema,
  ),
  page: z._default(z.int(), 1),
  limit: z._default(z.int(), 50),
});

export function getNsByNamespaceConnectorsRequestToJSON(
  getNsByNamespaceConnectorsRequest: GetNsByNamespaceConnectorsRequest,
): string {
  return JSON.stringify(
    GetNsByNamespaceConnectorsRequest$outboundSchema.parse(
      getNsByNamespaceConnectorsRequest,
    ),
  );
}

/** @internal */
export const GetNsByNamespaceConnectorsConnectorProvider$inboundSchema:
  z.ZodMiniType<GetNsByNamespaceConnectorsConnectorProvider, unknown> =
    openEnums.inboundSchema(GetNsByNamespaceConnectorsConnectorProvider);

/** @internal */
export const GetNsByNamespaceConnectorsStatus$inboundSchema: z.ZodMiniType<
  GetNsByNamespaceConnectorsStatus,
  unknown
> = openEnums.inboundSchema(GetNsByNamespaceConnectorsStatus);

/** @internal */
export const GetNsByNamespaceConnectorsCapabilities$inboundSchema:
  z.ZodMiniType<GetNsByNamespaceConnectorsCapabilities, unknown> = z.object({
    selectable: types.boolean(),
    webhooks: types.boolean(),
  });

export function getNsByNamespaceConnectorsCapabilitiesFromJSON(
  jsonString: string,
): SafeParseResult<GetNsByNamespaceConnectorsCapabilities, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetNsByNamespaceConnectorsCapabilities$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetNsByNamespaceConnectorsCapabilities' from JSON`,
  );
}

/** @internal */
export const GetNsByNamespaceConnectorsConfig$inboundSchema: z.ZodMiniType<
  GetNsByNamespaceConnectorsConfig,
  unknown
> = smartUnion([types.string(), types.number(), types.boolean()]);

export function getNsByNamespaceConnectorsConfigFromJSON(
  jsonString: string,
): SafeParseResult<GetNsByNamespaceConnectorsConfig, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetNsByNamespaceConnectorsConfig$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetNsByNamespaceConnectorsConfig' from JSON`,
  );
}

/** @internal */
export const GetNsByNamespaceConnectorsSelection$inboundSchema: z.ZodMiniType<
  GetNsByNamespaceConnectorsSelection,
  unknown
> = z.object({
  id: types.string(),
  name: types.string(),
});

export function getNsByNamespaceConnectorsSelectionFromJSON(
  jsonString: string,
): SafeParseResult<GetNsByNamespaceConnectorsSelection, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetNsByNamespaceConnectorsSelection$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetNsByNamespaceConnectorsSelection' from JSON`,
  );
}

/** @internal */
export const GetNsByNamespaceConnectorsLastSyncStatus$inboundSchema:
  z.ZodMiniType<GetNsByNamespaceConnectorsLastSyncStatus, unknown> = openEnums
    .inboundSchema(GetNsByNamespaceConnectorsLastSyncStatus);

/** @internal */
export const GetNsByNamespaceConnectorsLastSyncErrorCode$inboundSchema:
  z.ZodMiniType<GetNsByNamespaceConnectorsLastSyncErrorCode, unknown> =
    openEnums.inboundSchema(GetNsByNamespaceConnectorsLastSyncErrorCode);

/** @internal */
export const GetNsByNamespaceConnectorsLastSync$inboundSchema: z.ZodMiniType<
  GetNsByNamespaceConnectorsLastSync,
  unknown
> = z.object({
  status: GetNsByNamespaceConnectorsLastSyncStatus$inboundSchema,
  errorCode: types.nullable(
    GetNsByNamespaceConnectorsLastSyncErrorCode$inboundSchema,
  ),
  error: types.nullable(types.string()),
  startedAt: types.date(),
  completedAt: types.nullable(types.date()),
});

export function getNsByNamespaceConnectorsLastSyncFromJSON(
  jsonString: string,
): SafeParseResult<GetNsByNamespaceConnectorsLastSync, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetNsByNamespaceConnectorsLastSync$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetNsByNamespaceConnectorsLastSync' from JSON`,
  );
}

/** @internal */
export const GetNsByNamespaceConnectorsSyncStatus$inboundSchema: z.ZodMiniType<
  GetNsByNamespaceConnectorsSyncStatus,
  unknown
> = openEnums.inboundSchema(GetNsByNamespaceConnectorsSyncStatus);

/** @internal */
export const GetNsByNamespaceConnectorsSyncErrorCode$inboundSchema:
  z.ZodMiniType<GetNsByNamespaceConnectorsSyncErrorCode, unknown> = openEnums
    .inboundSchema(GetNsByNamespaceConnectorsSyncErrorCode);

/** @internal */
export const GetNsByNamespaceConnectorsTrigger$inboundSchema: z.ZodMiniType<
  GetNsByNamespaceConnectorsTrigger,
  unknown
> = openEnums.inboundSchema(GetNsByNamespaceConnectorsTrigger);

/** @internal */
export const GetNsByNamespaceConnectorsFailure$inboundSchema: z.ZodMiniType<
  GetNsByNamespaceConnectorsFailure,
  unknown
> = z.object({
  documentId: types.string(),
  title: types.nullable(types.string()),
  errorCode: types.string(),
  errorMessage: types.string(),
  failedAt: types.string(),
});

export function getNsByNamespaceConnectorsFailureFromJSON(
  jsonString: string,
): SafeParseResult<GetNsByNamespaceConnectorsFailure, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetNsByNamespaceConnectorsFailure$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetNsByNamespaceConnectorsFailure' from JSON`,
  );
}

/** @internal */
export const GetNsByNamespaceConnectorsSync$inboundSchema: z.ZodMiniType<
  GetNsByNamespaceConnectorsSync,
  unknown
> = z.object({
  status: GetNsByNamespaceConnectorsSyncStatus$inboundSchema,
  errorCode: types.nullable(
    GetNsByNamespaceConnectorsSyncErrorCode$inboundSchema,
  ),
  error: types.nullable(types.string()),
  startedAt: types.date(),
  completedAt: types.nullable(types.date()),
  id: types.string(),
  trigger: GetNsByNamespaceConnectorsTrigger$inboundSchema,
  itemsProcessed: types.number(),
  itemsFailed: types.number(),
  failures: z.array(
    z.lazy(() => GetNsByNamespaceConnectorsFailure$inboundSchema),
  ),
});

export function getNsByNamespaceConnectorsSyncFromJSON(
  jsonString: string,
): SafeParseResult<GetNsByNamespaceConnectorsSync, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetNsByNamespaceConnectorsSync$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetNsByNamespaceConnectorsSync' from JSON`,
  );
}

/** @internal */
export const GetNsByNamespaceConnectorsPicker$inboundSchema: z.ZodMiniType<
  GetNsByNamespaceConnectorsPicker,
  unknown
> = z.object({
  url: types.string(),
  expiresAt: types.date(),
});

export function getNsByNamespaceConnectorsPickerFromJSON(
  jsonString: string,
): SafeParseResult<GetNsByNamespaceConnectorsPicker, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetNsByNamespaceConnectorsPicker$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetNsByNamespaceConnectorsPicker' from JSON`,
  );
}

/** @internal */
export const GetNsByNamespaceConnectorsConnector$inboundSchema: z.ZodMiniType<
  GetNsByNamespaceConnectorsConnector,
  unknown
> = z.object({
  id: types.string(),
  provider: GetNsByNamespaceConnectorsConnectorProvider$inboundSchema,
  status: GetNsByNamespaceConnectorsStatus$inboundSchema,
  authUrl: types.optional(types.string()),
  authUrlExpiresAt: types.optional(types.date()),
  namespace: types.nullable(types.string()),
  account: types.nullable(types.string()),
  capabilities: z.lazy(() =>
    GetNsByNamespaceConnectorsCapabilities$inboundSchema
  ),
  config: types.nullable(
    z.record(
      z.string(),
      smartUnion([types.string(), types.number(), types.boolean()]),
    ),
  ),
  selection: types.nullable(
    z.record(
      z.string(),
      z.array(z.lazy(() => GetNsByNamespaceConnectorsSelection$inboundSchema)),
    ),
  ),
  documentLimit: types.number(),
  documentCount: types.number(),
  lastSync: types.nullable(
    z.lazy(() => GetNsByNamespaceConnectorsLastSync$inboundSchema),
  ),
  lastSyncedAt: types.nullable(types.date()),
  createdAt: types.date(),
  syncs: types.optional(
    z.array(z.lazy(() => GetNsByNamespaceConnectorsSync$inboundSchema)),
  ),
  picker: z.optional(
    z.nullable(z.lazy(() => GetNsByNamespaceConnectorsPicker$inboundSchema)),
  ),
});

export function getNsByNamespaceConnectorsConnectorFromJSON(
  jsonString: string,
): SafeParseResult<GetNsByNamespaceConnectorsConnector, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetNsByNamespaceConnectorsConnector$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetNsByNamespaceConnectorsConnector' from JSON`,
  );
}

/** @internal */
export const GetNsByNamespaceConnectorsPagination$inboundSchema: z.ZodMiniType<
  GetNsByNamespaceConnectorsPagination,
  unknown
> = z.object({
  currentPage: types.number(),
  limit: z._default(types.number(), 10),
  totalItems: types.number(),
  totalPages: types.number(),
});

export function getNsByNamespaceConnectorsPaginationFromJSON(
  jsonString: string,
): SafeParseResult<GetNsByNamespaceConnectorsPagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetNsByNamespaceConnectorsPagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetNsByNamespaceConnectorsPagination' from JSON`,
  );
}

/** @internal */
export const GetNsByNamespaceConnectorsResponse$inboundSchema: z.ZodMiniType<
  GetNsByNamespaceConnectorsResponse,
  unknown
> = z.object({
  connectors: z.array(
    z.lazy(() => GetNsByNamespaceConnectorsConnector$inboundSchema),
  ),
  pagination: z.lazy(() => GetNsByNamespaceConnectorsPagination$inboundSchema),
});

export function getNsByNamespaceConnectorsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetNsByNamespaceConnectorsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetNsByNamespaceConnectorsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetNsByNamespaceConnectorsResponse' from JSON`,
  );
}
