/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 7faaba94b10f
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { ClosedEnum, OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * `active` returns in-flight documents updated in the last 4 hours. `all` also includes failed and stuck documents.
 */
export const View = {
  Active: "active",
  All: "all",
} as const;
/**
 * `active` returns in-flight documents updated in the last 4 hours. `all` also includes failed and stuck documents.
 */
export type View = ClosedEnum<typeof View>;

/**
 * Page number to fetch. Used with `view=all`.
 */
export type GetV3DocumentsProcessingPage = string | number;

/**
 * Number of items per page. Used with `view=all`.
 */
export type GetV3DocumentsProcessingLimit = string | number;

export type GetV3DocumentsProcessingRequest = {
  /**
   * `active` returns in-flight documents updated in the last 4 hours. `all` also includes failed and stuck documents.
   */
  view?: View | undefined;
  /**
   * Comma-separated container tags to filter by
   */
  containerTags?: string | undefined;
  /**
   * Page number to fetch. Used with `view=all`.
   */
  page?: string | number | undefined;
  /**
   * Number of items per page. Used with `view=all`.
   */
  limit?: string | number | undefined;
};

/**
 * Type of the document
 */
export const GetV3DocumentsProcessingType = {
  Text: "text",
  Pdf: "pdf",
  Tweet: "tweet",
  GoogleDoc: "google_doc",
  GoogleSlide: "google_slide",
  GoogleSheet: "google_sheet",
  Image: "image",
  Video: "video",
  Audio: "audio",
  NotionDoc: "notion_doc",
  Webpage: "webpage",
  Onedrive: "onedrive",
  GithubMarkdown: "github_markdown",
  Granola: "granola",
} as const;
/**
 * Type of the document
 */
export type GetV3DocumentsProcessingType = OpenEnum<
  typeof GetV3DocumentsProcessingType
>;

/**
 * Status of the document
 */
export const GetV3DocumentsProcessingStatus = {
  Unknown: "unknown",
  Queued: "queued",
  Extracting: "extracting",
  Chunking: "chunking",
  Embedding: "embedding",
  Indexing: "indexing",
  Done: "done",
  Failed: "failed",
} as const;
/**
 * Status of the document
 */
export type GetV3DocumentsProcessingStatus = OpenEnum<
  typeof GetV3DocumentsProcessingStatus
>;

export type GetV3DocumentsProcessingMetadata1 = string | number | boolean;

/**
 * Optional metadata for the document. This is used to store additional information about the document. You can use this to store any additional information you need about the document. Metadata can be filtered through. Keys must be strings and are case sensitive. Values can be strings, numbers, or booleans. You cannot nest objects.
 */
export type GetV3DocumentsProcessingMetadata2 = string | number | boolean | {
  [k: string]: any;
} | Array<any>;

export type GetV3DocumentsProcessingDocument = {
  /**
   * Unique identifier of the document.
   */
  id: string;
  customId: string | null;
  title: string | null;
  /**
   * Type of the document
   */
  type: GetV3DocumentsProcessingType;
  /**
   * Status of the document
   */
  status: GetV3DocumentsProcessingStatus;
  summary: string | null;
  connectionId: string | null;
  /**
   * Creation timestamp
   */
  createdAt: string;
  /**
   * Last update timestamp
   */
  updatedAt: string;
  metadata:
    | string
    | number
    | boolean
    | { [k: string]: any }
    | Array<any>
    | null;
  /**
   * Optional tags this document should be containerized by. This can be an ID for your user, a project ID, or any other identifier you wish to use to group documents.
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  containerTags?: Array<string> | undefined;
  /**
   * True when the document is not done/failed and has not been updated for 4 hours
   */
  stuck?: boolean | undefined;
  /**
   * Stable error code when processing failed, if available
   */
  errorCode?: string | null | undefined;
  /**
   * Human-readable processing error, if available
   */
  errorMessage?: string | null | undefined;
};

/**
 * Present when `view=all`
 */
export type GetV3DocumentsProcessingPagination = {
  currentPage: number;
  limit: number;
  totalItems: number;
  totalPages: number;
};

/**
 * List of documents currently being processed
 */
export type GetV3DocumentsProcessingResponse = {
  documents: Array<GetV3DocumentsProcessingDocument>;
  /**
   * Total number of processing documents
   */
  totalCount: number;
  /**
   * Present when `view=all`
   */
  pagination?: GetV3DocumentsProcessingPagination | undefined;
};

/** @internal */
export const View$outboundSchema: z.ZodMiniEnum<typeof View> = z.enum(View);

/** @internal */
export type GetV3DocumentsProcessingPage$Outbound = string | number;

/** @internal */
export const GetV3DocumentsProcessingPage$outboundSchema: z.ZodMiniType<
  GetV3DocumentsProcessingPage$Outbound,
  GetV3DocumentsProcessingPage
> = smartUnion([z.string(), z.number()]);

export function getV3DocumentsProcessingPageToJSON(
  getV3DocumentsProcessingPage: GetV3DocumentsProcessingPage,
): string {
  return JSON.stringify(
    GetV3DocumentsProcessingPage$outboundSchema.parse(
      getV3DocumentsProcessingPage,
    ),
  );
}

/** @internal */
export type GetV3DocumentsProcessingLimit$Outbound = string | number;

/** @internal */
export const GetV3DocumentsProcessingLimit$outboundSchema: z.ZodMiniType<
  GetV3DocumentsProcessingLimit$Outbound,
  GetV3DocumentsProcessingLimit
> = smartUnion([z.string(), z.number()]);

export function getV3DocumentsProcessingLimitToJSON(
  getV3DocumentsProcessingLimit: GetV3DocumentsProcessingLimit,
): string {
  return JSON.stringify(
    GetV3DocumentsProcessingLimit$outboundSchema.parse(
      getV3DocumentsProcessingLimit,
    ),
  );
}

/** @internal */
export type GetV3DocumentsProcessingRequest$Outbound = {
  view: string;
  containerTags?: string | undefined;
  page?: string | number | undefined;
  limit?: string | number | undefined;
};

/** @internal */
export const GetV3DocumentsProcessingRequest$outboundSchema: z.ZodMiniType<
  GetV3DocumentsProcessingRequest$Outbound,
  GetV3DocumentsProcessingRequest
> = z.object({
  view: z._default(View$outboundSchema, "active"),
  containerTags: z.optional(z.string()),
  page: z.optional(smartUnion([z.string(), z.number()])),
  limit: z.optional(smartUnion([z.string(), z.number()])),
});

export function getV3DocumentsProcessingRequestToJSON(
  getV3DocumentsProcessingRequest: GetV3DocumentsProcessingRequest,
): string {
  return JSON.stringify(
    GetV3DocumentsProcessingRequest$outboundSchema.parse(
      getV3DocumentsProcessingRequest,
    ),
  );
}

/** @internal */
export const GetV3DocumentsProcessingType$inboundSchema: z.ZodMiniType<
  GetV3DocumentsProcessingType,
  unknown
> = openEnums.inboundSchema(GetV3DocumentsProcessingType);

/** @internal */
export const GetV3DocumentsProcessingStatus$inboundSchema: z.ZodMiniType<
  GetV3DocumentsProcessingStatus,
  unknown
> = openEnums.inboundSchema(GetV3DocumentsProcessingStatus);

/** @internal */
export const GetV3DocumentsProcessingMetadata1$inboundSchema: z.ZodMiniType<
  GetV3DocumentsProcessingMetadata1,
  unknown
> = smartUnion([types.string(), types.number(), types.boolean()]);

export function getV3DocumentsProcessingMetadata1FromJSON(
  jsonString: string,
): SafeParseResult<GetV3DocumentsProcessingMetadata1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV3DocumentsProcessingMetadata1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV3DocumentsProcessingMetadata1' from JSON`,
  );
}

/** @internal */
export const GetV3DocumentsProcessingMetadata2$inboundSchema: z.ZodMiniType<
  GetV3DocumentsProcessingMetadata2,
  unknown
> = smartUnion([
  smartUnion([types.string(), types.number(), types.boolean()]),
  z.record(z.string(), z.any()),
  z.array(z.any()),
]);

export function getV3DocumentsProcessingMetadata2FromJSON(
  jsonString: string,
): SafeParseResult<GetV3DocumentsProcessingMetadata2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV3DocumentsProcessingMetadata2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV3DocumentsProcessingMetadata2' from JSON`,
  );
}

/** @internal */
export const GetV3DocumentsProcessingDocument$inboundSchema: z.ZodMiniType<
  GetV3DocumentsProcessingDocument,
  unknown
> = z.object({
  id: types.string(),
  customId: types.nullable(types.string()),
  title: types.nullable(types.string()),
  type: GetV3DocumentsProcessingType$inboundSchema,
  status: GetV3DocumentsProcessingStatus$inboundSchema,
  summary: types.nullable(types.string()),
  connectionId: types.nullable(types.string()),
  createdAt: types.string(),
  updatedAt: types.string(),
  metadata: types.nullable(
    smartUnion([
      smartUnion([types.string(), types.number(), types.boolean()]),
      z.record(z.string(), z.any()),
      z.array(z.any()),
    ]),
  ),
  containerTags: types.optional(z.array(types.string())),
  stuck: types.optional(types.boolean()),
  errorCode: z.optional(z.nullable(types.string())),
  errorMessage: z.optional(z.nullable(types.string())),
});

export function getV3DocumentsProcessingDocumentFromJSON(
  jsonString: string,
): SafeParseResult<GetV3DocumentsProcessingDocument, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV3DocumentsProcessingDocument$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV3DocumentsProcessingDocument' from JSON`,
  );
}

/** @internal */
export const GetV3DocumentsProcessingPagination$inboundSchema: z.ZodMiniType<
  GetV3DocumentsProcessingPagination,
  unknown
> = z.object({
  currentPage: types.number(),
  limit: z._default(types.number(), 10),
  totalItems: types.number(),
  totalPages: types.number(),
});

export function getV3DocumentsProcessingPaginationFromJSON(
  jsonString: string,
): SafeParseResult<GetV3DocumentsProcessingPagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV3DocumentsProcessingPagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV3DocumentsProcessingPagination' from JSON`,
  );
}

/** @internal */
export const GetV3DocumentsProcessingResponse$inboundSchema: z.ZodMiniType<
  GetV3DocumentsProcessingResponse,
  unknown
> = z.object({
  documents: z.array(
    z.lazy(() => GetV3DocumentsProcessingDocument$inboundSchema),
  ),
  totalCount: types.number(),
  pagination: types.optional(
    z.lazy(() => GetV3DocumentsProcessingPagination$inboundSchema),
  ),
});

export function getV3DocumentsProcessingResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV3DocumentsProcessingResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV3DocumentsProcessingResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV3DocumentsProcessingResponse' from JSON`,
  );
}
