/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV3ContainerTagsByContainerTagRequest = {
  containerTag: string;
};

/**
 * Definition of a single profile bucket
 */
export type GetV3ContainerTagsByContainerTagProfileBucket = {
  /**
   * Stable slug for the bucket, stored on each memory
   */
  key: string;
  /**
   * What belongs in this bucket — used to guide the ingestion classifier.
   */
  description: string;
};

/**
 * Container tag settings including entity context
 */
export type GetV3ContainerTagsByContainerTagResponse = {
  /**
   * The container tag identifier
   */
  containerTag: string;
  /**
   * Display name for this container tag
   */
  name: string | null;
  /**
   * Custom context prompt for this container tag. Used to provide additional context when processing documents in this container.
   */
  entityContext: string | null;
  /**
   * Per-tag allowlist of filesystem paths that trigger memory generation for mount-ingested documents. Docs whose filepath does not match are ingested as 'superrag' (chunked and searchable, no memory extraction).
   */
  memoryFilesystemPaths: Array<string> | null;
  /**
   * Container-tag-level buckets added on top of the org buckets (add-only)
   */
  profileBuckets: Array<GetV3ContainerTagsByContainerTagProfileBucket>;
  /**
   * Creation timestamp
   */
  createdAt: string;
  /**
   * Last update timestamp
   */
  updatedAt: string;
};

/** @internal */
export type GetV3ContainerTagsByContainerTagRequest$Outbound = {
  containerTag: string;
};

/** @internal */
export const GetV3ContainerTagsByContainerTagRequest$outboundSchema:
  z.ZodMiniType<
    GetV3ContainerTagsByContainerTagRequest$Outbound,
    GetV3ContainerTagsByContainerTagRequest
  > = z.object({
    containerTag: z.string(),
  });

export function getV3ContainerTagsByContainerTagRequestToJSON(
  getV3ContainerTagsByContainerTagRequest:
    GetV3ContainerTagsByContainerTagRequest,
): string {
  return JSON.stringify(
    GetV3ContainerTagsByContainerTagRequest$outboundSchema.parse(
      getV3ContainerTagsByContainerTagRequest,
    ),
  );
}

/** @internal */
export const GetV3ContainerTagsByContainerTagProfileBucket$inboundSchema:
  z.ZodMiniType<GetV3ContainerTagsByContainerTagProfileBucket, unknown> = z
    .object({
      key: types.string(),
      description: z._default(types.string(), ""),
    });

export function getV3ContainerTagsByContainerTagProfileBucketFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV3ContainerTagsByContainerTagProfileBucket,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV3ContainerTagsByContainerTagProfileBucket$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV3ContainerTagsByContainerTagProfileBucket' from JSON`,
  );
}

/** @internal */
export const GetV3ContainerTagsByContainerTagResponse$inboundSchema:
  z.ZodMiniType<GetV3ContainerTagsByContainerTagResponse, unknown> = z.object({
    containerTag: types.string(),
    name: types.nullable(types.string()),
    entityContext: types.nullable(types.string()),
    memoryFilesystemPaths: types.nullable(z.array(types.string())),
    profileBuckets: z.array(
      z.lazy(() => GetV3ContainerTagsByContainerTagProfileBucket$inboundSchema),
    ),
    createdAt: types.string(),
    updatedAt: types.string(),
  });

export function getV3ContainerTagsByContainerTagResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV3ContainerTagsByContainerTagResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV3ContainerTagsByContainerTagResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV3ContainerTagsByContainerTagResponse' from JSON`,
  );
}
