/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 50b54a3f8887
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV3ContainerTagsMergeByMergeIdRequest = {
  mergeId: string;
};

export const GetV3ContainerTagsMergeByMergeIdStatus = {
  Queued: "queued",
  WaitingForIngest: "waiting_for_ingest",
  CopyingVectors: "copying_vectors",
  DbCommitting: "db_committing",
  CleanupPending: "cleanup_pending",
  Completed: "completed",
  Failed: "failed",
} as const;
export type GetV3ContainerTagsMergeByMergeIdStatus = OpenEnum<
  typeof GetV3ContainerTagsMergeByMergeIdStatus
>;

export const Phase = {
  Queued: "queued",
  WaitingForIngest: "waiting_for_ingest",
  CopyingVectors: "copying_vectors",
  DbCommitting: "db_committing",
  CleanupPending: "cleanup_pending",
  Completed: "completed",
  Failed: "failed",
} as const;
export type Phase = OpenEnum<typeof Phase>;

export const CurrentKind = {
  Chunk: "chunk",
  Memory: "memory",
} as const;
export type CurrentKind = OpenEnum<typeof CurrentKind>;

export type Progress = {
  phase?: Phase | undefined;
  currentSourceTag?: string | undefined;
  currentKind?: CurrentKind | undefined;
  copiedRows?: number | undefined;
  completedSourceTags?: Array<string> | undefined;
  inFlightItems?: number | undefined;
  attempt?: number | undefined;
};

/**
 * Merge job status
 */
export type GetV3ContainerTagsMergeByMergeIdResponse = {
  id: string;
  status: GetV3ContainerTagsMergeByMergeIdStatus;
  sourceTags: Array<string>;
  targetTag: string;
  progress: Progress | null;
  lastError: string | null;
};

/** @internal */
export type GetV3ContainerTagsMergeByMergeIdRequest$Outbound = {
  mergeId: string;
};

/** @internal */
export const GetV3ContainerTagsMergeByMergeIdRequest$outboundSchema:
  z.ZodMiniType<
    GetV3ContainerTagsMergeByMergeIdRequest$Outbound,
    GetV3ContainerTagsMergeByMergeIdRequest
  > = z.object({
    mergeId: z.string(),
  });

export function getV3ContainerTagsMergeByMergeIdRequestToJSON(
  getV3ContainerTagsMergeByMergeIdRequest:
    GetV3ContainerTagsMergeByMergeIdRequest,
): string {
  return JSON.stringify(
    GetV3ContainerTagsMergeByMergeIdRequest$outboundSchema.parse(
      getV3ContainerTagsMergeByMergeIdRequest,
    ),
  );
}

/** @internal */
export const GetV3ContainerTagsMergeByMergeIdStatus$inboundSchema:
  z.ZodMiniType<GetV3ContainerTagsMergeByMergeIdStatus, unknown> = openEnums
    .inboundSchema(GetV3ContainerTagsMergeByMergeIdStatus);

/** @internal */
export const Phase$inboundSchema: z.ZodMiniType<Phase, unknown> = openEnums
  .inboundSchema(Phase);

/** @internal */
export const CurrentKind$inboundSchema: z.ZodMiniType<CurrentKind, unknown> =
  openEnums.inboundSchema(CurrentKind);

/** @internal */
export const Progress$inboundSchema: z.ZodMiniType<Progress, unknown> = z
  .object({
    phase: types.optional(Phase$inboundSchema),
    currentSourceTag: types.optional(types.string()),
    currentKind: types.optional(CurrentKind$inboundSchema),
    copiedRows: types.optional(types.number()),
    completedSourceTags: types.optional(z.array(types.string())),
    inFlightItems: types.optional(types.number()),
    attempt: types.optional(types.number()),
  });

export function progressFromJSON(
  jsonString: string,
): SafeParseResult<Progress, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Progress$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Progress' from JSON`,
  );
}

/** @internal */
export const GetV3ContainerTagsMergeByMergeIdResponse$inboundSchema:
  z.ZodMiniType<GetV3ContainerTagsMergeByMergeIdResponse, unknown> = z.object({
    id: types.string(),
    status: GetV3ContainerTagsMergeByMergeIdStatus$inboundSchema,
    sourceTags: z.array(types.string()),
    targetTag: types.string(),
    progress: types.nullable(z.lazy(() => Progress$inboundSchema)),
    lastError: types.nullable(types.string()),
  });

export function getV3ContainerTagsMergeByMergeIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV3ContainerTagsMergeByMergeIdResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV3ContainerTagsMergeByMergeIdResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV3ContainerTagsMergeByMergeIdResponse' from JSON`,
  );
}
