/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV3ContainerTagsMergeByMergeIdRequest = {
  mergeId: string;
};

/**
 * Merge job status
 */
export type GetV3ContainerTagsMergeByMergeIdResponse = {
  id: string;
};

/** @internal */
export type GetV3ContainerTagsMergeByMergeIdRequest$Outbound = {
  mergeId: string;
};

/** @internal */
export const GetV3ContainerTagsMergeByMergeIdRequest$outboundSchema:
  z.ZodMiniType<
    GetV3ContainerTagsMergeByMergeIdRequest$Outbound,
    GetV3ContainerTagsMergeByMergeIdRequest
  > = z.object({
    mergeId: z.string(),
  });

export function getV3ContainerTagsMergeByMergeIdRequestToJSON(
  getV3ContainerTagsMergeByMergeIdRequest:
    GetV3ContainerTagsMergeByMergeIdRequest,
): string {
  return JSON.stringify(
    GetV3ContainerTagsMergeByMergeIdRequest$outboundSchema.parse(
      getV3ContainerTagsMergeByMergeIdRequest,
    ),
  );
}

/** @internal */
export const GetV3ContainerTagsMergeByMergeIdResponse$inboundSchema:
  z.ZodMiniType<GetV3ContainerTagsMergeByMergeIdResponse, unknown> = z.object({
    id: types.string(),
  });

export function getV3ContainerTagsMergeByMergeIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV3ContainerTagsMergeByMergeIdResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV3ContainerTagsMergeByMergeIdResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV3ContainerTagsMergeByMergeIdResponse' from JSON`,
  );
}
