/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 01153803ef8c
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV3DocumentsByIdRequest = {
  id: string;
};

export type GetV3DocumentsByIdMetadata1 = string | number | boolean;

/**
 * Optional metadata for the document. This is used to store additional information about the document. You can use this to store any additional information you need about the document. Metadata can be filtered through. Keys must be strings and are case sensitive. Values can be strings, numbers, or booleans. You cannot nest objects.
 */
export type GetV3DocumentsByIdMetadata2 = string | number | boolean | {
  [k: string]: any;
} | Array<any>;

/**
 * Task type: "memory" (default) for full context layer with SuperRAG built in, "superrag" for managed RAG as a service.
 */
export const GetV3DocumentsByIdTaskType = {
  Memory: "memory",
  Superrag: "superrag",
} as const;
/**
 * Task type: "memory" (default) for full context layer with SuperRAG built in, "superrag" for managed RAG as a service.
 */
export type GetV3DocumentsByIdTaskType = OpenEnum<
  typeof GetV3DocumentsByIdTaskType
>;

/**
 * Status of the document
 */
export const GetV3DocumentsByIdStatus = {
  Unknown: "unknown",
  Queued: "queued",
  Extracting: "extracting",
  Chunking: "chunking",
  Embedding: "embedding",
  Indexing: "indexing",
  Done: "done",
  Failed: "failed",
} as const;
/**
 * Status of the document
 */
export type GetV3DocumentsByIdStatus = OpenEnum<
  typeof GetV3DocumentsByIdStatus
>;

export const DreamingStatus = {
  Dreaming: "dreaming",
  Done: "done",
} as const;
export type DreamingStatus = OpenEnum<typeof DreamingStatus>;

/**
 * Type of the document
 */
export const GetV3DocumentsByIdType = {
  Text: "text",
  Pdf: "pdf",
  Tweet: "tweet",
  GoogleDoc: "google_doc",
  GoogleSlide: "google_slide",
  GoogleSheet: "google_sheet",
  Image: "image",
  Video: "video",
  Audio: "audio",
  NotionDoc: "notion_doc",
  Webpage: "webpage",
  Onedrive: "onedrive",
  GithubMarkdown: "github_markdown",
  Granola: "granola",
} as const;
/**
 * Type of the document
 */
export type GetV3DocumentsByIdType = OpenEnum<typeof GetV3DocumentsByIdType>;

export type GetV3DocumentsByIdMetadataMemory = string | number | boolean;

export type GetV3DocumentsByIdMemoryMetadata = string | number | boolean | {
  [k: string]: any;
} | Array<any>;

export type GetV3DocumentsByIdMemory = {
  id: string;
  memory: string;
  /**
   * Creation timestamp
   */
  createdAt: string;
  /**
   * Last update timestamp
   */
  updatedAt: string | null;
  isLatest: boolean;
  isForgotten: boolean;
  isStatic: boolean;
  isInference: boolean;
  version: number;
  sourceCount: number;
  metadata:
    | string
    | number
    | boolean
    | { [k: string]: any }
    | Array<any>
    | null;
  parentMemoryId: string | null;
  rootMemoryId: string | null;
};

/**
 * Successfully retrieved document
 */
export type GetV3DocumentsByIdResponse = {
  connectionId: string | null;
  content: string | null;
  /**
   * Optional tags this document should be containerized by. This can be an ID for your user, a project ID, or any other identifier you wish to use to group documents.
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  containerTags?: Array<string> | undefined;
  /**
   * Creation timestamp
   */
  createdAt: string;
  customId: string | null;
  /**
   * Unique identifier of the document.
   */
  id: string;
  metadata:
    | string
    | number
    | boolean
    | { [k: string]: any }
    | Array<any>
    | null;
  ogImage: string | null;
  raw: any | null;
  source: string | null;
  /**
   * Task type: "memory" (default) for full context layer with SuperRAG built in, "superrag" for managed RAG as a service.
   */
  taskType: GetV3DocumentsByIdTaskType;
  /**
   * Status of the document
   */
  status: GetV3DocumentsByIdStatus;
  dreamingStatus: DreamingStatus;
  summary: string | null;
  title: string | null;
  /**
   * Type of the document
   */
  type: GetV3DocumentsByIdType;
  /**
   * Last update timestamp
   */
  updatedAt: string;
  url?: string | null | undefined;
  filepath: string | null;
  /**
   * Memories extracted from this document. Omitted when the document has no memories (e.g. still processing).
   */
  memories?: Array<GetV3DocumentsByIdMemory> | undefined;
};

/** @internal */
export type GetV3DocumentsByIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetV3DocumentsByIdRequest$outboundSchema: z.ZodMiniType<
  GetV3DocumentsByIdRequest$Outbound,
  GetV3DocumentsByIdRequest
> = z.object({
  id: z.string(),
});

export function getV3DocumentsByIdRequestToJSON(
  getV3DocumentsByIdRequest: GetV3DocumentsByIdRequest,
): string {
  return JSON.stringify(
    GetV3DocumentsByIdRequest$outboundSchema.parse(getV3DocumentsByIdRequest),
  );
}

/** @internal */
export const GetV3DocumentsByIdMetadata1$inboundSchema: z.ZodMiniType<
  GetV3DocumentsByIdMetadata1,
  unknown
> = smartUnion([types.string(), types.number(), types.boolean()]);

export function getV3DocumentsByIdMetadata1FromJSON(
  jsonString: string,
): SafeParseResult<GetV3DocumentsByIdMetadata1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV3DocumentsByIdMetadata1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV3DocumentsByIdMetadata1' from JSON`,
  );
}

/** @internal */
export const GetV3DocumentsByIdMetadata2$inboundSchema: z.ZodMiniType<
  GetV3DocumentsByIdMetadata2,
  unknown
> = smartUnion([
  smartUnion([types.string(), types.number(), types.boolean()]),
  z.record(z.string(), z.any()),
  z.array(z.any()),
]);

export function getV3DocumentsByIdMetadata2FromJSON(
  jsonString: string,
): SafeParseResult<GetV3DocumentsByIdMetadata2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV3DocumentsByIdMetadata2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV3DocumentsByIdMetadata2' from JSON`,
  );
}

/** @internal */
export const GetV3DocumentsByIdTaskType$inboundSchema: z.ZodMiniType<
  GetV3DocumentsByIdTaskType,
  unknown
> = openEnums.inboundSchema(GetV3DocumentsByIdTaskType);

/** @internal */
export const GetV3DocumentsByIdStatus$inboundSchema: z.ZodMiniType<
  GetV3DocumentsByIdStatus,
  unknown
> = openEnums.inboundSchema(GetV3DocumentsByIdStatus);

/** @internal */
export const DreamingStatus$inboundSchema: z.ZodMiniType<
  DreamingStatus,
  unknown
> = openEnums.inboundSchema(DreamingStatus);

/** @internal */
export const GetV3DocumentsByIdType$inboundSchema: z.ZodMiniType<
  GetV3DocumentsByIdType,
  unknown
> = openEnums.inboundSchema(GetV3DocumentsByIdType);

/** @internal */
export const GetV3DocumentsByIdMetadataMemory$inboundSchema: z.ZodMiniType<
  GetV3DocumentsByIdMetadataMemory,
  unknown
> = smartUnion([types.string(), types.number(), types.boolean()]);

export function getV3DocumentsByIdMetadataMemoryFromJSON(
  jsonString: string,
): SafeParseResult<GetV3DocumentsByIdMetadataMemory, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV3DocumentsByIdMetadataMemory$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV3DocumentsByIdMetadataMemory' from JSON`,
  );
}

/** @internal */
export const GetV3DocumentsByIdMemoryMetadata$inboundSchema: z.ZodMiniType<
  GetV3DocumentsByIdMemoryMetadata,
  unknown
> = smartUnion([
  smartUnion([types.string(), types.number(), types.boolean()]),
  z.record(z.string(), z.any()),
  z.array(z.any()),
]);

export function getV3DocumentsByIdMemoryMetadataFromJSON(
  jsonString: string,
): SafeParseResult<GetV3DocumentsByIdMemoryMetadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV3DocumentsByIdMemoryMetadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV3DocumentsByIdMemoryMetadata' from JSON`,
  );
}

/** @internal */
export const GetV3DocumentsByIdMemory$inboundSchema: z.ZodMiniType<
  GetV3DocumentsByIdMemory,
  unknown
> = z.object({
  id: types.string(),
  memory: types.string(),
  createdAt: types.string(),
  updatedAt: types.nullable(types.string()),
  isLatest: types.boolean(),
  isForgotten: types.boolean(),
  isStatic: types.boolean(),
  isInference: types.boolean(),
  version: types.number(),
  sourceCount: types.number(),
  metadata: types.nullable(
    smartUnion([
      smartUnion([types.string(), types.number(), types.boolean()]),
      z.record(z.string(), z.any()),
      z.array(z.any()),
    ]),
  ),
  parentMemoryId: types.nullable(types.string()),
  rootMemoryId: types.nullable(types.string()),
});

export function getV3DocumentsByIdMemoryFromJSON(
  jsonString: string,
): SafeParseResult<GetV3DocumentsByIdMemory, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV3DocumentsByIdMemory$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV3DocumentsByIdMemory' from JSON`,
  );
}

/** @internal */
export const GetV3DocumentsByIdResponse$inboundSchema: z.ZodMiniType<
  GetV3DocumentsByIdResponse,
  unknown
> = z.object({
  connectionId: types.nullable(types.string()),
  content: types.nullable(types.string()),
  containerTags: types.optional(z.array(types.string())),
  createdAt: types.string(),
  customId: types.nullable(types.string()),
  id: types.string(),
  metadata: types.nullable(
    smartUnion([
      smartUnion([types.string(), types.number(), types.boolean()]),
      z.record(z.string(), z.any()),
      z.array(z.any()),
    ]),
  ),
  ogImage: types.nullable(types.string()),
  raw: types.nullable(z.any()),
  source: types.nullable(types.string()),
  taskType: GetV3DocumentsByIdTaskType$inboundSchema,
  status: GetV3DocumentsByIdStatus$inboundSchema,
  dreamingStatus: DreamingStatus$inboundSchema,
  summary: types.nullable(types.string()),
  title: types.nullable(types.string()),
  type: GetV3DocumentsByIdType$inboundSchema,
  updatedAt: types.string(),
  url: z.optional(z.nullable(types.string())),
  filepath: types.nullable(types.string()),
  memories: types.optional(
    z.array(z.lazy(() => GetV3DocumentsByIdMemory$inboundSchema)),
  ),
});

export function getV3DocumentsByIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV3DocumentsByIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV3DocumentsByIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV3DocumentsByIdResponse' from JSON`,
  );
}
