/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0e587a6e43dc
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type PatchOrganizationRequest = {
  /**
   * Shared background that guides memory formation across every namespace. Set null to clear it.
   */
  organizationalContext: string | null;
};

/**
 * Organization settings updated successfully
 */
export type PatchOrganizationResponse = {
  /**
   * Shared background that helps Supermemory interpret content consistently across every namespace
   */
  organizationalContext: string | null;
  /**
   * Number of namespaces in the organization
   */
  namespaceCount: number;
};

/** @internal */
export type PatchOrganizationRequest$Outbound = {
  organizationalContext: string | null;
};

/** @internal */
export const PatchOrganizationRequest$outboundSchema: z.ZodMiniType<
  PatchOrganizationRequest$Outbound,
  PatchOrganizationRequest
> = z.object({
  organizationalContext: z.nullable(z.string()),
});

export function patchOrganizationRequestToJSON(
  patchOrganizationRequest: PatchOrganizationRequest,
): string {
  return JSON.stringify(
    PatchOrganizationRequest$outboundSchema.parse(patchOrganizationRequest),
  );
}

/** @internal */
export const PatchOrganizationResponse$inboundSchema: z.ZodMiniType<
  PatchOrganizationResponse,
  unknown
> = z.object({
  organizationalContext: types.nullable(types.string()),
  namespaceCount: types.number(),
});

export function patchOrganizationResponseFromJSON(
  jsonString: string,
): SafeParseResult<PatchOrganizationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchOrganizationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchOrganizationResponse' from JSON`,
  );
}
