/*
 * Generated by scripts/surface/generate.ts from fern/openapi.json. DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as types from "../../types/primitives.js";

export const PatchNsByNamespaceDocumentByIdTaskType = {
  Memory: "memory",
  Superrag: "superrag",
} as const;
export type PatchNsByNamespaceDocumentByIdTaskType = ClosedEnum<typeof PatchNsByNamespaceDocumentByIdTaskType>;

/** @internal */
export const PatchNsByNamespaceDocumentByIdTaskType$outboundSchema: z.ZodMiniEnum<typeof PatchNsByNamespaceDocumentByIdTaskType> = z.enum(PatchNsByNamespaceDocumentByIdTaskType);

export const PatchNsByNamespaceDocumentByIdDreaming = {
  Dynamic: "dynamic",
  Instant: "instant",
} as const;
export type PatchNsByNamespaceDocumentByIdDreaming = ClosedEnum<typeof PatchNsByNamespaceDocumentByIdDreaming>;

/** @internal */
export const PatchNsByNamespaceDocumentByIdDreaming$outboundSchema: z.ZodMiniEnum<typeof PatchNsByNamespaceDocumentByIdDreaming> = z.enum(PatchNsByNamespaceDocumentByIdDreaming);

export type PatchNsByNamespaceDocumentByIdRequestBody = {
  /**
   * The content to process. This may be plaintext or a URL to supported rich content.
   */
  content?: string | undefined;
  /**
   * Context used to guide memory extraction within this namespace. Max 1500 characters.
   */
  supportingContext?: string | undefined;
  /**
   * Arbitrary metadata attached to the document and derived data
   */
  metadata?: { [k: string]: string | number | boolean | Array<string> } | undefined;
  /**
   * Metadata values that isolate related context within the namespace
   */
  group?: { [k: string]: string | number | boolean | Array<string> } | undefined;
  /**
   * When the source content is from, in ISO 8601 format
   */
  date?: string | undefined;
};

/** @internal */
export type PatchNsByNamespaceDocumentByIdRequestBody$Outbound = {
  /**
   * The content to process. This may be plaintext or a URL to supported rich content.
   */
  content?: string | undefined;
  /**
   * Context used to guide memory extraction within this namespace. Max 1500 characters.
   */
  supportingContext?: string | undefined;
  /**
   * Arbitrary metadata attached to the document and derived data
   */
  metadata?: { [k: string]: string | number | boolean | Array<string> } | undefined;
  /**
   * Metadata values that isolate related context within the namespace
   */
  group?: { [k: string]: string | number | boolean | Array<string> } | undefined;
  /**
   * When the source content is from, in ISO 8601 format
   */
  date?: string | undefined;
};

/** @internal */
export const PatchNsByNamespaceDocumentByIdRequestBody$outboundSchema: z.ZodMiniType<PatchNsByNamespaceDocumentByIdRequestBody$Outbound, PatchNsByNamespaceDocumentByIdRequestBody> = z.object({
  content: z.optional(z.string()),
  supportingContext: z.optional(z.string()),
  metadata: z.optional(z.record(z.string(), smartUnion([z.string(), z.number(), z.boolean(), z.array(z.string())]))),
  group: z.optional(z.record(z.string(), smartUnion([z.string(), z.number(), z.boolean(), z.array(z.string())]))),
  date: z.optional(z.string()),
});

export function patchNsByNamespaceDocumentByIdRequestBodyToJSON(
  patchNsByNamespaceDocumentByIdRequestBody: PatchNsByNamespaceDocumentByIdRequestBody,
): string {
  return JSON.stringify(PatchNsByNamespaceDocumentByIdRequestBody$outboundSchema.parse(patchNsByNamespaceDocumentByIdRequestBody));
}

export type PatchNsByNamespaceDocumentByIdMetadata =
  | string
  | number
  | boolean
  | Array<string>
;

/** @internal */
export type PatchNsByNamespaceDocumentByIdMetadata$Outbound =
  | string
  | number
  | boolean
  | Array<string>
;

/** @internal */
export const PatchNsByNamespaceDocumentByIdMetadata$outboundSchema: z.ZodMiniType<PatchNsByNamespaceDocumentByIdMetadata$Outbound, PatchNsByNamespaceDocumentByIdMetadata> = smartUnion([
  z.string(),
  z.number(),
  z.boolean(),
  z.array(z.string()),
]);

export function patchNsByNamespaceDocumentByIdMetadataToJSON(
  patchNsByNamespaceDocumentByIdMetadata: PatchNsByNamespaceDocumentByIdMetadata,
): string {
  return JSON.stringify(PatchNsByNamespaceDocumentByIdMetadata$outboundSchema.parse(patchNsByNamespaceDocumentByIdMetadata));
}

export type PatchNsByNamespaceDocumentByIdGroup =
  | string
  | number
  | boolean
  | Array<string>
;

/** @internal */
export type PatchNsByNamespaceDocumentByIdGroup$Outbound =
  | string
  | number
  | boolean
  | Array<string>
;

/** @internal */
export const PatchNsByNamespaceDocumentByIdGroup$outboundSchema: z.ZodMiniType<PatchNsByNamespaceDocumentByIdGroup$Outbound, PatchNsByNamespaceDocumentByIdGroup> = smartUnion([
  z.string(),
  z.number(),
  z.boolean(),
  z.array(z.string()),
]);

export function patchNsByNamespaceDocumentByIdGroupToJSON(
  patchNsByNamespaceDocumentByIdGroup: PatchNsByNamespaceDocumentByIdGroup,
): string {
  return JSON.stringify(PatchNsByNamespaceDocumentByIdGroup$outboundSchema.parse(patchNsByNamespaceDocumentByIdGroup));
}

export type PatchNsByNamespaceDocumentByIdRequest = {
  namespace: string;
  id: string;
  taskType?: PatchNsByNamespaceDocumentByIdTaskType | undefined;
  dreaming?: PatchNsByNamespaceDocumentByIdDreaming | undefined;
  body: PatchNsByNamespaceDocumentByIdRequestBody;
};

/** @internal */
export type PatchNsByNamespaceDocumentByIdRequest$Outbound = {
  namespace: string;
  id: string;
  taskType?: string | undefined;
  dreaming?: string | undefined;
  body: PatchNsByNamespaceDocumentByIdRequestBody$Outbound;
};

/** @internal */
export const PatchNsByNamespaceDocumentByIdRequest$outboundSchema: z.ZodMiniType<PatchNsByNamespaceDocumentByIdRequest$Outbound, PatchNsByNamespaceDocumentByIdRequest> = z.object({
  namespace: z.string(),
  id: z.string(),
  taskType: z.optional(PatchNsByNamespaceDocumentByIdTaskType$outboundSchema),
  dreaming: z.optional(PatchNsByNamespaceDocumentByIdDreaming$outboundSchema),
  body: z.lazy(() => PatchNsByNamespaceDocumentByIdRequestBody$outboundSchema),
});

export function patchNsByNamespaceDocumentByIdRequestToJSON(
  patchNsByNamespaceDocumentByIdRequest: PatchNsByNamespaceDocumentByIdRequest,
): string {
  return JSON.stringify(PatchNsByNamespaceDocumentByIdRequest$outboundSchema.parse(patchNsByNamespaceDocumentByIdRequest));
}

export type PatchNsByNamespaceDocumentByIdResponse = {
  /**
   * Unique identifier of the document
   */
  id: string;
  /**
   * Status of the document
   */
  status: string;
};

/** @internal */
export const PatchNsByNamespaceDocumentByIdResponse$inboundSchema: z.ZodMiniType<PatchNsByNamespaceDocumentByIdResponse, unknown> = z.object({
  id: types.string(),
  status: types.string(),
});

export function patchNsByNamespaceDocumentByIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<PatchNsByNamespaceDocumentByIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchNsByNamespaceDocumentByIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchNsByNamespaceDocumentByIdResponse' from JSON`,
  );
}
