/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 90661d21d9b6
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type PatchV3DocumentsByIdMetadata =
  | string
  | number
  | boolean
  | Array<string>;

/**
 * Task type: "memory" (default) for full context layer with SuperRAG built in, "superrag" for managed RAG as a service.
 */
export const PatchV3DocumentsByIdTaskType = {
  Memory: "memory",
  Superrag: "superrag",
} as const;
/**
 * Task type: "memory" (default) for full context layer with SuperRAG built in, "superrag" for managed RAG as a service.
 */
export type PatchV3DocumentsByIdTaskType = ClosedEnum<
  typeof PatchV3DocumentsByIdTaskType
>;

export type PatchV3DocumentsByIdFilterByMetadata =
  | string
  | number
  | boolean
  | Array<string>;

export type PatchV3DocumentsByIdRequestBody = {
  /**
   * Optional tag this document should be containerized by. This can be an ID for your user, a project ID, or any other identifier you wish to use to group documents.
   */
  containerTag?: string | undefined;
  /**
   * (DEPRECATED: Use containerTag instead) Optional tags this document should be containerized by. This can be an ID for your user, a project ID, or any other identifier you wish to use to group documents.
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  containerTags?: Array<string> | undefined;
  /**
   * The content to extract and process into a document. This can be a URL to a website, a PDF, an image, or a video.
   *
   * @remarks
   *
   * Plaintext: Any plaintext format
   *
   * URL: A URL to a website, PDF, image, or video
   *
   * We automatically detect the content type from the url's response format.
   */
  content?: string | undefined;
  /**
   * Optional custom ID of the document. This could be an ID from your database that will uniquely identify this document.
   */
  customId?: string | undefined;
  /**
   * Optional metadata for the document. This is used to store additional information about the document. You can use this to store any additional information you need about the document. Metadata can be filtered through. Keys must be strings and are case sensitive. Values can be strings, numbers, or booleans. You cannot nest objects.
   */
  metadata?:
    | { [k: string]: string | number | boolean | Array<string> }
    | undefined;
  /**
   * Task type: "memory" (default) for full context layer with SuperRAG built in, "superrag" for managed RAG as a service.
   */
  taskType?: PatchV3DocumentsByIdTaskType | undefined;
  /**
   * Optional file path for the document (e.g., '/documents/reports/file.pdf'). Used by supermemoryfs to map documents to filesystem paths.
   */
  filepath?: string | undefined;
  /**
   * Optional metadata filter scoping which existing memories are pulled as context during ingestion. Scalar values match exactly (AND across keys); array values match ANY (OR within key). Only memories whose source documents match this filter are used as context.
   */
  filterByMetadata?:
    | { [k: string]: string | number | boolean | Array<string> }
    | undefined;
};

export type PatchV3DocumentsByIdRequest = {
  id: string;
  body: PatchV3DocumentsByIdRequestBody;
};

/**
 * Document updated successfully
 */
export type PatchV3DocumentsByIdResponse = {
  /**
   * Unique identifier of the document
   */
  id: string;
  /**
   * Status of the document
   */
  status: string;
};

/** @internal */
export type PatchV3DocumentsByIdMetadata$Outbound =
  | string
  | number
  | boolean
  | Array<string>;

/** @internal */
export const PatchV3DocumentsByIdMetadata$outboundSchema: z.ZodMiniType<
  PatchV3DocumentsByIdMetadata$Outbound,
  PatchV3DocumentsByIdMetadata
> = smartUnion([z.string(), z.number(), z.boolean(), z.array(z.string())]);

export function patchV3DocumentsByIdMetadataToJSON(
  patchV3DocumentsByIdMetadata: PatchV3DocumentsByIdMetadata,
): string {
  return JSON.stringify(
    PatchV3DocumentsByIdMetadata$outboundSchema.parse(
      patchV3DocumentsByIdMetadata,
    ),
  );
}

/** @internal */
export const PatchV3DocumentsByIdTaskType$outboundSchema: z.ZodMiniEnum<
  typeof PatchV3DocumentsByIdTaskType
> = z.enum(PatchV3DocumentsByIdTaskType);

/** @internal */
export type PatchV3DocumentsByIdFilterByMetadata$Outbound =
  | string
  | number
  | boolean
  | Array<string>;

/** @internal */
export const PatchV3DocumentsByIdFilterByMetadata$outboundSchema: z.ZodMiniType<
  PatchV3DocumentsByIdFilterByMetadata$Outbound,
  PatchV3DocumentsByIdFilterByMetadata
> = smartUnion([z.string(), z.number(), z.boolean(), z.array(z.string())]);

export function patchV3DocumentsByIdFilterByMetadataToJSON(
  patchV3DocumentsByIdFilterByMetadata: PatchV3DocumentsByIdFilterByMetadata,
): string {
  return JSON.stringify(
    PatchV3DocumentsByIdFilterByMetadata$outboundSchema.parse(
      patchV3DocumentsByIdFilterByMetadata,
    ),
  );
}

/** @internal */
export type PatchV3DocumentsByIdRequestBody$Outbound = {
  containerTag?: string | undefined;
  containerTags?: Array<string> | undefined;
  content?: string | undefined;
  customId?: string | undefined;
  metadata?:
    | { [k: string]: string | number | boolean | Array<string> }
    | undefined;
  taskType?: string | undefined;
  filepath?: string | undefined;
  filterByMetadata?:
    | { [k: string]: string | number | boolean | Array<string> }
    | undefined;
};

/** @internal */
export const PatchV3DocumentsByIdRequestBody$outboundSchema: z.ZodMiniType<
  PatchV3DocumentsByIdRequestBody$Outbound,
  PatchV3DocumentsByIdRequestBody
> = z.object({
  containerTag: z.optional(z.string()),
  containerTags: z.optional(z.array(z.string())),
  content: z.optional(z.string()),
  customId: z.optional(z.string()),
  metadata: z.optional(
    z.record(
      z.string(),
      smartUnion([z.string(), z.number(), z.boolean(), z.array(z.string())]),
    ),
  ),
  taskType: z.optional(PatchV3DocumentsByIdTaskType$outboundSchema),
  filepath: z.optional(z.string()),
  filterByMetadata: z.optional(
    z.record(
      z.string(),
      smartUnion([z.string(), z.number(), z.boolean(), z.array(z.string())]),
    ),
  ),
});

export function patchV3DocumentsByIdRequestBodyToJSON(
  patchV3DocumentsByIdRequestBody: PatchV3DocumentsByIdRequestBody,
): string {
  return JSON.stringify(
    PatchV3DocumentsByIdRequestBody$outboundSchema.parse(
      patchV3DocumentsByIdRequestBody,
    ),
  );
}

/** @internal */
export type PatchV3DocumentsByIdRequest$Outbound = {
  id: string;
  body: PatchV3DocumentsByIdRequestBody$Outbound;
};

/** @internal */
export const PatchV3DocumentsByIdRequest$outboundSchema: z.ZodMiniType<
  PatchV3DocumentsByIdRequest$Outbound,
  PatchV3DocumentsByIdRequest
> = z.object({
  id: z.string(),
  body: z.lazy(() => PatchV3DocumentsByIdRequestBody$outboundSchema),
});

export function patchV3DocumentsByIdRequestToJSON(
  patchV3DocumentsByIdRequest: PatchV3DocumentsByIdRequest,
): string {
  return JSON.stringify(
    PatchV3DocumentsByIdRequest$outboundSchema.parse(
      patchV3DocumentsByIdRequest,
    ),
  );
}

/** @internal */
export const PatchV3DocumentsByIdResponse$inboundSchema: z.ZodMiniType<
  PatchV3DocumentsByIdResponse,
  unknown
> = z.object({
  id: types.string(),
  status: types.string(),
});

export function patchV3DocumentsByIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<PatchV3DocumentsByIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchV3DocumentsByIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchV3DocumentsByIdResponse' from JSON`,
  );
}
