/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 67e42de37b6f
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Definition of a single profile bucket
 */
export type PatchV3ContainerTagsByContainerTagProfileBucketRequest = {
  /**
   * Stable slug for the bucket, stored on each memory
   */
  key: string;
  /**
   * What belongs in this bucket — used to guide the ingestion classifier.
   */
  description?: string | undefined;
};

/**
 * Request body for updating container tag settings
 */
export type PatchV3ContainerTagsByContainerTagRequestBody = {
  /**
   * Display name for this container tag. This does not change the container tag identifier.
   */
  name?: string | undefined;
  /**
   * Custom context prompt for this container tag. Used to provide additional context when processing documents in this container. Maximum 1500 characters.
   */
  entityContext?: string | null | undefined;
  /**
   * Per-tag allowlist of filesystem paths that trigger memory generation for mount-ingested documents. Docs whose filepath does not match are ingested as 'superrag' (chunked and searchable, no memory extraction).
   */
  memoryFilesystemPaths?: Array<string> | null | undefined;
  /**
   * Container-tag-level buckets to set (add-only on top of org buckets). Replaces this tag's own bucket list; cannot override or remove org buckets.
   */
  profileBuckets?:
    | Array<PatchV3ContainerTagsByContainerTagProfileBucketRequest>
    | undefined;
};

export type PatchV3ContainerTagsByContainerTagRequest = {
  containerTag: string;
  body: PatchV3ContainerTagsByContainerTagRequestBody;
};

/**
 * Definition of a single profile bucket
 */
export type PatchV3ContainerTagsByContainerTagProfileBucketResponse = {
  /**
   * Stable slug for the bucket, stored on each memory
   */
  key: string;
  /**
   * What belongs in this bucket — used to guide the ingestion classifier.
   */
  description: string;
};

/**
 * Response after updating container tag settings
 */
export type PatchV3ContainerTagsByContainerTagResponse = {
  /**
   * The container tag identifier
   */
  containerTag: string;
  /**
   * Display name for this container tag
   */
  name: string | null;
  /**
   * Custom context prompt for this container tag. Used to provide additional context when processing documents in this container.
   */
  entityContext: string | null;
  /**
   * Per-tag allowlist of filesystem paths that trigger memory generation for mount-ingested documents. Docs whose filepath does not match are ingested as 'superrag' (chunked and searchable, no memory extraction).
   */
  memoryFilesystemPaths: Array<string> | null;
  /**
   * Container-tag-level buckets added on top of the org buckets (add-only)
   */
  profileBuckets: Array<
    PatchV3ContainerTagsByContainerTagProfileBucketResponse
  >;
  /**
   * Last update timestamp
   */
  updatedAt: string;
};

/** @internal */
export type PatchV3ContainerTagsByContainerTagProfileBucketRequest$Outbound = {
  key: string;
  description: string;
};

/** @internal */
export const PatchV3ContainerTagsByContainerTagProfileBucketRequest$outboundSchema:
  z.ZodMiniType<
    PatchV3ContainerTagsByContainerTagProfileBucketRequest$Outbound,
    PatchV3ContainerTagsByContainerTagProfileBucketRequest
  > = z.object({
    key: z.string(),
    description: z._default(z.string(), ""),
  });

export function patchV3ContainerTagsByContainerTagProfileBucketRequestToJSON(
  patchV3ContainerTagsByContainerTagProfileBucketRequest:
    PatchV3ContainerTagsByContainerTagProfileBucketRequest,
): string {
  return JSON.stringify(
    PatchV3ContainerTagsByContainerTagProfileBucketRequest$outboundSchema.parse(
      patchV3ContainerTagsByContainerTagProfileBucketRequest,
    ),
  );
}

/** @internal */
export type PatchV3ContainerTagsByContainerTagRequestBody$Outbound = {
  name?: string | undefined;
  entityContext?: string | null | undefined;
  memoryFilesystemPaths?: Array<string> | null | undefined;
  profileBuckets?:
    | Array<PatchV3ContainerTagsByContainerTagProfileBucketRequest$Outbound>
    | undefined;
};

/** @internal */
export const PatchV3ContainerTagsByContainerTagRequestBody$outboundSchema:
  z.ZodMiniType<
    PatchV3ContainerTagsByContainerTagRequestBody$Outbound,
    PatchV3ContainerTagsByContainerTagRequestBody
  > = z.object({
    name: z.optional(z.string()),
    entityContext: z.optional(z.nullable(z.string())),
    memoryFilesystemPaths: z.optional(z.nullable(z.array(z.string()))),
    profileBuckets: z.optional(
      z.array(z.lazy(() =>
        PatchV3ContainerTagsByContainerTagProfileBucketRequest$outboundSchema
      )),
    ),
  });

export function patchV3ContainerTagsByContainerTagRequestBodyToJSON(
  patchV3ContainerTagsByContainerTagRequestBody:
    PatchV3ContainerTagsByContainerTagRequestBody,
): string {
  return JSON.stringify(
    PatchV3ContainerTagsByContainerTagRequestBody$outboundSchema.parse(
      patchV3ContainerTagsByContainerTagRequestBody,
    ),
  );
}

/** @internal */
export type PatchV3ContainerTagsByContainerTagRequest$Outbound = {
  containerTag: string;
  body: PatchV3ContainerTagsByContainerTagRequestBody$Outbound;
};

/** @internal */
export const PatchV3ContainerTagsByContainerTagRequest$outboundSchema:
  z.ZodMiniType<
    PatchV3ContainerTagsByContainerTagRequest$Outbound,
    PatchV3ContainerTagsByContainerTagRequest
  > = z.object({
    containerTag: z.string(),
    body: z.lazy(() =>
      PatchV3ContainerTagsByContainerTagRequestBody$outboundSchema
    ),
  });

export function patchV3ContainerTagsByContainerTagRequestToJSON(
  patchV3ContainerTagsByContainerTagRequest:
    PatchV3ContainerTagsByContainerTagRequest,
): string {
  return JSON.stringify(
    PatchV3ContainerTagsByContainerTagRequest$outboundSchema.parse(
      patchV3ContainerTagsByContainerTagRequest,
    ),
  );
}

/** @internal */
export const PatchV3ContainerTagsByContainerTagProfileBucketResponse$inboundSchema:
  z.ZodMiniType<
    PatchV3ContainerTagsByContainerTagProfileBucketResponse,
    unknown
  > = z.object({
    key: types.string(),
    description: z._default(types.string(), ""),
  });

export function patchV3ContainerTagsByContainerTagProfileBucketResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  PatchV3ContainerTagsByContainerTagProfileBucketResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PatchV3ContainerTagsByContainerTagProfileBucketResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PatchV3ContainerTagsByContainerTagProfileBucketResponse' from JSON`,
  );
}

/** @internal */
export const PatchV3ContainerTagsByContainerTagResponse$inboundSchema:
  z.ZodMiniType<PatchV3ContainerTagsByContainerTagResponse, unknown> = z.object(
    {
      containerTag: types.string(),
      name: types.nullable(types.string()),
      entityContext: types.nullable(types.string()),
      memoryFilesystemPaths: types.nullable(z.array(types.string())),
      profileBuckets: z.array(z.lazy(() =>
        PatchV3ContainerTagsByContainerTagProfileBucketResponse$inboundSchema
      )),
      updatedAt: types.string(),
    },
  );

export function patchV3ContainerTagsByContainerTagResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  PatchV3ContainerTagsByContainerTagResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PatchV3ContainerTagsByContainerTagResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PatchV3ContainerTagsByContainerTagResponse' from JSON`,
  );
}
