/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ad3522555862
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * What to sync, as ids grouped by kind. GitHub takes repos, Gmail takes labels, Google Drive takes files and folders. Replaces the current selection.
 */
export type SelectionRequest = {
  /**
   * GitHub repository ids
   */
  repos?: Array<string> | undefined;
  /**
   * Gmail label ids
   */
  labels?: Array<string> | undefined;
  /**
   * Google Drive file ids
   */
  files?: Array<string> | undefined;
  /**
   * Google Drive folder ids
   */
  folders?: Array<string> | undefined;
};

export type PatchNsByNamespaceConnectorsByIdRequestBody = {
  /**
   * What to sync, as ids grouped by kind. GitHub takes repos, Gmail takes labels, Google Drive takes files and folders. Replaces the current selection.
   */
  selection?: SelectionRequest | undefined;
  /**
   * Maximum documents this connector imports
   */
  documentLimit?: number | undefined;
};

export type PatchNsByNamespaceConnectorsByIdRequest = {
  /**
   * Namespace identifier. This can be an ID for your user, a project ID, or any other identifier you wish to use to scope documents and memories.
   */
  namespace: string;
  /**
   * Connector identifier returned when the connector was created
   */
  id: string;
  body: PatchNsByNamespaceConnectorsByIdRequestBody;
};

/**
 * External source
 */
export const PatchNsByNamespaceConnectorsByIdProvider = {
  Notion: "notion",
  GoogleDrive: "google-drive",
  Onedrive: "onedrive",
  Gmail: "gmail",
  Github: "github",
  WebCrawler: "web-crawler",
  S3: "s3",
  Granola: "granola",
} as const;
/**
 * External source
 */
export type PatchNsByNamespaceConnectorsByIdProvider = OpenEnum<
  typeof PatchNsByNamespaceConnectorsByIdProvider
>;

export type PatchNsByNamespaceConnectorsByIdCapabilities = {
  /**
   * Supports choosing what to sync via the hosted picker
   */
  selectable: boolean;
  /**
   * Receives change notifications instead of only polling
   */
  webhooks: boolean;
};

export type PatchNsByNamespaceConnectorsByIdConfig = string | number | boolean;

export type PatchNsByNamespaceConnectorsByIdSelectionResponse = {
  id: string;
  name: string;
};

export const PatchNsByNamespaceConnectorsByIdLastSyncStatus = {
  Running: "running",
  Completed: "completed",
  Failed: "failed",
} as const;
export type PatchNsByNamespaceConnectorsByIdLastSyncStatus = OpenEnum<
  typeof PatchNsByNamespaceConnectorsByIdLastSyncStatus
>;

export const PatchNsByNamespaceConnectorsByIdLastSyncErrorCode = {
  AuthExpired: "auth_expired",
  RateLimited: "rate_limited",
  PlanRequired: "plan_required",
  ProviderUnavailable: "provider_unavailable",
  Internal: "internal",
} as const;
export type PatchNsByNamespaceConnectorsByIdLastSyncErrorCode = OpenEnum<
  typeof PatchNsByNamespaceConnectorsByIdLastSyncErrorCode
>;

export type PatchNsByNamespaceConnectorsByIdLastSync = {
  status: PatchNsByNamespaceConnectorsByIdLastSyncStatus;
  errorCode: PatchNsByNamespaceConnectorsByIdLastSyncErrorCode | null;
  /**
   * Customer-safe error message
   */
  error: string | null;
  startedAt: Date;
  completedAt: Date | null;
};

export const PatchNsByNamespaceConnectorsByIdSyncStatus = {
  Running: "running",
  Completed: "completed",
  Failed: "failed",
} as const;
export type PatchNsByNamespaceConnectorsByIdSyncStatus = OpenEnum<
  typeof PatchNsByNamespaceConnectorsByIdSyncStatus
>;

export const PatchNsByNamespaceConnectorsByIdSyncErrorCode = {
  AuthExpired: "auth_expired",
  RateLimited: "rate_limited",
  PlanRequired: "plan_required",
  ProviderUnavailable: "provider_unavailable",
  Internal: "internal",
} as const;
export type PatchNsByNamespaceConnectorsByIdSyncErrorCode = OpenEnum<
  typeof PatchNsByNamespaceConnectorsByIdSyncErrorCode
>;

export const PatchNsByNamespaceConnectorsByIdTrigger = {
  Event: "event",
  Cron: "cron",
  Manual: "manual",
} as const;
export type PatchNsByNamespaceConnectorsByIdTrigger = OpenEnum<
  typeof PatchNsByNamespaceConnectorsByIdTrigger
>;

export type PatchNsByNamespaceConnectorsByIdFailure = {
  documentId: string;
  title: string | null;
  errorCode: string;
  errorMessage: string;
  failedAt: string;
};

export type PatchNsByNamespaceConnectorsByIdSync = {
  status: PatchNsByNamespaceConnectorsByIdSyncStatus;
  errorCode: PatchNsByNamespaceConnectorsByIdSyncErrorCode | null;
  /**
   * Customer-safe error message
   */
  error: string | null;
  startedAt: Date;
  completedAt: Date | null;
  id: string;
  trigger: PatchNsByNamespaceConnectorsByIdTrigger;
  itemsProcessed: number;
  itemsFailed: number;
  /**
   * Failed items, capped. itemsFailed is the true count.
   */
  failures: Array<PatchNsByNamespaceConnectorsByIdFailure>;
};

export type PatchNsByNamespaceConnectorsByIdPicker = {
  /**
   * Send the user here to choose what syncs. Works once, in any browser.
   */
  url: string;
  expiresAt: Date;
};

/**
 * Updated connector
 */
export type PatchNsByNamespaceConnectorsByIdResponse = {
  id: string;
  /**
   * External source
   */
  provider: PatchNsByNamespaceConnectorsByIdProvider;
  /**
   * Namespace the connector syncs into. Null only for connectors created before namespaces were required.
   */
  namespace: string | null;
  /**
   * Account on the provider side, usually an email
   */
  account: string | null;
  capabilities: PatchNsByNamespaceConnectorsByIdCapabilities;
  /**
   * Non-secret setup, such as the S3 bucket, crawler start URL or Notion workspace. Credentials are never returned.
   */
  config: { [k: string]: string | number | boolean } | null;
  /**
   * What syncs, grouped by kind, in the same shape PATCH takes. Null for connectors that sync everything.
   */
  selection: {
    [k: string]: Array<PatchNsByNamespaceConnectorsByIdSelectionResponse>;
  } | null;
  documentLimit: number;
  documentCount: number;
  /**
   * Most recent sync run
   */
  lastSync: PatchNsByNamespaceConnectorsByIdLastSync | null;
  /**
   * When content last finished syncing
   */
  lastSyncedAt: Date | null;
  createdAt: Date;
  /**
   * Present when attach=syncs
   */
  syncs?: Array<PatchNsByNamespaceConnectorsByIdSync> | undefined;
  /**
   * Present when attach=picker. Null for connectors that sync everything.
   */
  picker?: PatchNsByNamespaceConnectorsByIdPicker | null | undefined;
};

/** @internal */
export type SelectionRequest$Outbound = {
  repos?: Array<string> | undefined;
  labels?: Array<string> | undefined;
  files?: Array<string> | undefined;
  folders?: Array<string> | undefined;
};

/** @internal */
export const SelectionRequest$outboundSchema: z.ZodMiniType<
  SelectionRequest$Outbound,
  SelectionRequest
> = z.object({
  repos: z.optional(z.array(z.string())),
  labels: z.optional(z.array(z.string())),
  files: z.optional(z.array(z.string())),
  folders: z.optional(z.array(z.string())),
});

export function selectionRequestToJSON(
  selectionRequest: SelectionRequest,
): string {
  return JSON.stringify(
    SelectionRequest$outboundSchema.parse(selectionRequest),
  );
}

/** @internal */
export type PatchNsByNamespaceConnectorsByIdRequestBody$Outbound = {
  selection?: SelectionRequest$Outbound | undefined;
  documentLimit?: number | undefined;
};

/** @internal */
export const PatchNsByNamespaceConnectorsByIdRequestBody$outboundSchema:
  z.ZodMiniType<
    PatchNsByNamespaceConnectorsByIdRequestBody$Outbound,
    PatchNsByNamespaceConnectorsByIdRequestBody
  > = z.object({
    selection: z.optional(z.lazy(() => SelectionRequest$outboundSchema)),
    documentLimit: z.optional(z.int()),
  });

export function patchNsByNamespaceConnectorsByIdRequestBodyToJSON(
  patchNsByNamespaceConnectorsByIdRequestBody:
    PatchNsByNamespaceConnectorsByIdRequestBody,
): string {
  return JSON.stringify(
    PatchNsByNamespaceConnectorsByIdRequestBody$outboundSchema.parse(
      patchNsByNamespaceConnectorsByIdRequestBody,
    ),
  );
}

/** @internal */
export type PatchNsByNamespaceConnectorsByIdRequest$Outbound = {
  namespace: string;
  id: string;
  body: PatchNsByNamespaceConnectorsByIdRequestBody$Outbound;
};

/** @internal */
export const PatchNsByNamespaceConnectorsByIdRequest$outboundSchema:
  z.ZodMiniType<
    PatchNsByNamespaceConnectorsByIdRequest$Outbound,
    PatchNsByNamespaceConnectorsByIdRequest
  > = z.object({
    namespace: z.string(),
    id: z.string(),
    body: z.lazy(() =>
      PatchNsByNamespaceConnectorsByIdRequestBody$outboundSchema
    ),
  });

export function patchNsByNamespaceConnectorsByIdRequestToJSON(
  patchNsByNamespaceConnectorsByIdRequest:
    PatchNsByNamespaceConnectorsByIdRequest,
): string {
  return JSON.stringify(
    PatchNsByNamespaceConnectorsByIdRequest$outboundSchema.parse(
      patchNsByNamespaceConnectorsByIdRequest,
    ),
  );
}

/** @internal */
export const PatchNsByNamespaceConnectorsByIdProvider$inboundSchema:
  z.ZodMiniType<PatchNsByNamespaceConnectorsByIdProvider, unknown> = openEnums
    .inboundSchema(PatchNsByNamespaceConnectorsByIdProvider);

/** @internal */
export const PatchNsByNamespaceConnectorsByIdCapabilities$inboundSchema:
  z.ZodMiniType<PatchNsByNamespaceConnectorsByIdCapabilities, unknown> = z
    .object({
      selectable: types.boolean(),
      webhooks: types.boolean(),
    });

export function patchNsByNamespaceConnectorsByIdCapabilitiesFromJSON(
  jsonString: string,
): SafeParseResult<
  PatchNsByNamespaceConnectorsByIdCapabilities,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PatchNsByNamespaceConnectorsByIdCapabilities$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PatchNsByNamespaceConnectorsByIdCapabilities' from JSON`,
  );
}

/** @internal */
export const PatchNsByNamespaceConnectorsByIdConfig$inboundSchema:
  z.ZodMiniType<PatchNsByNamespaceConnectorsByIdConfig, unknown> = smartUnion([
    types.string(),
    types.number(),
    types.boolean(),
  ]);

export function patchNsByNamespaceConnectorsByIdConfigFromJSON(
  jsonString: string,
): SafeParseResult<PatchNsByNamespaceConnectorsByIdConfig, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PatchNsByNamespaceConnectorsByIdConfig$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchNsByNamespaceConnectorsByIdConfig' from JSON`,
  );
}

/** @internal */
export const PatchNsByNamespaceConnectorsByIdSelectionResponse$inboundSchema:
  z.ZodMiniType<PatchNsByNamespaceConnectorsByIdSelectionResponse, unknown> = z
    .object({
      id: types.string(),
      name: types.string(),
    });

export function patchNsByNamespaceConnectorsByIdSelectionResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  PatchNsByNamespaceConnectorsByIdSelectionResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PatchNsByNamespaceConnectorsByIdSelectionResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PatchNsByNamespaceConnectorsByIdSelectionResponse' from JSON`,
  );
}

/** @internal */
export const PatchNsByNamespaceConnectorsByIdLastSyncStatus$inboundSchema:
  z.ZodMiniType<PatchNsByNamespaceConnectorsByIdLastSyncStatus, unknown> =
    openEnums.inboundSchema(PatchNsByNamespaceConnectorsByIdLastSyncStatus);

/** @internal */
export const PatchNsByNamespaceConnectorsByIdLastSyncErrorCode$inboundSchema:
  z.ZodMiniType<PatchNsByNamespaceConnectorsByIdLastSyncErrorCode, unknown> =
    openEnums.inboundSchema(PatchNsByNamespaceConnectorsByIdLastSyncErrorCode);

/** @internal */
export const PatchNsByNamespaceConnectorsByIdLastSync$inboundSchema:
  z.ZodMiniType<PatchNsByNamespaceConnectorsByIdLastSync, unknown> = z.object({
    status: PatchNsByNamespaceConnectorsByIdLastSyncStatus$inboundSchema,
    errorCode: types.nullable(
      PatchNsByNamespaceConnectorsByIdLastSyncErrorCode$inboundSchema,
    ),
    error: types.nullable(types.string()),
    startedAt: types.date(),
    completedAt: types.nullable(types.date()),
  });

export function patchNsByNamespaceConnectorsByIdLastSyncFromJSON(
  jsonString: string,
): SafeParseResult<
  PatchNsByNamespaceConnectorsByIdLastSync,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PatchNsByNamespaceConnectorsByIdLastSync$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PatchNsByNamespaceConnectorsByIdLastSync' from JSON`,
  );
}

/** @internal */
export const PatchNsByNamespaceConnectorsByIdSyncStatus$inboundSchema:
  z.ZodMiniType<PatchNsByNamespaceConnectorsByIdSyncStatus, unknown> = openEnums
    .inboundSchema(PatchNsByNamespaceConnectorsByIdSyncStatus);

/** @internal */
export const PatchNsByNamespaceConnectorsByIdSyncErrorCode$inboundSchema:
  z.ZodMiniType<PatchNsByNamespaceConnectorsByIdSyncErrorCode, unknown> =
    openEnums.inboundSchema(PatchNsByNamespaceConnectorsByIdSyncErrorCode);

/** @internal */
export const PatchNsByNamespaceConnectorsByIdTrigger$inboundSchema:
  z.ZodMiniType<PatchNsByNamespaceConnectorsByIdTrigger, unknown> = openEnums
    .inboundSchema(PatchNsByNamespaceConnectorsByIdTrigger);

/** @internal */
export const PatchNsByNamespaceConnectorsByIdFailure$inboundSchema:
  z.ZodMiniType<PatchNsByNamespaceConnectorsByIdFailure, unknown> = z.object({
    documentId: types.string(),
    title: types.nullable(types.string()),
    errorCode: types.string(),
    errorMessage: types.string(),
    failedAt: types.string(),
  });

export function patchNsByNamespaceConnectorsByIdFailureFromJSON(
  jsonString: string,
): SafeParseResult<
  PatchNsByNamespaceConnectorsByIdFailure,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PatchNsByNamespaceConnectorsByIdFailure$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PatchNsByNamespaceConnectorsByIdFailure' from JSON`,
  );
}

/** @internal */
export const PatchNsByNamespaceConnectorsByIdSync$inboundSchema: z.ZodMiniType<
  PatchNsByNamespaceConnectorsByIdSync,
  unknown
> = z.object({
  status: PatchNsByNamespaceConnectorsByIdSyncStatus$inboundSchema,
  errorCode: types.nullable(
    PatchNsByNamespaceConnectorsByIdSyncErrorCode$inboundSchema,
  ),
  error: types.nullable(types.string()),
  startedAt: types.date(),
  completedAt: types.nullable(types.date()),
  id: types.string(),
  trigger: PatchNsByNamespaceConnectorsByIdTrigger$inboundSchema,
  itemsProcessed: types.number(),
  itemsFailed: types.number(),
  failures: z.array(
    z.lazy(() => PatchNsByNamespaceConnectorsByIdFailure$inboundSchema),
  ),
});

export function patchNsByNamespaceConnectorsByIdSyncFromJSON(
  jsonString: string,
): SafeParseResult<PatchNsByNamespaceConnectorsByIdSync, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PatchNsByNamespaceConnectorsByIdSync$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchNsByNamespaceConnectorsByIdSync' from JSON`,
  );
}

/** @internal */
export const PatchNsByNamespaceConnectorsByIdPicker$inboundSchema:
  z.ZodMiniType<PatchNsByNamespaceConnectorsByIdPicker, unknown> = z.object({
    url: types.string(),
    expiresAt: types.date(),
  });

export function patchNsByNamespaceConnectorsByIdPickerFromJSON(
  jsonString: string,
): SafeParseResult<PatchNsByNamespaceConnectorsByIdPicker, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PatchNsByNamespaceConnectorsByIdPicker$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchNsByNamespaceConnectorsByIdPicker' from JSON`,
  );
}

/** @internal */
export const PatchNsByNamespaceConnectorsByIdResponse$inboundSchema:
  z.ZodMiniType<PatchNsByNamespaceConnectorsByIdResponse, unknown> = z.object({
    id: types.string(),
    provider: PatchNsByNamespaceConnectorsByIdProvider$inboundSchema,
    namespace: types.nullable(types.string()),
    account: types.nullable(types.string()),
    capabilities: z.lazy(() =>
      PatchNsByNamespaceConnectorsByIdCapabilities$inboundSchema
    ),
    config: types.nullable(
      z.record(
        z.string(),
        smartUnion([types.string(), types.number(), types.boolean()]),
      ),
    ),
    selection: types.nullable(
      z.record(
        z.string(),
        z.array(
          z.lazy(() =>
            PatchNsByNamespaceConnectorsByIdSelectionResponse$inboundSchema
          ),
        ),
      ),
    ),
    documentLimit: types.number(),
    documentCount: types.number(),
    lastSync: types.nullable(
      z.lazy(() => PatchNsByNamespaceConnectorsByIdLastSync$inboundSchema),
    ),
    lastSyncedAt: types.nullable(types.date()),
    createdAt: types.date(),
    syncs: types.optional(
      z.array(z.lazy(() => PatchNsByNamespaceConnectorsByIdSync$inboundSchema)),
    ),
    picker: z.optional(
      z.nullable(z.lazy(() =>
        PatchNsByNamespaceConnectorsByIdPicker$inboundSchema
      )),
    ),
  });

export function patchNsByNamespaceConnectorsByIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  PatchNsByNamespaceConnectorsByIdResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PatchNsByNamespaceConnectorsByIdResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PatchNsByNamespaceConnectorsByIdResponse' from JSON`,
  );
}
