/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0d50fd020a50
 */

import * as z from "zod/v4-mini";

export type PatchV3SettingsSecurityRequest = {
  requireTwoFactor: boolean;
};

/** @internal */
export type PatchV3SettingsSecurityRequest$Outbound = {
  requireTwoFactor: boolean;
};

/** @internal */
export const PatchV3SettingsSecurityRequest$outboundSchema: z.ZodMiniType<
  PatchV3SettingsSecurityRequest$Outbound,
  PatchV3SettingsSecurityRequest
> = z.object({
  requireTwoFactor: z.boolean(),
});

export function patchV3SettingsSecurityRequestToJSON(
  patchV3SettingsSecurityRequest: PatchV3SettingsSecurityRequest,
): string {
  return JSON.stringify(
    PatchV3SettingsSecurityRequest$outboundSchema.parse(
      patchV3SettingsSecurityRequest,
    ),
  );
}
