/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 6ba409283d60
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Processing pipeline. "memory" builds durable learned context; "superrag" optimizes the document for retrieval without generating memories.
 */
export const PatchNsByNamespaceDocumentByIdTaskType = {
  Memory: "memory",
  Superrag: "superrag",
} as const;
/**
 * Processing pipeline. "memory" builds durable learned context; "superrag" optimizes the document for retrieval without generating memories.
 */
export type PatchNsByNamespaceDocumentByIdTaskType = ClosedEnum<
  typeof PatchNsByNamespaceDocumentByIdTaskType
>;

/**
 * Processing mode. "dynamic" (default) groups related documents so memories form from coherent context. "instant" processes each document independently right away and bills one extra operation per document.
 */
export const PatchNsByNamespaceDocumentByIdDreaming = {
  Dynamic: "dynamic",
  Instant: "instant",
} as const;
/**
 * Processing mode. "dynamic" (default) groups related documents so memories form from coherent context. "instant" processes each document independently right away and bills one extra operation per document.
 */
export type PatchNsByNamespaceDocumentByIdDreaming = ClosedEnum<
  typeof PatchNsByNamespaceDocumentByIdDreaming
>;

export type PatchNsByNamespaceDocumentByIdMetadata =
  | string
  | number
  | boolean
  | Array<string>;

export type PatchNsByNamespaceDocumentByIdGroup =
  | string
  | number
  | boolean
  | Array<string>;

export type PatchNsByNamespaceDocumentByIdRequestBody = {
  /**
   * The content to process. This may be plaintext or a URL to supported rich content.
   */
  content?: string | undefined;
  /**
   * Context used to guide memory extraction within this namespace. Max 1500 characters.
   */
  supportingContext?: string | undefined;
  /**
   * Arbitrary metadata attached to the document and derived data
   */
  metadata?:
    | { [k: string]: string | number | boolean | Array<string> }
    | undefined;
  /**
   * Metadata values that isolate related context within the namespace
   */
  group?:
    | { [k: string]: string | number | boolean | Array<string> }
    | undefined;
  /**
   * When the source content is from, in ISO 8601 format
   */
  date?: string | undefined;
};

export type PatchNsByNamespaceDocumentByIdRequest = {
  /**
   * The isolated namespace. This can be an ID for your user, a project ID, or any other identifier you wish to use to scope documents.
   */
  namespace: string;
  /**
   * The public document ID
   */
  id: string;
  /**
   * Processing pipeline. "memory" builds durable learned context; "superrag" optimizes the document for retrieval without generating memories.
   */
  taskType?: PatchNsByNamespaceDocumentByIdTaskType | undefined;
  /**
   * Processing mode. "dynamic" (default) groups related documents so memories form from coherent context. "instant" processes each document independently right away and bills one extra operation per document.
   */
  dreaming?: PatchNsByNamespaceDocumentByIdDreaming | undefined;
  body: PatchNsByNamespaceDocumentByIdRequestBody;
};

/**
 * Document updated successfully
 */
export type PatchNsByNamespaceDocumentByIdResponse = {
  /**
   * Unique identifier of the document
   */
  id: string;
  /**
   * Status of the document
   */
  status: string;
};

/** @internal */
export const PatchNsByNamespaceDocumentByIdTaskType$outboundSchema:
  z.ZodMiniEnum<typeof PatchNsByNamespaceDocumentByIdTaskType> = z.enum(
    PatchNsByNamespaceDocumentByIdTaskType,
  );

/** @internal */
export const PatchNsByNamespaceDocumentByIdDreaming$outboundSchema:
  z.ZodMiniEnum<typeof PatchNsByNamespaceDocumentByIdDreaming> = z.enum(
    PatchNsByNamespaceDocumentByIdDreaming,
  );

/** @internal */
export type PatchNsByNamespaceDocumentByIdMetadata$Outbound =
  | string
  | number
  | boolean
  | Array<string>;

/** @internal */
export const PatchNsByNamespaceDocumentByIdMetadata$outboundSchema:
  z.ZodMiniType<
    PatchNsByNamespaceDocumentByIdMetadata$Outbound,
    PatchNsByNamespaceDocumentByIdMetadata
  > = smartUnion([z.string(), z.number(), z.boolean(), z.array(z.string())]);

export function patchNsByNamespaceDocumentByIdMetadataToJSON(
  patchNsByNamespaceDocumentByIdMetadata:
    PatchNsByNamespaceDocumentByIdMetadata,
): string {
  return JSON.stringify(
    PatchNsByNamespaceDocumentByIdMetadata$outboundSchema.parse(
      patchNsByNamespaceDocumentByIdMetadata,
    ),
  );
}

/** @internal */
export type PatchNsByNamespaceDocumentByIdGroup$Outbound =
  | string
  | number
  | boolean
  | Array<string>;

/** @internal */
export const PatchNsByNamespaceDocumentByIdGroup$outboundSchema: z.ZodMiniType<
  PatchNsByNamespaceDocumentByIdGroup$Outbound,
  PatchNsByNamespaceDocumentByIdGroup
> = smartUnion([z.string(), z.number(), z.boolean(), z.array(z.string())]);

export function patchNsByNamespaceDocumentByIdGroupToJSON(
  patchNsByNamespaceDocumentByIdGroup: PatchNsByNamespaceDocumentByIdGroup,
): string {
  return JSON.stringify(
    PatchNsByNamespaceDocumentByIdGroup$outboundSchema.parse(
      patchNsByNamespaceDocumentByIdGroup,
    ),
  );
}

/** @internal */
export type PatchNsByNamespaceDocumentByIdRequestBody$Outbound = {
  content?: string | undefined;
  supportingContext?: string | undefined;
  metadata?:
    | { [k: string]: string | number | boolean | Array<string> }
    | undefined;
  group?:
    | { [k: string]: string | number | boolean | Array<string> }
    | undefined;
  date?: string | undefined;
};

/** @internal */
export const PatchNsByNamespaceDocumentByIdRequestBody$outboundSchema:
  z.ZodMiniType<
    PatchNsByNamespaceDocumentByIdRequestBody$Outbound,
    PatchNsByNamespaceDocumentByIdRequestBody
  > = z.object({
    content: z.optional(z.string()),
    supportingContext: z.optional(z.string()),
    metadata: z.optional(
      z.record(
        z.string(),
        smartUnion([z.string(), z.number(), z.boolean(), z.array(z.string())]),
      ),
    ),
    group: z.optional(
      z.record(
        z.string(),
        smartUnion([z.string(), z.number(), z.boolean(), z.array(z.string())]),
      ),
    ),
    date: z.optional(z.string()),
  });

export function patchNsByNamespaceDocumentByIdRequestBodyToJSON(
  patchNsByNamespaceDocumentByIdRequestBody:
    PatchNsByNamespaceDocumentByIdRequestBody,
): string {
  return JSON.stringify(
    PatchNsByNamespaceDocumentByIdRequestBody$outboundSchema.parse(
      patchNsByNamespaceDocumentByIdRequestBody,
    ),
  );
}

/** @internal */
export type PatchNsByNamespaceDocumentByIdRequest$Outbound = {
  namespace: string;
  id: string;
  taskType?: string | undefined;
  dreaming?: string | undefined;
  body: PatchNsByNamespaceDocumentByIdRequestBody$Outbound;
};

/** @internal */
export const PatchNsByNamespaceDocumentByIdRequest$outboundSchema:
  z.ZodMiniType<
    PatchNsByNamespaceDocumentByIdRequest$Outbound,
    PatchNsByNamespaceDocumentByIdRequest
  > = z.object({
    namespace: z.string(),
    id: z.string(),
    taskType: z.optional(PatchNsByNamespaceDocumentByIdTaskType$outboundSchema),
    dreaming: z.optional(PatchNsByNamespaceDocumentByIdDreaming$outboundSchema),
    body: z.lazy(() =>
      PatchNsByNamespaceDocumentByIdRequestBody$outboundSchema
    ),
  });

export function patchNsByNamespaceDocumentByIdRequestToJSON(
  patchNsByNamespaceDocumentByIdRequest: PatchNsByNamespaceDocumentByIdRequest,
): string {
  return JSON.stringify(
    PatchNsByNamespaceDocumentByIdRequest$outboundSchema.parse(
      patchNsByNamespaceDocumentByIdRequest,
    ),
  );
}

/** @internal */
export const PatchNsByNamespaceDocumentByIdResponse$inboundSchema:
  z.ZodMiniType<PatchNsByNamespaceDocumentByIdResponse, unknown> = z.object({
    id: types.string(),
    status: types.string(),
  });

export function patchNsByNamespaceDocumentByIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<PatchNsByNamespaceDocumentByIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PatchNsByNamespaceDocumentByIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchNsByNamespaceDocumentByIdResponse' from JSON`,
  );
}
