/*
 * Generated by scripts/surface/generate.ts from fern/openapi.json. DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as types from "../../types/primitives.js";

/**
 * External source
 */
export const PatchNsByNamespaceConnectorsByIdResponseProvider = {
  Notion: "notion",
  GoogleDrive: "google-drive",
  Onedrive: "onedrive",
  Gmail: "gmail",
  Github: "github",
  WebCrawler: "web-crawler",
  S3: "s3",
  Granola: "granola",
} as const;
/**
 * External source
 */
export type PatchNsByNamespaceConnectorsByIdResponseProvider = OpenEnum<typeof PatchNsByNamespaceConnectorsByIdResponseProvider>;

/** @internal */
export const PatchNsByNamespaceConnectorsByIdResponseProvider$inboundSchema: z.ZodMiniType<PatchNsByNamespaceConnectorsByIdResponseProvider, unknown> = openEnums.inboundSchema(PatchNsByNamespaceConnectorsByIdResponseProvider);

/**
 * pending_authorization until the user finishes the provider login at authUrl; DELETE cancels it. Pending connectors are not listed.
 */
export const PatchNsByNamespaceConnectorsByIdResponseStatus = {
  PendingAuthorization: "pending_authorization",
  Active: "active",
} as const;
/**
 * pending_authorization until the user finishes the provider login at authUrl; DELETE cancels it. Pending connectors are not listed.
 */
export type PatchNsByNamespaceConnectorsByIdResponseStatus = OpenEnum<typeof PatchNsByNamespaceConnectorsByIdResponseStatus>;

/** @internal */
export const PatchNsByNamespaceConnectorsByIdResponseStatus$inboundSchema: z.ZodMiniType<PatchNsByNamespaceConnectorsByIdResponseStatus, unknown> = openEnums.inboundSchema(PatchNsByNamespaceConnectorsByIdResponseStatus);

export const PatchNsByNamespaceConnectorsByIdResponseLastSyncStatus = {
  Running: "running",
  Completed: "completed",
  Failed: "failed",
} as const;
export type PatchNsByNamespaceConnectorsByIdResponseLastSyncStatus = OpenEnum<typeof PatchNsByNamespaceConnectorsByIdResponseLastSyncStatus>;

/** @internal */
export const PatchNsByNamespaceConnectorsByIdResponseLastSyncStatus$inboundSchema: z.ZodMiniType<PatchNsByNamespaceConnectorsByIdResponseLastSyncStatus, unknown> = openEnums.inboundSchema(PatchNsByNamespaceConnectorsByIdResponseLastSyncStatus);

export const PatchNsByNamespaceConnectorsByIdResponseLastSyncErrorCode = {
  AuthExpired: "auth_expired",
  RateLimited: "rate_limited",
  PlanRequired: "plan_required",
  ProviderUnavailable: "provider_unavailable",
  Internal: "internal",
} as const;
export type PatchNsByNamespaceConnectorsByIdResponseLastSyncErrorCode = OpenEnum<typeof PatchNsByNamespaceConnectorsByIdResponseLastSyncErrorCode>;

/** @internal */
export const PatchNsByNamespaceConnectorsByIdResponseLastSyncErrorCode$inboundSchema: z.ZodMiniType<PatchNsByNamespaceConnectorsByIdResponseLastSyncErrorCode, unknown> = openEnums.inboundSchema(PatchNsByNamespaceConnectorsByIdResponseLastSyncErrorCode);

export const PatchNsByNamespaceConnectorsByIdResponseSyncsStatus = {
  Running: "running",
  Completed: "completed",
  Failed: "failed",
} as const;
export type PatchNsByNamespaceConnectorsByIdResponseSyncsStatus = OpenEnum<typeof PatchNsByNamespaceConnectorsByIdResponseSyncsStatus>;

/** @internal */
export const PatchNsByNamespaceConnectorsByIdResponseSyncsStatus$inboundSchema: z.ZodMiniType<PatchNsByNamespaceConnectorsByIdResponseSyncsStatus, unknown> = openEnums.inboundSchema(PatchNsByNamespaceConnectorsByIdResponseSyncsStatus);

export const PatchNsByNamespaceConnectorsByIdResponseSyncsErrorCode = {
  AuthExpired: "auth_expired",
  RateLimited: "rate_limited",
  PlanRequired: "plan_required",
  ProviderUnavailable: "provider_unavailable",
  Internal: "internal",
} as const;
export type PatchNsByNamespaceConnectorsByIdResponseSyncsErrorCode = OpenEnum<typeof PatchNsByNamespaceConnectorsByIdResponseSyncsErrorCode>;

/** @internal */
export const PatchNsByNamespaceConnectorsByIdResponseSyncsErrorCode$inboundSchema: z.ZodMiniType<PatchNsByNamespaceConnectorsByIdResponseSyncsErrorCode, unknown> = openEnums.inboundSchema(PatchNsByNamespaceConnectorsByIdResponseSyncsErrorCode);

export const PatchNsByNamespaceConnectorsByIdResponseSyncsTrigger = {
  Event: "event",
  Cron: "cron",
  Manual: "manual",
} as const;
export type PatchNsByNamespaceConnectorsByIdResponseSyncsTrigger = OpenEnum<typeof PatchNsByNamespaceConnectorsByIdResponseSyncsTrigger>;

/** @internal */
export const PatchNsByNamespaceConnectorsByIdResponseSyncsTrigger$inboundSchema: z.ZodMiniType<PatchNsByNamespaceConnectorsByIdResponseSyncsTrigger, unknown> = openEnums.inboundSchema(PatchNsByNamespaceConnectorsByIdResponseSyncsTrigger);

export type PatchNsByNamespaceConnectorsByIdRequestBody = {
  /**
   * What to sync, as ids grouped by kind. GitHub takes repos, Gmail takes labels, Google Drive takes files and folders. Replaces the current selection.
   */
  selection?: PatchNsByNamespaceConnectorsByIdRequestBodySelection | undefined;
  /**
   * Maximum documents this connector imports
   */
  documentLimit?: number | undefined;
};

/** @internal */
export type PatchNsByNamespaceConnectorsByIdRequestBody$Outbound = {
  /**
   * What to sync, as ids grouped by kind. GitHub takes repos, Gmail takes labels, Google Drive takes files and folders. Replaces the current selection.
   */
  selection?: PatchNsByNamespaceConnectorsByIdRequestBodySelection$Outbound | undefined;
  /**
   * Maximum documents this connector imports
   */
  documentLimit?: number | undefined;
};

/** @internal */
export const PatchNsByNamespaceConnectorsByIdRequestBody$outboundSchema: z.ZodMiniType<PatchNsByNamespaceConnectorsByIdRequestBody$Outbound, PatchNsByNamespaceConnectorsByIdRequestBody> = z.object({
  selection: z.optional(z.lazy(() => PatchNsByNamespaceConnectorsByIdRequestBodySelection$outboundSchema)),
  documentLimit: z.optional(z.int()),
});

export function patchNsByNamespaceConnectorsByIdRequestBodyToJSON(
  patchNsByNamespaceConnectorsByIdRequestBody: PatchNsByNamespaceConnectorsByIdRequestBody,
): string {
  return JSON.stringify(PatchNsByNamespaceConnectorsByIdRequestBody$outboundSchema.parse(patchNsByNamespaceConnectorsByIdRequestBody));
}

/**
 * What to sync, as ids grouped by kind. GitHub takes repos, Gmail takes labels, Google Drive takes files and folders. Replaces the current selection.
 */
export type PatchNsByNamespaceConnectorsByIdRequestBodySelection = {
  /**
   * GitHub repository ids
   */
  repos?: Array<string> | undefined;
  /**
   * Gmail label ids
   */
  labels?: Array<string> | undefined;
  /**
   * Google Drive file ids
   */
  files?: Array<string> | undefined;
  /**
   * Google Drive folder ids
   */
  folders?: Array<string> | undefined;
};

/** @internal */
export type PatchNsByNamespaceConnectorsByIdRequestBodySelection$Outbound = {
  /**
   * GitHub repository ids
   */
  repos?: Array<string> | undefined;
  /**
   * Gmail label ids
   */
  labels?: Array<string> | undefined;
  /**
   * Google Drive file ids
   */
  files?: Array<string> | undefined;
  /**
   * Google Drive folder ids
   */
  folders?: Array<string> | undefined;
};

/** @internal */
export const PatchNsByNamespaceConnectorsByIdRequestBodySelection$outboundSchema: z.ZodMiniType<PatchNsByNamespaceConnectorsByIdRequestBodySelection$Outbound, PatchNsByNamespaceConnectorsByIdRequestBodySelection> = z.object({
  repos: z.optional(z.array(z.string())),
  labels: z.optional(z.array(z.string())),
  files: z.optional(z.array(z.string())),
  folders: z.optional(z.array(z.string())),
});

export function patchNsByNamespaceConnectorsByIdRequestBodySelectionToJSON(
  patchNsByNamespaceConnectorsByIdRequestBodySelection: PatchNsByNamespaceConnectorsByIdRequestBodySelection,
): string {
  return JSON.stringify(PatchNsByNamespaceConnectorsByIdRequestBodySelection$outboundSchema.parse(patchNsByNamespaceConnectorsByIdRequestBodySelection));
}

export type PatchNsByNamespaceConnectorsByIdRequest = {
  namespace: string;
  id: string;
  body: PatchNsByNamespaceConnectorsByIdRequestBody;
};

/** @internal */
export type PatchNsByNamespaceConnectorsByIdRequest$Outbound = {
  namespace: string;
  id: string;
  body: PatchNsByNamespaceConnectorsByIdRequestBody$Outbound;
};

/** @internal */
export const PatchNsByNamespaceConnectorsByIdRequest$outboundSchema: z.ZodMiniType<PatchNsByNamespaceConnectorsByIdRequest$Outbound, PatchNsByNamespaceConnectorsByIdRequest> = z.object({
  namespace: z.string(),
  id: z.string(),
  body: z.lazy(() => PatchNsByNamespaceConnectorsByIdRequestBody$outboundSchema),
});

export function patchNsByNamespaceConnectorsByIdRequestToJSON(
  patchNsByNamespaceConnectorsByIdRequest: PatchNsByNamespaceConnectorsByIdRequest,
): string {
  return JSON.stringify(PatchNsByNamespaceConnectorsByIdRequest$outboundSchema.parse(patchNsByNamespaceConnectorsByIdRequest));
}

export type PatchNsByNamespaceConnectorsByIdResponse = {
  id: string;
  /**
   * External source
   */
  provider: PatchNsByNamespaceConnectorsByIdResponseProvider;
  /**
   * pending_authorization until the user finishes the provider login at authUrl; DELETE cancels it. Pending connectors are not listed.
   */
  status: PatchNsByNamespaceConnectorsByIdResponseStatus;
  /**
   * Present while pending, when the caller can create connectors in this namespace: where to send the user to authorize
   */
  authUrl?: string | undefined;
  /**
   * Present while pending: when authUrl stops working
   */
  authUrlExpiresAt?: Date | undefined;
  /**
   * Namespace the connector syncs into. Null only for connectors created before namespaces were required.
   */
  namespace: string | null;
  /**
   * Account on the provider side, usually an email
   */
  account: string | null;
  capabilities: PatchNsByNamespaceConnectorsByIdResponseCapabilities;
  /**
   * Non-secret setup, such as the S3 bucket, crawler start URL or Notion workspace. Credentials are never returned.
   */
  config: { [k: string]: string | number | boolean } | null;
  /**
   * What syncs, grouped by kind, in the same shape PATCH takes. Null for connectors that sync everything.
   */
  selection: { [k: string]: Array<PatchNsByNamespaceConnectorsByIdResponseSelection> } | null;
  documentLimit: number;
  documentCount: number;
  /**
   * Most recent sync run
   */
  lastSync: PatchNsByNamespaceConnectorsByIdResponseLastSync | null;
  /**
   * When content last finished syncing
   */
  lastSyncedAt: Date | null;
  createdAt: Date;
  /**
   * Present when attach=syncs
   */
  syncs?: Array<PatchNsByNamespaceConnectorsByIdResponseSyncs> | undefined;
  /**
   * Present when attach=picker. Null for connectors that sync everything.
   */
  picker?: PatchNsByNamespaceConnectorsByIdResponsePicker | null | undefined;
};

/** @internal */
export const PatchNsByNamespaceConnectorsByIdResponse$inboundSchema: z.ZodMiniType<PatchNsByNamespaceConnectorsByIdResponse, unknown> = z.object({
  id: types.string(),
  provider: PatchNsByNamespaceConnectorsByIdResponseProvider$inboundSchema,
  status: PatchNsByNamespaceConnectorsByIdResponseStatus$inboundSchema,
  authUrl: types.optional(types.string()),
  authUrlExpiresAt: types.optional(types.date()),
  namespace: types.nullable(types.string()),
  account: types.nullable(types.string()),
  capabilities: z.lazy(() => PatchNsByNamespaceConnectorsByIdResponseCapabilities$inboundSchema),
  config: types.nullable(z.record(z.string(), smartUnion([types.string(), types.number(), types.boolean()]))),
  selection: types.nullable(z.record(z.string(), z.array(z.lazy(() => PatchNsByNamespaceConnectorsByIdResponseSelection$inboundSchema)))),
  documentLimit: types.number(),
  documentCount: types.number(),
  lastSync: types.nullable(z.lazy(() => PatchNsByNamespaceConnectorsByIdResponseLastSync$inboundSchema)),
  lastSyncedAt: types.nullable(types.date()),
  createdAt: types.date(),
  syncs: types.optional(z.array(z.lazy(() => PatchNsByNamespaceConnectorsByIdResponseSyncs$inboundSchema))),
  picker: z.optional(z.nullable(z.lazy(() => PatchNsByNamespaceConnectorsByIdResponsePicker$inboundSchema))),
});

export function patchNsByNamespaceConnectorsByIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<PatchNsByNamespaceConnectorsByIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchNsByNamespaceConnectorsByIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchNsByNamespaceConnectorsByIdResponse' from JSON`,
  );
}

export type PatchNsByNamespaceConnectorsByIdResponseCapabilities = {
  /**
   * Supports choosing what to sync via the hosted picker
   */
  selectable: boolean;
  /**
   * Receives change notifications instead of only polling
   */
  webhooks: boolean;
};

/** @internal */
export const PatchNsByNamespaceConnectorsByIdResponseCapabilities$inboundSchema: z.ZodMiniType<PatchNsByNamespaceConnectorsByIdResponseCapabilities, unknown> = z.object({
  selectable: types.boolean(),
  webhooks: types.boolean(),
});

export function patchNsByNamespaceConnectorsByIdResponseCapabilitiesFromJSON(
  jsonString: string,
): SafeParseResult<PatchNsByNamespaceConnectorsByIdResponseCapabilities, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchNsByNamespaceConnectorsByIdResponseCapabilities$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchNsByNamespaceConnectorsByIdResponseCapabilities' from JSON`,
  );
}

export type PatchNsByNamespaceConnectorsByIdResponseConfig =
  | string
  | number
  | boolean
;

/** @internal */
export const PatchNsByNamespaceConnectorsByIdResponseConfig$inboundSchema: z.ZodMiniType<PatchNsByNamespaceConnectorsByIdResponseConfig, unknown> = smartUnion([
  types.string(),
  types.number(),
  types.boolean(),
]);

export function patchNsByNamespaceConnectorsByIdResponseConfigFromJSON(
  jsonString: string,
): SafeParseResult<PatchNsByNamespaceConnectorsByIdResponseConfig, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchNsByNamespaceConnectorsByIdResponseConfig$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchNsByNamespaceConnectorsByIdResponseConfig' from JSON`,
  );
}

export type PatchNsByNamespaceConnectorsByIdResponseSelection = {
  id: string;
  name: string;
};

/** @internal */
export const PatchNsByNamespaceConnectorsByIdResponseSelection$inboundSchema: z.ZodMiniType<PatchNsByNamespaceConnectorsByIdResponseSelection, unknown> = z.object({
  id: types.string(),
  name: types.string(),
});

export function patchNsByNamespaceConnectorsByIdResponseSelectionFromJSON(
  jsonString: string,
): SafeParseResult<PatchNsByNamespaceConnectorsByIdResponseSelection, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchNsByNamespaceConnectorsByIdResponseSelection$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchNsByNamespaceConnectorsByIdResponseSelection' from JSON`,
  );
}

export type PatchNsByNamespaceConnectorsByIdResponseLastSync = {
  status: PatchNsByNamespaceConnectorsByIdResponseLastSyncStatus;
  errorCode: PatchNsByNamespaceConnectorsByIdResponseLastSyncErrorCode | null;
  /**
   * Customer-safe error message
   */
  error: string | null;
  startedAt: Date;
  completedAt: Date | null;
};

/** @internal */
export const PatchNsByNamespaceConnectorsByIdResponseLastSync$inboundSchema: z.ZodMiniType<PatchNsByNamespaceConnectorsByIdResponseLastSync, unknown> = z.object({
  status: PatchNsByNamespaceConnectorsByIdResponseLastSyncStatus$inboundSchema,
  errorCode: types.nullable(PatchNsByNamespaceConnectorsByIdResponseLastSyncErrorCode$inboundSchema),
  error: types.nullable(types.string()),
  startedAt: types.date(),
  completedAt: types.nullable(types.date()),
});

export function patchNsByNamespaceConnectorsByIdResponseLastSyncFromJSON(
  jsonString: string,
): SafeParseResult<PatchNsByNamespaceConnectorsByIdResponseLastSync, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchNsByNamespaceConnectorsByIdResponseLastSync$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchNsByNamespaceConnectorsByIdResponseLastSync' from JSON`,
  );
}

export type PatchNsByNamespaceConnectorsByIdResponseSyncs = {
  status: PatchNsByNamespaceConnectorsByIdResponseSyncsStatus;
  errorCode: PatchNsByNamespaceConnectorsByIdResponseSyncsErrorCode | null;
  /**
   * Customer-safe error message
   */
  error: string | null;
  startedAt: Date;
  completedAt: Date | null;
  id: string;
  trigger: PatchNsByNamespaceConnectorsByIdResponseSyncsTrigger;
  itemsProcessed: number;
  itemsFailed: number;
  /**
   * Failed items, capped. itemsFailed is the true count.
   */
  failures: Array<PatchNsByNamespaceConnectorsByIdResponseSyncsFailures>;
};

/** @internal */
export const PatchNsByNamespaceConnectorsByIdResponseSyncs$inboundSchema: z.ZodMiniType<PatchNsByNamespaceConnectorsByIdResponseSyncs, unknown> = z.object({
  status: PatchNsByNamespaceConnectorsByIdResponseSyncsStatus$inboundSchema,
  errorCode: types.nullable(PatchNsByNamespaceConnectorsByIdResponseSyncsErrorCode$inboundSchema),
  error: types.nullable(types.string()),
  startedAt: types.date(),
  completedAt: types.nullable(types.date()),
  id: types.string(),
  trigger: PatchNsByNamespaceConnectorsByIdResponseSyncsTrigger$inboundSchema,
  itemsProcessed: types.number(),
  itemsFailed: types.number(),
  failures: z.array(z.lazy(() => PatchNsByNamespaceConnectorsByIdResponseSyncsFailures$inboundSchema)),
});

export function patchNsByNamespaceConnectorsByIdResponseSyncsFromJSON(
  jsonString: string,
): SafeParseResult<PatchNsByNamespaceConnectorsByIdResponseSyncs, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchNsByNamespaceConnectorsByIdResponseSyncs$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchNsByNamespaceConnectorsByIdResponseSyncs' from JSON`,
  );
}

export type PatchNsByNamespaceConnectorsByIdResponseSyncsFailures = {
  documentId: string;
  title: string | null;
  errorCode: string;
  errorMessage: string;
  failedAt: string;
};

/** @internal */
export const PatchNsByNamespaceConnectorsByIdResponseSyncsFailures$inboundSchema: z.ZodMiniType<PatchNsByNamespaceConnectorsByIdResponseSyncsFailures, unknown> = z.object({
  documentId: types.string(),
  title: types.nullable(types.string()),
  errorCode: types.string(),
  errorMessage: types.string(),
  failedAt: types.string(),
});

export function patchNsByNamespaceConnectorsByIdResponseSyncsFailuresFromJSON(
  jsonString: string,
): SafeParseResult<PatchNsByNamespaceConnectorsByIdResponseSyncsFailures, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchNsByNamespaceConnectorsByIdResponseSyncsFailures$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchNsByNamespaceConnectorsByIdResponseSyncsFailures' from JSON`,
  );
}

export type PatchNsByNamespaceConnectorsByIdResponsePicker = {
  /**
   * Send the user here to choose what syncs. Works once, in any browser.
   */
  url: string;
  expiresAt: Date;
};

/** @internal */
export const PatchNsByNamespaceConnectorsByIdResponsePicker$inboundSchema: z.ZodMiniType<PatchNsByNamespaceConnectorsByIdResponsePicker, unknown> = z.object({
  url: types.string(),
  expiresAt: types.date(),
});

export function patchNsByNamespaceConnectorsByIdResponsePickerFromJSON(
  jsonString: string,
): SafeParseResult<PatchNsByNamespaceConnectorsByIdResponsePicker, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchNsByNamespaceConnectorsByIdResponsePicker$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchNsByNamespaceConnectorsByIdResponsePicker' from JSON`,
  );
}
