/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 38b5508a6720
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import { smartUnion } from "../../types/smart-union.js";

export const Role = {
  User: "user",
  Assistant: "assistant",
  System: "system",
  Tool: "tool",
} as const;
export type Role = ClosedEnum<typeof Role>;

export type ImageUrl = {
  url: string;
};

export type ContentImageURL = {
  type: "image_url";
  imageUrl: ImageUrl;
};

export type ContentText = {
  type: "text";
  text: string;
};

export type ContentUnion2 = ContentText | ContentImageURL;

export type ContentUnion1 = string | Array<ContentText | ContentImageURL>;

export type Message = {
  role: Role;
  content: string | Array<ContentText | ContentImageURL>;
  name?: string | undefined;
  toolCalls?: Array<any> | undefined;
  toolCallId?: string | undefined;
};

export type PostV4ConversationsMetadata = string | number | boolean;

export type PostV4ConversationsRequest = {
  conversationId: string;
  messages: Array<Message>;
  containerTags?: Array<string> | undefined;
  metadata?: { [k: string]: string | number | boolean } | undefined;
};

/** @internal */
export const Role$outboundSchema: z.ZodMiniEnum<typeof Role> = z.enum(Role);

/** @internal */
export type ImageUrl$Outbound = {
  url: string;
};

/** @internal */
export const ImageUrl$outboundSchema: z.ZodMiniType<
  ImageUrl$Outbound,
  ImageUrl
> = z.object({
  url: z.string(),
});

export function imageUrlToJSON(imageUrl: ImageUrl): string {
  return JSON.stringify(ImageUrl$outboundSchema.parse(imageUrl));
}

/** @internal */
export type ContentImageURL$Outbound = {
  type: "image_url";
  imageUrl: ImageUrl$Outbound;
};

/** @internal */
export const ContentImageURL$outboundSchema: z.ZodMiniType<
  ContentImageURL$Outbound,
  ContentImageURL
> = z.object({
  type: z.literal("image_url"),
  imageUrl: z.lazy(() => ImageUrl$outboundSchema),
});

export function contentImageURLToJSON(
  contentImageURL: ContentImageURL,
): string {
  return JSON.stringify(ContentImageURL$outboundSchema.parse(contentImageURL));
}

/** @internal */
export type ContentText$Outbound = {
  type: "text";
  text: string;
};

/** @internal */
export const ContentText$outboundSchema: z.ZodMiniType<
  ContentText$Outbound,
  ContentText
> = z.object({
  type: z.literal("text"),
  text: z.string(),
});

export function contentTextToJSON(contentText: ContentText): string {
  return JSON.stringify(ContentText$outboundSchema.parse(contentText));
}

/** @internal */
export type ContentUnion2$Outbound =
  | ContentText$Outbound
  | ContentImageURL$Outbound;

/** @internal */
export const ContentUnion2$outboundSchema: z.ZodMiniType<
  ContentUnion2$Outbound,
  ContentUnion2
> = z.union([
  z.lazy(() => ContentText$outboundSchema),
  z.lazy(() => ContentImageURL$outboundSchema),
]);

export function contentUnion2ToJSON(contentUnion2: ContentUnion2): string {
  return JSON.stringify(ContentUnion2$outboundSchema.parse(contentUnion2));
}

/** @internal */
export type ContentUnion1$Outbound =
  | string
  | Array<ContentText$Outbound | ContentImageURL$Outbound>;

/** @internal */
export const ContentUnion1$outboundSchema: z.ZodMiniType<
  ContentUnion1$Outbound,
  ContentUnion1
> = smartUnion([
  z.string(),
  z.array(z.union([
    z.lazy(() => ContentText$outboundSchema),
    z.lazy(() => ContentImageURL$outboundSchema),
  ])),
]);

export function contentUnion1ToJSON(contentUnion1: ContentUnion1): string {
  return JSON.stringify(ContentUnion1$outboundSchema.parse(contentUnion1));
}

/** @internal */
export type Message$Outbound = {
  role: string;
  content: string | Array<ContentText$Outbound | ContentImageURL$Outbound>;
  name?: string | undefined;
  tool_calls?: Array<any> | undefined;
  tool_call_id?: string | undefined;
};

/** @internal */
export const Message$outboundSchema: z.ZodMiniType<Message$Outbound, Message> =
  z.pipe(
    z.object({
      role: Role$outboundSchema,
      content: smartUnion([
        z.string(),
        z.array(z.union([
          z.lazy(() => ContentText$outboundSchema),
          z.lazy(() => ContentImageURL$outboundSchema),
        ])),
      ]),
      name: z.optional(z.string()),
      toolCalls: z.optional(z.array(z.any())),
      toolCallId: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        toolCalls: "tool_calls",
        toolCallId: "tool_call_id",
      });
    }),
  );

export function messageToJSON(message: Message): string {
  return JSON.stringify(Message$outboundSchema.parse(message));
}

/** @internal */
export type PostV4ConversationsMetadata$Outbound = string | number | boolean;

/** @internal */
export const PostV4ConversationsMetadata$outboundSchema: z.ZodMiniType<
  PostV4ConversationsMetadata$Outbound,
  PostV4ConversationsMetadata
> = smartUnion([z.string(), z.number(), z.boolean()]);

export function postV4ConversationsMetadataToJSON(
  postV4ConversationsMetadata: PostV4ConversationsMetadata,
): string {
  return JSON.stringify(
    PostV4ConversationsMetadata$outboundSchema.parse(
      postV4ConversationsMetadata,
    ),
  );
}

/** @internal */
export type PostV4ConversationsRequest$Outbound = {
  conversationId: string;
  messages: Array<Message$Outbound>;
  containerTags?: Array<string> | undefined;
  metadata?: { [k: string]: string | number | boolean } | undefined;
};

/** @internal */
export const PostV4ConversationsRequest$outboundSchema: z.ZodMiniType<
  PostV4ConversationsRequest$Outbound,
  PostV4ConversationsRequest
> = z.object({
  conversationId: z.string(),
  messages: z.array(z.lazy(() => Message$outboundSchema)),
  containerTags: z.optional(z.array(z.string())),
  metadata: z.optional(
    z.record(z.string(), smartUnion([z.string(), z.number(), z.boolean()])),
  ),
});

export function postV4ConversationsRequestToJSON(
  postV4ConversationsRequest: PostV4ConversationsRequest,
): string {
  return JSON.stringify(
    PostV4ConversationsRequest$outboundSchema.parse(postV4ConversationsRequest),
  );
}
