/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ad4d749ee74c
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export const PostV3ConnectionsByProviderDocumentsProvider = {
  Notion: "notion",
  GoogleDrive: "google-drive",
  Onedrive: "onedrive",
  Gmail: "gmail",
  Github: "github",
  WebCrawler: "web-crawler",
  S3: "s3",
  Granola: "granola",
} as const;
export type PostV3ConnectionsByProviderDocumentsProvider = ClosedEnum<
  typeof PostV3ConnectionsByProviderDocumentsProvider
>;

export type PostV3ConnectionsByProviderDocumentsRequestBody = {
  /**
   * Optional comma-separated list of container tags to filter documents by
   */
  containerTags?: Array<string> | undefined;
};

export type PostV3ConnectionsByProviderDocumentsRequest = {
  provider: PostV3ConnectionsByProviderDocumentsProvider;
  body: PostV3ConnectionsByProviderDocumentsRequestBody;
};

export type PostV3ConnectionsByProviderDocumentsResponse = {
  createdAt: string;
  id: string | null;
  status: string;
  summary: string | null;
  title: string | null;
  type: string;
  updatedAt: string;
};

/** @internal */
export const PostV3ConnectionsByProviderDocumentsProvider$outboundSchema:
  z.ZodMiniEnum<typeof PostV3ConnectionsByProviderDocumentsProvider> = z.enum(
    PostV3ConnectionsByProviderDocumentsProvider,
  );

/** @internal */
export type PostV3ConnectionsByProviderDocumentsRequestBody$Outbound = {
  containerTags?: Array<string> | undefined;
};

/** @internal */
export const PostV3ConnectionsByProviderDocumentsRequestBody$outboundSchema:
  z.ZodMiniType<
    PostV3ConnectionsByProviderDocumentsRequestBody$Outbound,
    PostV3ConnectionsByProviderDocumentsRequestBody
  > = z.object({
    containerTags: z.optional(z.array(z.string())),
  });

export function postV3ConnectionsByProviderDocumentsRequestBodyToJSON(
  postV3ConnectionsByProviderDocumentsRequestBody:
    PostV3ConnectionsByProviderDocumentsRequestBody,
): string {
  return JSON.stringify(
    PostV3ConnectionsByProviderDocumentsRequestBody$outboundSchema.parse(
      postV3ConnectionsByProviderDocumentsRequestBody,
    ),
  );
}

/** @internal */
export type PostV3ConnectionsByProviderDocumentsRequest$Outbound = {
  provider: string;
  body: PostV3ConnectionsByProviderDocumentsRequestBody$Outbound;
};

/** @internal */
export const PostV3ConnectionsByProviderDocumentsRequest$outboundSchema:
  z.ZodMiniType<
    PostV3ConnectionsByProviderDocumentsRequest$Outbound,
    PostV3ConnectionsByProviderDocumentsRequest
  > = z.object({
    provider: PostV3ConnectionsByProviderDocumentsProvider$outboundSchema,
    body: z.lazy(() =>
      PostV3ConnectionsByProviderDocumentsRequestBody$outboundSchema
    ),
  });

export function postV3ConnectionsByProviderDocumentsRequestToJSON(
  postV3ConnectionsByProviderDocumentsRequest:
    PostV3ConnectionsByProviderDocumentsRequest,
): string {
  return JSON.stringify(
    PostV3ConnectionsByProviderDocumentsRequest$outboundSchema.parse(
      postV3ConnectionsByProviderDocumentsRequest,
    ),
  );
}

/** @internal */
export const PostV3ConnectionsByProviderDocumentsResponse$inboundSchema:
  z.ZodMiniType<PostV3ConnectionsByProviderDocumentsResponse, unknown> = z
    .object({
      createdAt: types.string(),
      id: types.nullable(types.string()),
      status: types.string(),
      summary: types.nullable(types.string()),
      title: types.nullable(types.string()),
      type: types.string(),
      updatedAt: types.string(),
    });

export function postV3ConnectionsByProviderDocumentsResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  PostV3ConnectionsByProviderDocumentsResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostV3ConnectionsByProviderDocumentsResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PostV3ConnectionsByProviderDocumentsResponse' from JSON`,
  );
}
