/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d8f4662533da
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Processing pipeline. "memory" builds durable learned context; "superrag" optimizes the document for retrieval without generating memories.
 */
export const PostNsByNamespaceDocumentTaskType = {
  Memory: "memory",
  Superrag: "superrag",
} as const;
/**
 * Processing pipeline. "memory" builds durable learned context; "superrag" optimizes the document for retrieval without generating memories.
 */
export type PostNsByNamespaceDocumentTaskType = ClosedEnum<
  typeof PostNsByNamespaceDocumentTaskType
>;

/**
 * Processing mode. "dynamic" (default) groups related documents so memories form from coherent context. "instant" processes each document independently right away and bills one extra operation per document.
 */
export const PostNsByNamespaceDocumentDreaming = {
  Dynamic: "dynamic",
  Instant: "instant",
} as const;
/**
 * Processing mode. "dynamic" (default) groups related documents so memories form from coherent context. "instant" processes each document independently right away and bills one extra operation per document.
 */
export type PostNsByNamespaceDocumentDreaming = ClosedEnum<
  typeof PostNsByNamespaceDocumentDreaming
>;

export type PostNsByNamespaceDocumentMetadata =
  | string
  | number
  | boolean
  | Array<string>;

export type PostNsByNamespaceDocumentGroup =
  | string
  | number
  | boolean
  | Array<string>;

export type PostNsByNamespaceDocumentRequestBody = {
  /**
   * The content to process. This may be plaintext or a URL to supported rich content.
   */
  content: string;
  /**
   * An optional caller-defined document ID
   */
  id?: string | undefined;
  /**
   * Context used to guide memory extraction within this namespace. Max 1500 characters.
   */
  supportingContext?: string | undefined;
  /**
   * Arbitrary metadata attached to the document and derived data
   */
  metadata?:
    | { [k: string]: string | number | boolean | Array<string> }
    | undefined;
  /**
   * Metadata values that isolate related context within the namespace
   */
  group?:
    | { [k: string]: string | number | boolean | Array<string> }
    | undefined;
  /**
   * When the source content is from, in ISO 8601 format
   */
  date?: string | undefined;
};

export type PostNsByNamespaceDocumentRequest = {
  /**
   * The isolated namespace. This can be an ID for your user, a project ID, or any other identifier you wish to use to scope documents.
   */
  namespace: string;
  /**
   * Processing pipeline. "memory" builds durable learned context; "superrag" optimizes the document for retrieval without generating memories.
   */
  taskType?: PostNsByNamespaceDocumentTaskType | undefined;
  /**
   * Processing mode. "dynamic" (default) groups related documents so memories form from coherent context. "instant" processes each document independently right away and bills one extra operation per document.
   */
  dreaming?: PostNsByNamespaceDocumentDreaming | undefined;
  body: PostNsByNamespaceDocumentRequestBody;
};

/**
 * Document accepted for processing
 */
export type PostNsByNamespaceDocumentResponse = {
  /**
   * Unique identifier of the document
   */
  id: string;
  /**
   * Status of the document
   */
  status: string;
};

/** @internal */
export const PostNsByNamespaceDocumentTaskType$outboundSchema: z.ZodMiniEnum<
  typeof PostNsByNamespaceDocumentTaskType
> = z.enum(PostNsByNamespaceDocumentTaskType);

/** @internal */
export const PostNsByNamespaceDocumentDreaming$outboundSchema: z.ZodMiniEnum<
  typeof PostNsByNamespaceDocumentDreaming
> = z.enum(PostNsByNamespaceDocumentDreaming);

/** @internal */
export type PostNsByNamespaceDocumentMetadata$Outbound =
  | string
  | number
  | boolean
  | Array<string>;

/** @internal */
export const PostNsByNamespaceDocumentMetadata$outboundSchema: z.ZodMiniType<
  PostNsByNamespaceDocumentMetadata$Outbound,
  PostNsByNamespaceDocumentMetadata
> = smartUnion([z.string(), z.number(), z.boolean(), z.array(z.string())]);

export function postNsByNamespaceDocumentMetadataToJSON(
  postNsByNamespaceDocumentMetadata: PostNsByNamespaceDocumentMetadata,
): string {
  return JSON.stringify(
    PostNsByNamespaceDocumentMetadata$outboundSchema.parse(
      postNsByNamespaceDocumentMetadata,
    ),
  );
}

/** @internal */
export type PostNsByNamespaceDocumentGroup$Outbound =
  | string
  | number
  | boolean
  | Array<string>;

/** @internal */
export const PostNsByNamespaceDocumentGroup$outboundSchema: z.ZodMiniType<
  PostNsByNamespaceDocumentGroup$Outbound,
  PostNsByNamespaceDocumentGroup
> = smartUnion([z.string(), z.number(), z.boolean(), z.array(z.string())]);

export function postNsByNamespaceDocumentGroupToJSON(
  postNsByNamespaceDocumentGroup: PostNsByNamespaceDocumentGroup,
): string {
  return JSON.stringify(
    PostNsByNamespaceDocumentGroup$outboundSchema.parse(
      postNsByNamespaceDocumentGroup,
    ),
  );
}

/** @internal */
export type PostNsByNamespaceDocumentRequestBody$Outbound = {
  content: string;
  id?: string | undefined;
  supportingContext?: string | undefined;
  metadata?:
    | { [k: string]: string | number | boolean | Array<string> }
    | undefined;
  group?:
    | { [k: string]: string | number | boolean | Array<string> }
    | undefined;
  date?: string | undefined;
};

/** @internal */
export const PostNsByNamespaceDocumentRequestBody$outboundSchema: z.ZodMiniType<
  PostNsByNamespaceDocumentRequestBody$Outbound,
  PostNsByNamespaceDocumentRequestBody
> = z.object({
  content: z.string(),
  id: z.optional(z.string()),
  supportingContext: z.optional(z.string()),
  metadata: z.optional(
    z.record(
      z.string(),
      smartUnion([z.string(), z.number(), z.boolean(), z.array(z.string())]),
    ),
  ),
  group: z.optional(
    z.record(
      z.string(),
      smartUnion([z.string(), z.number(), z.boolean(), z.array(z.string())]),
    ),
  ),
  date: z.optional(z.string()),
});

export function postNsByNamespaceDocumentRequestBodyToJSON(
  postNsByNamespaceDocumentRequestBody: PostNsByNamespaceDocumentRequestBody,
): string {
  return JSON.stringify(
    PostNsByNamespaceDocumentRequestBody$outboundSchema.parse(
      postNsByNamespaceDocumentRequestBody,
    ),
  );
}

/** @internal */
export type PostNsByNamespaceDocumentRequest$Outbound = {
  namespace: string;
  taskType?: string | undefined;
  dreaming?: string | undefined;
  body: PostNsByNamespaceDocumentRequestBody$Outbound;
};

/** @internal */
export const PostNsByNamespaceDocumentRequest$outboundSchema: z.ZodMiniType<
  PostNsByNamespaceDocumentRequest$Outbound,
  PostNsByNamespaceDocumentRequest
> = z.object({
  namespace: z.string(),
  taskType: z.optional(PostNsByNamespaceDocumentTaskType$outboundSchema),
  dreaming: z.optional(PostNsByNamespaceDocumentDreaming$outboundSchema),
  body: z.lazy(() => PostNsByNamespaceDocumentRequestBody$outboundSchema),
});

export function postNsByNamespaceDocumentRequestToJSON(
  postNsByNamespaceDocumentRequest: PostNsByNamespaceDocumentRequest,
): string {
  return JSON.stringify(
    PostNsByNamespaceDocumentRequest$outboundSchema.parse(
      postNsByNamespaceDocumentRequest,
    ),
  );
}

/** @internal */
export const PostNsByNamespaceDocumentResponse$inboundSchema: z.ZodMiniType<
  PostNsByNamespaceDocumentResponse,
  unknown
> = z.object({
  id: types.string(),
  status: types.string(),
});

export function postNsByNamespaceDocumentResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostNsByNamespaceDocumentResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostNsByNamespaceDocumentResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostNsByNamespaceDocumentResponse' from JSON`,
  );
}
