/*
 * Generated by scripts/surface/generate.ts from fern/openapi.json. DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as types from "../../types/primitives.js";

export const PostNsByNamespaceDocumentBatchTaskType = {
  Memory: "memory",
  Superrag: "superrag",
} as const;
export type PostNsByNamespaceDocumentBatchTaskType = ClosedEnum<typeof PostNsByNamespaceDocumentBatchTaskType>;

/** @internal */
export const PostNsByNamespaceDocumentBatchTaskType$outboundSchema: z.ZodMiniEnum<typeof PostNsByNamespaceDocumentBatchTaskType> = z.enum(PostNsByNamespaceDocumentBatchTaskType);

export const PostNsByNamespaceDocumentBatchDreaming = {
  Dynamic: "dynamic",
  Instant: "instant",
} as const;
export type PostNsByNamespaceDocumentBatchDreaming = ClosedEnum<typeof PostNsByNamespaceDocumentBatchDreaming>;

/** @internal */
export const PostNsByNamespaceDocumentBatchDreaming$outboundSchema: z.ZodMiniEnum<typeof PostNsByNamespaceDocumentBatchDreaming> = z.enum(PostNsByNamespaceDocumentBatchDreaming);

export type PostNsByNamespaceDocumentBatchRequestBody = {
  /**
   * Documents to ingest or append in one request
   */
  documents: Array<PostNsByNamespaceDocumentBatchDocument>;
};

/** @internal */
export type PostNsByNamespaceDocumentBatchRequestBody$Outbound = {
  /**
   * Documents to ingest or append in one request
   */
  documents: Array<PostNsByNamespaceDocumentBatchDocument$Outbound>;
};

/** @internal */
export const PostNsByNamespaceDocumentBatchRequestBody$outboundSchema: z.ZodMiniType<PostNsByNamespaceDocumentBatchRequestBody$Outbound, PostNsByNamespaceDocumentBatchRequestBody> = z.object({
  documents: z.array(z.lazy(() => PostNsByNamespaceDocumentBatchDocument$outboundSchema)),
});

export function postNsByNamespaceDocumentBatchRequestBodyToJSON(
  postNsByNamespaceDocumentBatchRequestBody: PostNsByNamespaceDocumentBatchRequestBody,
): string {
  return JSON.stringify(PostNsByNamespaceDocumentBatchRequestBody$outboundSchema.parse(postNsByNamespaceDocumentBatchRequestBody));
}

export type PostNsByNamespaceDocumentBatchDocument = {
  /**
   * The content to process. This may be plaintext or a URL to supported rich content.
   */
  content: string;
  /**
   * An optional caller-defined document ID
   */
  id?: string | undefined;
  /**
   * Context used to guide memory extraction within this namespace. Max 1500 characters.
   */
  supportingContext?: string | undefined;
  /**
   * Arbitrary metadata attached to the document and derived data
   */
  metadata?: { [k: string]: string | number | boolean | Array<string> } | undefined;
  /**
   * Metadata values that isolate related context within the namespace
   */
  group?: { [k: string]: string | number | boolean | Array<string> } | undefined;
  /**
   * When the source content is from, in ISO 8601 format
   */
  date?: string | undefined;
};

/** @internal */
export type PostNsByNamespaceDocumentBatchDocument$Outbound = {
  /**
   * The content to process. This may be plaintext or a URL to supported rich content.
   */
  content: string;
  /**
   * An optional caller-defined document ID
   */
  id?: string | undefined;
  /**
   * Context used to guide memory extraction within this namespace. Max 1500 characters.
   */
  supportingContext?: string | undefined;
  /**
   * Arbitrary metadata attached to the document and derived data
   */
  metadata?: { [k: string]: string | number | boolean | Array<string> } | undefined;
  /**
   * Metadata values that isolate related context within the namespace
   */
  group?: { [k: string]: string | number | boolean | Array<string> } | undefined;
  /**
   * When the source content is from, in ISO 8601 format
   */
  date?: string | undefined;
};

/** @internal */
export const PostNsByNamespaceDocumentBatchDocument$outboundSchema: z.ZodMiniType<PostNsByNamespaceDocumentBatchDocument$Outbound, PostNsByNamespaceDocumentBatchDocument> = z.object({
  content: z.string(),
  id: z.optional(z.string()),
  supportingContext: z.optional(z.string()),
  metadata: z.optional(z.record(z.string(), smartUnion([z.string(), z.number(), z.boolean(), z.array(z.string())]))),
  group: z.optional(z.record(z.string(), smartUnion([z.string(), z.number(), z.boolean(), z.array(z.string())]))),
  date: z.optional(z.string()),
});

export function postNsByNamespaceDocumentBatchDocumentToJSON(
  postNsByNamespaceDocumentBatchDocument: PostNsByNamespaceDocumentBatchDocument,
): string {
  return JSON.stringify(PostNsByNamespaceDocumentBatchDocument$outboundSchema.parse(postNsByNamespaceDocumentBatchDocument));
}

export type PostNsByNamespaceDocumentBatchMetadata =
  | string
  | number
  | boolean
  | Array<string>
;

/** @internal */
export type PostNsByNamespaceDocumentBatchMetadata$Outbound =
  | string
  | number
  | boolean
  | Array<string>
;

/** @internal */
export const PostNsByNamespaceDocumentBatchMetadata$outboundSchema: z.ZodMiniType<PostNsByNamespaceDocumentBatchMetadata$Outbound, PostNsByNamespaceDocumentBatchMetadata> = smartUnion([
  z.string(),
  z.number(),
  z.boolean(),
  z.array(z.string()),
]);

export function postNsByNamespaceDocumentBatchMetadataToJSON(
  postNsByNamespaceDocumentBatchMetadata: PostNsByNamespaceDocumentBatchMetadata,
): string {
  return JSON.stringify(PostNsByNamespaceDocumentBatchMetadata$outboundSchema.parse(postNsByNamespaceDocumentBatchMetadata));
}

export type PostNsByNamespaceDocumentBatchGroup =
  | string
  | number
  | boolean
  | Array<string>
;

/** @internal */
export type PostNsByNamespaceDocumentBatchGroup$Outbound =
  | string
  | number
  | boolean
  | Array<string>
;

/** @internal */
export const PostNsByNamespaceDocumentBatchGroup$outboundSchema: z.ZodMiniType<PostNsByNamespaceDocumentBatchGroup$Outbound, PostNsByNamespaceDocumentBatchGroup> = smartUnion([
  z.string(),
  z.number(),
  z.boolean(),
  z.array(z.string()),
]);

export function postNsByNamespaceDocumentBatchGroupToJSON(
  postNsByNamespaceDocumentBatchGroup: PostNsByNamespaceDocumentBatchGroup,
): string {
  return JSON.stringify(PostNsByNamespaceDocumentBatchGroup$outboundSchema.parse(postNsByNamespaceDocumentBatchGroup));
}

export type PostNsByNamespaceDocumentBatchRequest = {
  namespace: string;
  taskType?: PostNsByNamespaceDocumentBatchTaskType | undefined;
  dreaming?: PostNsByNamespaceDocumentBatchDreaming | undefined;
  body: PostNsByNamespaceDocumentBatchRequestBody;
};

/** @internal */
export type PostNsByNamespaceDocumentBatchRequest$Outbound = {
  namespace: string;
  taskType?: string | undefined;
  dreaming?: string | undefined;
  body: PostNsByNamespaceDocumentBatchRequestBody$Outbound;
};

/** @internal */
export const PostNsByNamespaceDocumentBatchRequest$outboundSchema: z.ZodMiniType<PostNsByNamespaceDocumentBatchRequest$Outbound, PostNsByNamespaceDocumentBatchRequest> = z.object({
  namespace: z.string(),
  taskType: z.optional(PostNsByNamespaceDocumentBatchTaskType$outboundSchema),
  dreaming: z.optional(PostNsByNamespaceDocumentBatchDreaming$outboundSchema),
  body: z.lazy(() => PostNsByNamespaceDocumentBatchRequestBody$outboundSchema),
});

export function postNsByNamespaceDocumentBatchRequestToJSON(
  postNsByNamespaceDocumentBatchRequest: PostNsByNamespaceDocumentBatchRequest,
): string {
  return JSON.stringify(PostNsByNamespaceDocumentBatchRequest$outboundSchema.parse(postNsByNamespaceDocumentBatchRequest));
}

export type PostNsByNamespaceDocumentBatchResponse = {
  /**
   * Array of results for each document in the batch
   */
  results: Array<PostNsByNamespaceDocumentBatchResult>;
  /**
   * Count of documents that failed to add
   */
  failed: number;
  /**
   * Count of documents successfully added
   */
  success: number;
};

/** @internal */
export const PostNsByNamespaceDocumentBatchResponse$inboundSchema: z.ZodMiniType<PostNsByNamespaceDocumentBatchResponse, unknown> = z.object({
  results: z.array(z.lazy(() => PostNsByNamespaceDocumentBatchResult$inboundSchema)),
  failed: types.number(),
  success: types.number(),
});

export function postNsByNamespaceDocumentBatchResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostNsByNamespaceDocumentBatchResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostNsByNamespaceDocumentBatchResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostNsByNamespaceDocumentBatchResponse' from JSON`,
  );
}

export type PostNsByNamespaceDocumentBatchResult = {
  /**
   * Unique identifier of the document (empty string for failed items)
   */
  id: string;
  /**
   * Status of the document (e.g. 'done', 'queued', 'error')
   */
  status: string;
  /**
   * Error message when status is 'error'
   */
  error?: string | undefined;
  /**
   * Additional error details when status is 'error'
   */
  details?: string | undefined;
  /**
   * URL of the failed item, when it had one. Only present on failed items, where it may be the only way to tell which input the error belongs to (the id falls back to 'unknown' when the input had neither an id nor a customId).
   */
  url?: string | undefined;
};

/** @internal */
export const PostNsByNamespaceDocumentBatchResult$inboundSchema: z.ZodMiniType<PostNsByNamespaceDocumentBatchResult, unknown> = z.object({
  id: types.string(),
  status: types.string(),
  error: types.optional(types.string()),
  details: types.optional(types.string()),
  url: types.optional(types.string()),
});

export function postNsByNamespaceDocumentBatchResultFromJSON(
  jsonString: string,
): SafeParseResult<PostNsByNamespaceDocumentBatchResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostNsByNamespaceDocumentBatchResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostNsByNamespaceDocumentBatchResult' from JSON`,
  );
}
