/*
 * Generated by scripts/surface/generate.ts from fern/openapi.json. DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import { FilterExpression, FilterExpression$Outbound, FilterExpression$outboundSchema } from "../filter-expression.js";
import * as types from "../../types/primitives.js";

export const Type = {
  Documents: "documents",
  Chunks: "chunks",
  Memories: "memories",
} as const;
export type Type = ClosedEnum<typeof Type>;

/** @internal */
export const Type$outboundSchema: z.ZodMiniEnum<typeof Type> = z.enum(Type);

export const Sort = {
  CreatedAt: "createdAt",
  UpdatedAt: "updatedAt",
  Position: "position",
} as const;
export type Sort = ClosedEnum<typeof Sort>;

/** @internal */
export const Sort$outboundSchema: z.ZodMiniEnum<typeof Sort> = z.enum(Sort);

export const Order = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type Order = ClosedEnum<typeof Order>;

/** @internal */
export const Order$outboundSchema: z.ZodMiniEnum<typeof Order> = z.enum(Order);

export type Page =
  | string
  | number
;

/** @internal */
export type Page$Outbound =
  | string
  | number
;

/** @internal */
export const Page$outboundSchema: z.ZodMiniType<Page$Outbound, Page> = smartUnion([
  z.string(),
  z.number(),
]);

export function pageToJSON(
  page: Page,
): string {
  return JSON.stringify(Page$outboundSchema.parse(page));
}

export type Limit =
  | string
  | number
;

/** @internal */
export type Limit$Outbound =
  | string
  | number
;

/** @internal */
export const Limit$outboundSchema: z.ZodMiniType<Limit$Outbound, Limit> = smartUnion([
  z.string(),
  z.number(),
]);

export function limitToJSON(
  limit: Limit,
): string {
  return JSON.stringify(Limit$outboundSchema.parse(limit));
}

export type PostNsByNamespaceListByTypeRequestBody = {
  /**
   * A type-safe metadata filter predicate or nested and/or expression. The API validates up to 5 levels of nesting.
   */
  filter?: FilterExpression | undefined;
};

/** @internal */
export type PostNsByNamespaceListByTypeRequestBody$Outbound = {
  /**
   * A type-safe metadata filter predicate or nested and/or expression. The API validates up to 5 levels of nesting.
   */
  filter?: FilterExpression$Outbound | undefined;
};

/** @internal */
export const PostNsByNamespaceListByTypeRequestBody$outboundSchema: z.ZodMiniType<PostNsByNamespaceListByTypeRequestBody$Outbound, PostNsByNamespaceListByTypeRequestBody> = z.object({
  filter: z.optional(FilterExpression$outboundSchema),
});

export function postNsByNamespaceListByTypeRequestBodyToJSON(
  postNsByNamespaceListByTypeRequestBody: PostNsByNamespaceListByTypeRequestBody,
): string {
  return JSON.stringify(PostNsByNamespaceListByTypeRequestBody$outboundSchema.parse(postNsByNamespaceListByTypeRequestBody));
}

export type PostNsByNamespaceListByTypeRequest = {
  namespace: string;
  type: Type;
  page?: string | number | undefined;
  limit?: string | number | undefined;
  sort?: Sort | undefined;
  order?: Order | undefined;
  body?: PostNsByNamespaceListByTypeRequestBody | undefined;
};

/** @internal */
export type PostNsByNamespaceListByTypeRequest$Outbound = {
  namespace: string;
  type: string;
  page?: string | number | undefined;
  limit?: string | number | undefined;
  sort?: string | undefined;
  order?: string | undefined;
  body?: PostNsByNamespaceListByTypeRequestBody$Outbound | undefined;
};

/** @internal */
export const PostNsByNamespaceListByTypeRequest$outboundSchema: z.ZodMiniType<PostNsByNamespaceListByTypeRequest$Outbound, PostNsByNamespaceListByTypeRequest> = z.object({
  namespace: z.string(),
  type: Type$outboundSchema,
  page: z.optional(smartUnion([z.string(), z.number()])),
  limit: z.optional(smartUnion([z.string(), z.number()])),
  sort: z.optional(Sort$outboundSchema),
  order: z._default(Order$outboundSchema, "desc"),
  body: z.optional(z.lazy(() => PostNsByNamespaceListByTypeRequestBody$outboundSchema)),
});

export function postNsByNamespaceListByTypeRequestToJSON(
  postNsByNamespaceListByTypeRequest: PostNsByNamespaceListByTypeRequest,
): string {
  return JSON.stringify(PostNsByNamespaceListByTypeRequest$outboundSchema.parse(postNsByNamespaceListByTypeRequest));
}

/**
 * A namespace-scoped page of one resource type
 */
export type PostNsByNamespaceListByTypeResponse = {
  /**
   * Documents on this page; empty when a different resource type is requested
   */
  documents: Array<PostNsByNamespaceListByTypeDocument>;
  /**
   * Chunks on this page; empty when a different resource type is requested
   */
  chunks: Array<PostNsByNamespaceListByTypeChunk>;
  /**
   * Memories on this page; empty when a different resource type is requested
   */
  memories: Array<PostNsByNamespaceListByTypeMemory>;
  /**
   * Page metadata for the selected resource collection
   */
  pagination: Pagination;
};

/** @internal */
export const PostNsByNamespaceListByTypeResponse$inboundSchema: z.ZodMiniType<PostNsByNamespaceListByTypeResponse, unknown> = z.object({
  documents: z.array(z.lazy(() => PostNsByNamespaceListByTypeDocument$inboundSchema)),
  chunks: z.array(z.lazy(() => PostNsByNamespaceListByTypeChunk$inboundSchema)),
  memories: z.array(z.lazy(() => PostNsByNamespaceListByTypeMemory$inboundSchema)),
  pagination: z.lazy(() => Pagination$inboundSchema),
});

export function postNsByNamespaceListByTypeResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostNsByNamespaceListByTypeResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostNsByNamespaceListByTypeResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostNsByNamespaceListByTypeResponse' from JSON`,
  );
}

/**
 * A document in this namespace without its content
 */
export type PostNsByNamespaceListByTypeDocument = {
  /**
   * Stable document identifier
   */
  id: string;
  /**
   * Extracted or caller-provided document title
   */
  title: string | null;
  /**
   * Detected source or content type
   */
  type: string;
  /**
   * Generated summary of the document, when available
   */
  summary: string | null;
  /**
   * Public metadata attached to the document
   */
  metadata: { [k: string]: any };
  /**
   * Original source URL, when the document was ingested from the web
   */
  url: string | null;
  /**
   * Processing status, lifecycle timestamps, and storage path maintained by Supermemory
   */
  system: DocumentSystem;
};

/** @internal */
export const PostNsByNamespaceListByTypeDocument$inboundSchema: z.ZodMiniType<PostNsByNamespaceListByTypeDocument, unknown> = z.object({
  id: types.string(),
  title: types.nullable(types.string()),
  type: types.string(),
  summary: types.nullable(types.string()),
  metadata: z.record(z.string(), z.any()),
  url: types.nullable(types.string()),
  system: z.lazy(() => DocumentSystem$inboundSchema),
});

export function postNsByNamespaceListByTypeDocumentFromJSON(
  jsonString: string,
): SafeParseResult<PostNsByNamespaceListByTypeDocument, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostNsByNamespaceListByTypeDocument$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostNsByNamespaceListByTypeDocument' from JSON`,
  );
}

/**
 * Processing status, lifecycle timestamps, and storage path maintained by Supermemory
 */
export type DocumentSystem = {
  /**
   * Current extraction and memory-processing status
   */
  status: string;
  /**
   * ISO 8601 timestamp when the document was created
   */
  createdAt: Date;
  /**
   * ISO 8601 timestamp of the latest document update
   */
  updatedAt: Date;
};

/** @internal */
export const DocumentSystem$inboundSchema: z.ZodMiniType<DocumentSystem, unknown> = z.object({
  status: types.string(),
  createdAt: types.date(),
  updatedAt: types.date(),
});

export function documentSystemFromJSON(
  jsonString: string,
): SafeParseResult<DocumentSystem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DocumentSystem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DocumentSystem' from JSON`,
  );
}

export type PostNsByNamespaceListByTypeChunk = {
  /**
   * Stable chunk identifier
   */
  id: string;
  /**
   * Zero-based order within the document
   */
  position: number;
  /**
   * Chunk text used for retrieval
   */
  content: string;
  /**
   * Chunk content type
   */
  type: string;
  /**
   * Chunk metadata, when available
   */
  metadata: { [k: string]: any } | null;
  /**
   * Lifecycle timestamps maintained by Supermemory
   */
  system: PostNsByNamespaceListByTypeChunkSystem;
  /**
   * ID of the chunk's parent document
   */
  documentId: string;
};

/** @internal */
export const PostNsByNamespaceListByTypeChunk$inboundSchema: z.ZodMiniType<PostNsByNamespaceListByTypeChunk, unknown> = z.object({
  id: types.string(),
  position: types.number(),
  content: types.string(),
  type: types.string(),
  metadata: types.nullable(z.record(z.string(), z.any())),
  system: z.lazy(() => PostNsByNamespaceListByTypeChunkSystem$inboundSchema),
  documentId: types.string(),
});

export function postNsByNamespaceListByTypeChunkFromJSON(
  jsonString: string,
): SafeParseResult<PostNsByNamespaceListByTypeChunk, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostNsByNamespaceListByTypeChunk$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostNsByNamespaceListByTypeChunk' from JSON`,
  );
}

/**
 * Lifecycle timestamps maintained by Supermemory
 */
export type PostNsByNamespaceListByTypeChunkSystem = {
  /**
   * ISO 8601 timestamp when the chunk was created
   */
  createdAt: Date;
};

/** @internal */
export const PostNsByNamespaceListByTypeChunkSystem$inboundSchema: z.ZodMiniType<PostNsByNamespaceListByTypeChunkSystem, unknown> = z.object({
  createdAt: types.date(),
});

export function postNsByNamespaceListByTypeChunkSystemFromJSON(
  jsonString: string,
): SafeParseResult<PostNsByNamespaceListByTypeChunkSystem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostNsByNamespaceListByTypeChunkSystem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostNsByNamespaceListByTypeChunkSystem' from JSON`,
  );
}

/**
 * A memory formed from documents in this namespace
 */
export type PostNsByNamespaceListByTypeMemory = {
  /**
   * Stable memory identifier
   */
  id: string;
  /**
   * Learned fact or context extracted from the document
   */
  memory: string;
  /**
   * Memory metadata, including temporal context when available
   */
  metadata: { [k: string]: any } | null;
  /**
   * Whether the memory belongs to the stable profile section
   */
  isStatic: boolean;
  /**
   * Whether the memory was inferred rather than explicitly stated
   */
  isInference: boolean;
  /**
   * Whether this is the newest version in its memory chain
   */
  isLatest: boolean;
  /**
   * Whether this memory has been excluded from normal recall
   */
  isForgotten: boolean;
  /**
   * Version number within the memory chain
   */
  version: number;
  /**
   * Lifecycle timestamps maintained by Supermemory
   */
  system: PostNsByNamespaceListByTypeMemorySystem;
};

/** @internal */
export const PostNsByNamespaceListByTypeMemory$inboundSchema: z.ZodMiniType<PostNsByNamespaceListByTypeMemory, unknown> = z.object({
  id: types.string(),
  memory: types.string(),
  metadata: types.nullable(z.record(z.string(), z.any())),
  isStatic: types.boolean(),
  isInference: types.boolean(),
  isLatest: types.boolean(),
  isForgotten: types.boolean(),
  version: types.number(),
  system: z.lazy(() => PostNsByNamespaceListByTypeMemorySystem$inboundSchema),
});

export function postNsByNamespaceListByTypeMemoryFromJSON(
  jsonString: string,
): SafeParseResult<PostNsByNamespaceListByTypeMemory, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostNsByNamespaceListByTypeMemory$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostNsByNamespaceListByTypeMemory' from JSON`,
  );
}

/**
 * Lifecycle timestamps maintained by Supermemory
 */
export type PostNsByNamespaceListByTypeMemorySystem = {
  /**
   * ISO 8601 timestamp when this memory version was created
   */
  createdAt: Date;
  /**
   * ISO 8601 timestamp of the latest update to this version
   */
  updatedAt: Date;
};

/** @internal */
export const PostNsByNamespaceListByTypeMemorySystem$inboundSchema: z.ZodMiniType<PostNsByNamespaceListByTypeMemorySystem, unknown> = z.object({
  createdAt: types.date(),
  updatedAt: types.date(),
});

export function postNsByNamespaceListByTypeMemorySystemFromJSON(
  jsonString: string,
): SafeParseResult<PostNsByNamespaceListByTypeMemorySystem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostNsByNamespaceListByTypeMemorySystem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostNsByNamespaceListByTypeMemorySystem' from JSON`,
  );
}

/**
 * Page metadata for the selected resource collection
 */
export type Pagination = {
  /**
   * Current one-based page number
   */
  currentPage: number;
  /**
   * Maximum resources returned per page
   */
  limit: number;
  /**
   * Total resources matching the request
   */
  totalItems: number;
  /**
   * Total pages available at the selected limit
   */
  totalPages: number;
};

/** @internal */
export const Pagination$inboundSchema: z.ZodMiniType<Pagination, unknown> = z.object({
  currentPage: types.number(),
  limit: z._default(types.number(), 10),
  totalItems: types.number(),
  totalPages: types.number(),
});

export function paginationFromJSON(
  jsonString: string,
): SafeParseResult<Pagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Pagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Pagination' from JSON`,
  );
}
