/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b62475fe35e3
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type PostNsByNamespaceConnectorsByIdSyncRequest = {
  /**
   * Namespace identifier. This can be an ID for your user, a project ID, or any other identifier you wish to use to scope documents and memories.
   */
  namespace: string;
  /**
   * Connector identifier returned when the connector was created
   */
  id: string;
};

/**
 * Sync queued
 */
export type PostNsByNamespaceConnectorsByIdSyncResponse = {
  /**
   * Connector identifier
   */
  id: string;
  status: "queued";
};

/** @internal */
export type PostNsByNamespaceConnectorsByIdSyncRequest$Outbound = {
  namespace: string;
  id: string;
};

/** @internal */
export const PostNsByNamespaceConnectorsByIdSyncRequest$outboundSchema:
  z.ZodMiniType<
    PostNsByNamespaceConnectorsByIdSyncRequest$Outbound,
    PostNsByNamespaceConnectorsByIdSyncRequest
  > = z.object({
    namespace: z.string(),
    id: z.string(),
  });

export function postNsByNamespaceConnectorsByIdSyncRequestToJSON(
  postNsByNamespaceConnectorsByIdSyncRequest:
    PostNsByNamespaceConnectorsByIdSyncRequest,
): string {
  return JSON.stringify(
    PostNsByNamespaceConnectorsByIdSyncRequest$outboundSchema.parse(
      postNsByNamespaceConnectorsByIdSyncRequest,
    ),
  );
}

/** @internal */
export const PostNsByNamespaceConnectorsByIdSyncResponse$inboundSchema:
  z.ZodMiniType<PostNsByNamespaceConnectorsByIdSyncResponse, unknown> = z
    .object({
      id: types.string(),
      status: types.literal("queued"),
    });

export function postNsByNamespaceConnectorsByIdSyncResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  PostNsByNamespaceConnectorsByIdSyncResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostNsByNamespaceConnectorsByIdSyncResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PostNsByNamespaceConnectorsByIdSyncResponse' from JSON`,
  );
}
