/*
 * Generated by scripts/surface/generate.ts from fern/openapi.json. DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import { FilterExpression, FilterExpression$Outbound, FilterExpression$outboundSchema } from "../filter-expression.js";
import * as types from "../../types/primitives.js";

export type PostNsByNamespaceProfileRequestBody = {
  /**
   * A type-safe metadata filter predicate or nested and/or expression. The API validates up to 5 levels of nesting.
   */
  filter?: FilterExpression | undefined;
  /**
   * Custom buckets to return. Omit to return every effective bucket.
   */
  buckets?: Array<string> | undefined;
};

/** @internal */
export type PostNsByNamespaceProfileRequestBody$Outbound = {
  /**
   * A type-safe metadata filter predicate or nested and/or expression. The API validates up to 5 levels of nesting.
   */
  filter?: FilterExpression$Outbound | undefined;
  /**
   * Custom buckets to return. Omit to return every effective bucket.
   */
  buckets?: Array<string> | undefined;
};

/** @internal */
export const PostNsByNamespaceProfileRequestBody$outboundSchema: z.ZodMiniType<PostNsByNamespaceProfileRequestBody$Outbound, PostNsByNamespaceProfileRequestBody> = z.object({
  filter: z.optional(FilterExpression$outboundSchema),
  buckets: z.optional(z.array(z.string())),
});

export function postNsByNamespaceProfileRequestBodyToJSON(
  postNsByNamespaceProfileRequestBody: PostNsByNamespaceProfileRequestBody,
): string {
  return JSON.stringify(PostNsByNamespaceProfileRequestBody$outboundSchema.parse(postNsByNamespaceProfileRequestBody));
}

export type PostNsByNamespaceProfileRequest = {
  namespace: string;
  body?: PostNsByNamespaceProfileRequestBody | undefined;
};

/** @internal */
export type PostNsByNamespaceProfileRequest$Outbound = {
  namespace: string;
  body?: PostNsByNamespaceProfileRequestBody$Outbound | undefined;
};

/** @internal */
export const PostNsByNamespaceProfileRequest$outboundSchema: z.ZodMiniType<PostNsByNamespaceProfileRequest$Outbound, PostNsByNamespaceProfileRequest> = z.object({
  namespace: z.string(),
  body: z.optional(z.lazy(() => PostNsByNamespaceProfileRequestBody$outboundSchema)),
});

export function postNsByNamespaceProfileRequestToJSON(
  postNsByNamespaceProfileRequest: PostNsByNamespaceProfileRequest,
): string {
  return JSON.stringify(PostNsByNamespaceProfileRequest$outboundSchema.parse(postNsByNamespaceProfileRequest));
}

export type PostNsByNamespaceProfileResponse =
  | PostNsByNamespaceProfileResponseBody
  | string
;

/** @internal */
export const PostNsByNamespaceProfileResponse$inboundSchema: z.ZodMiniType<PostNsByNamespaceProfileResponse, unknown> = smartUnion([
  z.lazy(() => PostNsByNamespaceProfileResponseBody$inboundSchema),
  types.string(),
]);

export function postNsByNamespaceProfileResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostNsByNamespaceProfileResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostNsByNamespaceProfileResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostNsByNamespaceProfileResponse' from JSON`,
  );
}

export type PostNsByNamespaceProfileResponseBody = {
  /**
   * Continuously maintained understanding of the subject represented by this namespace
   */
  profile: Profile;
};

/** @internal */
export const PostNsByNamespaceProfileResponseBody$inboundSchema: z.ZodMiniType<PostNsByNamespaceProfileResponseBody, unknown> = z.object({
  profile: z.lazy(() => Profile$inboundSchema),
});

export function postNsByNamespaceProfileResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<PostNsByNamespaceProfileResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostNsByNamespaceProfileResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostNsByNamespaceProfileResponseBody' from JSON`,
  );
}

/**
 * Continuously maintained understanding of the subject represented by this namespace
 */
export type Profile = {
  /**
   * Durable facts that define the subject and rarely change, such as identity or long-term preferences
   */
  static: Array<Static>;
  /**
   * Recent or evolving context, such as current goals, projects, and active interests
   */
  dynamic: Array<Dynamic>;
  /**
   * Custom profile sections keyed by bucket name, with the memories currently assigned to each bucket
   */
  buckets: { [k: string]: Array<Bucket> };
};

/** @internal */
export const Profile$inboundSchema: z.ZodMiniType<Profile, unknown> = z.object({
  static: z.array(z.lazy(() => Static$inboundSchema)),
  dynamic: z.array(z.lazy(() => Dynamic$inboundSchema)),
  buckets: z.record(z.string(), z.array(z.lazy(() => Bucket$inboundSchema))),
});

export function profileFromJSON(
  jsonString: string,
): SafeParseResult<Profile, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Profile$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Profile' from JSON`,
  );
}

export type Static = {
  /**
   * Memory ID, or an aggregated_-prefixed ID for a summary synthesized from several memories
   */
  id: string;
  /**
   * Memory text
   */
  memory: string;
};

/** @internal */
export const Static$inboundSchema: z.ZodMiniType<Static, unknown> = z.object({
  id: types.string(),
  memory: types.string(),
});

export function staticFromJSON(
  jsonString: string,
): SafeParseResult<Static, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Static$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Static' from JSON`,
  );
}

export type Dynamic = {
  /**
   * Memory ID, or an aggregated_-prefixed ID for a summary synthesized from several memories
   */
  id: string;
  /**
   * Memory text
   */
  memory: string;
};

/** @internal */
export const Dynamic$inboundSchema: z.ZodMiniType<Dynamic, unknown> = z.object({
  id: types.string(),
  memory: types.string(),
});

export function dynamicFromJSON(
  jsonString: string,
): SafeParseResult<Dynamic, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Dynamic$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Dynamic' from JSON`,
  );
}

export type Bucket = {
  /**
   * Memory ID, or an aggregated_-prefixed ID for a summary synthesized from several memories
   */
  id: string;
  /**
   * Memory text
   */
  memory: string;
};

/** @internal */
export const Bucket$inboundSchema: z.ZodMiniType<Bucket, unknown> = z.object({
  id: types.string(),
  memory: types.string(),
});

export function bucketFromJSON(
  jsonString: string,
): SafeParseResult<Bucket, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Bucket$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Bucket' from JSON`,
  );
}
