/*
 * Generated by scripts/surface/generate.ts from fern/openapi.json. DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { ClosedEnum, OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import { FilterExpression, FilterExpression$Outbound, FilterExpression$outboundSchema } from "../filter-expression.js";
import * as types from "../../types/primitives.js";

export const SearchMode = {
  Hybrid: "hybrid",
  Memories: "memories",
  Chunks: "chunks",
} as const;
export type SearchMode = ClosedEnum<typeof SearchMode>;

/** @internal */
export const SearchMode$outboundSchema: z.ZodMiniEnum<typeof SearchMode> = z.enum(SearchMode);

/**
 * Post-retrieval ranking. "order" improves result ordering; "aggregate" also combines overlapping context into cleaner answers. This is helpful if you want to ensure the most relevant results are returned.
 */
export const Rerank = {
  None: "none",
  Order: "order",
  Aggregate: "aggregate",
} as const;
/**
 * Post-retrieval ranking. "order" improves result ordering; "aggregate" also combines overlapping context into cleaner answers. This is helpful if you want to ensure the most relevant results are returned.
 */
export type Rerank = ClosedEnum<typeof Rerank>;

/** @internal */
export const Rerank$outboundSchema: z.ZodMiniEnum<typeof Rerank> = z.enum(Rerank);

/**
 * How this memory is connected to the matched memory
 */
export const ParentRelation = {
  Updates: "updates",
  Extends: "extends",
  Derives: "derives",
} as const;
/**
 * How this memory is connected to the matched memory
 */
export type ParentRelation = OpenEnum<typeof ParentRelation>;

/** @internal */
export const ParentRelation$inboundSchema: z.ZodMiniType<ParentRelation, unknown> = openEnums.inboundSchema(ParentRelation);

/**
 * How this memory is connected to the matched memory
 */
export const ChildRelation = {
  Updates: "updates",
  Extends: "extends",
  Derives: "derives",
} as const;
/**
 * How this memory is connected to the matched memory
 */
export type ChildRelation = OpenEnum<typeof ChildRelation>;

/** @internal */
export const ChildRelation$inboundSchema: z.ZodMiniType<ChildRelation, unknown> = openEnums.inboundSchema(ChildRelation);

/**
 * How this memory is connected to the matched memory
 */
export const SiblingRelation = {
  Updates: "updates",
  Extends: "extends",
  Derives: "derives",
} as const;
/**
 * How this memory is connected to the matched memory
 */
export type SiblingRelation = OpenEnum<typeof SiblingRelation>;

/** @internal */
export const SiblingRelation$inboundSchema: z.ZodMiniType<SiblingRelation, unknown> = openEnums.inboundSchema(SiblingRelation);

export type PostNsByNamespaceSearchRequestBody = {
  /**
   * Natural-language question, topic, or phrase to retrieve relevant context for. Replaces the v4 `q` field.
   */
  query: string;
  /**
   * A type-safe metadata filter predicate or nested and/or expression. The API validates up to 5 levels of nesting.
   */
  filter?: FilterExpression | undefined;
  /**
   * Optional context to include alongside each matching result
   */
  attach?: PostNsByNamespaceSearchAttach | undefined;
  /**
   * Minimum relevance score from 0 to 1. Raise it for precision (fewer, accurate results) or lower it for broader recall (more results).
   */
  threshold?: number | undefined;
  /**
   * Post-retrieval ranking. "order" improves result ordering; "aggregate" also combines overlapping context into cleaner answers. This is helpful if you want to ensure the most relevant results are returned.
   */
  rerank?: Rerank | undefined;
  /**
   * Expand and clarify the query before retrieval to improve recall for conversational or underspecified prompts. This increases the latency by about 400ms.
   */
  rewriteQuery?: boolean | undefined;
};

/** @internal */
export type PostNsByNamespaceSearchRequestBody$Outbound = {
  /**
   * Natural-language question, topic, or phrase to retrieve relevant context for. Replaces the v4 `q` field.
   */
  query: string;
  /**
   * A type-safe metadata filter predicate or nested and/or expression. The API validates up to 5 levels of nesting.
   */
  filter?: FilterExpression$Outbound | undefined;
  /**
   * Optional context to include alongside each matching result
   */
  attach?: PostNsByNamespaceSearchAttach$Outbound | undefined;
  /**
   * Minimum relevance score from 0 to 1. Raise it for precision (fewer, accurate results) or lower it for broader recall (more results).
   */
  threshold?: number | undefined;
  /**
   * Post-retrieval ranking. "order" improves result ordering; "aggregate" also combines overlapping context into cleaner answers. This is helpful if you want to ensure the most relevant results are returned.
   */
  rerank?: string | undefined;
  /**
   * Expand and clarify the query before retrieval to improve recall for conversational or underspecified prompts. This increases the latency by about 400ms.
   */
  rewriteQuery?: boolean | undefined;
};

/** @internal */
export const PostNsByNamespaceSearchRequestBody$outboundSchema: z.ZodMiniType<PostNsByNamespaceSearchRequestBody$Outbound, PostNsByNamespaceSearchRequestBody> = z.object({
  query: z.string(),
  filter: z.optional(FilterExpression$outboundSchema),
  attach: z.optional(z.lazy(() => PostNsByNamespaceSearchAttach$outboundSchema)),
  threshold: z._default(z.number(), 0.3),
  rerank: z._default(Rerank$outboundSchema, "none"),
  rewriteQuery: z._default(z.boolean(), false),
});

export function postNsByNamespaceSearchRequestBodyToJSON(
  postNsByNamespaceSearchRequestBody: PostNsByNamespaceSearchRequestBody,
): string {
  return JSON.stringify(PostNsByNamespaceSearchRequestBody$outboundSchema.parse(postNsByNamespaceSearchRequestBody));
}

/**
 * Optional context to include alongside each matching result
 */
export type PostNsByNamespaceSearchAttach = {
  /**
   * Attach the source document for each result when one is available
   */
  documents?: boolean | undefined;
  /**
   * Attach parent, child, and sibling memories that explain how each memory evolved
   */
  related?: boolean | undefined;
  /**
   * Allow forgotten memories to participate in recall
   */
  forgotten?: boolean | undefined;
};

/** @internal */
export type PostNsByNamespaceSearchAttach$Outbound = {
  /**
   * Attach the source document for each result when one is available
   */
  documents?: boolean | undefined;
  /**
   * Attach parent, child, and sibling memories that explain how each memory evolved
   */
  related?: boolean | undefined;
  /**
   * Allow forgotten memories to participate in recall
   */
  forgotten?: boolean | undefined;
};

/** @internal */
export const PostNsByNamespaceSearchAttach$outboundSchema: z.ZodMiniType<PostNsByNamespaceSearchAttach$Outbound, PostNsByNamespaceSearchAttach> = z.object({
  documents: z._default(z.boolean(), false),
  related: z._default(z.boolean(), false),
  forgotten: z._default(z.boolean(), false),
});

export function postNsByNamespaceSearchAttachToJSON(
  postNsByNamespaceSearchAttach: PostNsByNamespaceSearchAttach,
): string {
  return JSON.stringify(PostNsByNamespaceSearchAttach$outboundSchema.parse(postNsByNamespaceSearchAttach));
}

export type PostNsByNamespaceSearchRequest = {
  namespace: string;
  limit?: number | undefined;
  searchMode?: SearchMode | undefined;
  body: PostNsByNamespaceSearchRequestBody;
};

/** @internal */
export type PostNsByNamespaceSearchRequest$Outbound = {
  namespace: string;
  limit?: number | undefined;
  searchMode?: string | undefined;
  body: PostNsByNamespaceSearchRequestBody$Outbound;
};

/** @internal */
export const PostNsByNamespaceSearchRequest$outboundSchema: z.ZodMiniType<PostNsByNamespaceSearchRequest$Outbound, PostNsByNamespaceSearchRequest> = z.object({
  namespace: z.string(),
  limit: z._default(z.int(), 10),
  searchMode: z._default(SearchMode$outboundSchema, "hybrid"),
  body: z.lazy(() => PostNsByNamespaceSearchRequestBody$outboundSchema),
});

export function postNsByNamespaceSearchRequestToJSON(
  postNsByNamespaceSearchRequest: PostNsByNamespaceSearchRequest,
): string {
  return JSON.stringify(PostNsByNamespaceSearchRequest$outboundSchema.parse(postNsByNamespaceSearchRequest));
}

export type PostNsByNamespaceSearchResponse = {
  /**
   * Ranked memories and source chunks matching the query
   */
  results: Array<PostNsByNamespaceSearchResult>;
  /**
   * Server-side search duration in milliseconds
   */
  searchTime: number;
};

/** @internal */
export const PostNsByNamespaceSearchResponse$inboundSchema: z.ZodMiniType<PostNsByNamespaceSearchResponse, unknown> = z.object({
  results: z.array(z.lazy(() => PostNsByNamespaceSearchResult$inboundSchema)),
  searchTime: types.number(),
});

export function postNsByNamespaceSearchResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostNsByNamespaceSearchResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostNsByNamespaceSearchResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostNsByNamespaceSearchResponse' from JSON`,
  );
}

export type PostNsByNamespaceSearchResult = {
  /**
   * Stable identifier for the matching result
   */
  id: string;
  /**
   * Learned fact or context returned by memory search (only present for memory results)
   */
  memory?: string | undefined;
  /**
   * Source passage returned by chunk search (only present for chunk results from hybrid search)
   */
  chunk?: string | undefined;
  /**
   * Public metadata attached to the result
   */
  metadata: { [k: string]: any } | null;
  /**
   * Normalized relevance score used to rank the result, from 0 to 1
   */
  similarity: number;
  /**
   * Whether the memory is its latest version; false for recalled forgotten memories
   */
  isLatest: boolean;
  /**
   * Lifecycle and filesystem details for the result
   */
  system: PostNsByNamespaceSearchSystem;
  /**
   * Requested supporting context for the result
   */
  included?: Included | undefined;
};

/** @internal */
export const PostNsByNamespaceSearchResult$inboundSchema: z.ZodMiniType<PostNsByNamespaceSearchResult, unknown> = z.object({
  id: types.string(),
  memory: types.optional(types.string()),
  chunk: types.optional(types.string()),
  metadata: types.nullable(z.record(z.string(), z.any())),
  similarity: types.number(),
  isLatest: types.boolean(),
  system: z.lazy(() => PostNsByNamespaceSearchSystem$inboundSchema),
  included: types.optional(z.lazy(() => Included$inboundSchema)),
});

export function postNsByNamespaceSearchResultFromJSON(
  jsonString: string,
): SafeParseResult<PostNsByNamespaceSearchResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostNsByNamespaceSearchResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostNsByNamespaceSearchResult' from JSON`,
  );
}

/**
 * Lifecycle and filesystem details for the result
 */
export type PostNsByNamespaceSearchSystem = {
  /**
   * ISO 8601 timestamp of the latest result update
   */
  updatedAt: string;
  /**
   * ISO 8601 timestamp when the result was first created
   */
  createdAt?: string | undefined;
};

/** @internal */
export const PostNsByNamespaceSearchSystem$inboundSchema: z.ZodMiniType<PostNsByNamespaceSearchSystem, unknown> = z.object({
  updatedAt: types.string(),
  createdAt: types.optional(types.string()),
});

export function postNsByNamespaceSearchSystemFromJSON(
  jsonString: string,
): SafeParseResult<PostNsByNamespaceSearchSystem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostNsByNamespaceSearchSystem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostNsByNamespaceSearchSystem' from JSON`,
  );
}

/**
 * Requested supporting context for the result
 */
export type Included = {
  /**
   * Memory relationships attached when requested
   */
  related?: Related | undefined;
  /**
   * Source document attached when requested and available
   */
  document?: PostNsByNamespaceSearchDocument | undefined;
};

/** @internal */
export const Included$inboundSchema: z.ZodMiniType<Included, unknown> = z.object({
  related: types.optional(z.lazy(() => Related$inboundSchema)),
  document: types.optional(z.lazy(() => PostNsByNamespaceSearchDocument$inboundSchema)),
});

export function includedFromJSON(
  jsonString: string,
): SafeParseResult<Included, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Included$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Included' from JSON`,
  );
}

/**
 * Memory relationships attached when requested
 */
export type Related = {
  /**
   * Earlier memories this result updates or derives from
   */
  parents: Array<Parent>;
  /**
   * Newer memories that update or extend this result
   */
  children: Array<Child>;
  /**
   * Other memories derived from related context
   */
  siblings: Array<Sibling>;
};

/** @internal */
export const Related$inboundSchema: z.ZodMiniType<Related, unknown> = z.object({
  parents: z.array(z.lazy(() => Parent$inboundSchema)),
  children: z.array(z.lazy(() => Child$inboundSchema)),
  siblings: z.array(z.lazy(() => Sibling$inboundSchema)),
});

export function relatedFromJSON(
  jsonString: string,
): SafeParseResult<Related, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Related$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Related' from JSON`,
  );
}

export type Parent = {
  /**
   * How this memory is connected to the matched memory
   */
  relation: ParentRelation;
  /**
   * Version number within the related memory's history
   */
  version?: number | null | undefined;
  /**
   * Related learned fact or context
   */
  memory: string;
  /**
   * Public metadata associated with the related memory
   */
  metadata?: { [k: string]: any } | null | undefined;
  /**
   * Lifecycle details for the related memory
   */
  system: ParentSystem;
};

/** @internal */
export const Parent$inboundSchema: z.ZodMiniType<Parent, unknown> = z.object({
  relation: ParentRelation$inboundSchema,
  version: z.optional(z.nullable(types.number())),
  memory: types.string(),
  metadata: z.optional(z.nullable(z.record(z.string(), z.any()))),
  system: z.lazy(() => ParentSystem$inboundSchema),
});

export function parentFromJSON(
  jsonString: string,
): SafeParseResult<Parent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Parent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Parent' from JSON`,
  );
}

/**
 * Lifecycle details for the related memory
 */
export type ParentSystem = {
  /**
   * ISO 8601 timestamp of the related memory's latest update
   */
  updatedAt: string;
};

/** @internal */
export const ParentSystem$inboundSchema: z.ZodMiniType<ParentSystem, unknown> = z.object({
  updatedAt: types.string(),
});

export function parentSystemFromJSON(
  jsonString: string,
): SafeParseResult<ParentSystem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ParentSystem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ParentSystem' from JSON`,
  );
}

export type Child = {
  /**
   * How this memory is connected to the matched memory
   */
  relation: ChildRelation;
  /**
   * Version number within the related memory's history
   */
  version?: number | null | undefined;
  /**
   * Related learned fact or context
   */
  memory: string;
  /**
   * Public metadata associated with the related memory
   */
  metadata?: { [k: string]: any } | null | undefined;
  /**
   * Lifecycle details for the related memory
   */
  system: ChildSystem;
};

/** @internal */
export const Child$inboundSchema: z.ZodMiniType<Child, unknown> = z.object({
  relation: ChildRelation$inboundSchema,
  version: z.optional(z.nullable(types.number())),
  memory: types.string(),
  metadata: z.optional(z.nullable(z.record(z.string(), z.any()))),
  system: z.lazy(() => ChildSystem$inboundSchema),
});

export function childFromJSON(
  jsonString: string,
): SafeParseResult<Child, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Child$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Child' from JSON`,
  );
}

/**
 * Lifecycle details for the related memory
 */
export type ChildSystem = {
  /**
   * ISO 8601 timestamp of the related memory's latest update
   */
  updatedAt: string;
};

/** @internal */
export const ChildSystem$inboundSchema: z.ZodMiniType<ChildSystem, unknown> = z.object({
  updatedAt: types.string(),
});

export function childSystemFromJSON(
  jsonString: string,
): SafeParseResult<ChildSystem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChildSystem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChildSystem' from JSON`,
  );
}

export type Sibling = {
  /**
   * How this memory is connected to the matched memory
   */
  relation: SiblingRelation;
  /**
   * Version number within the related memory's history
   */
  version?: number | null | undefined;
  /**
   * Related learned fact or context
   */
  memory: string;
  /**
   * Public metadata associated with the related memory
   */
  metadata?: { [k: string]: any } | null | undefined;
  /**
   * Lifecycle details for the related memory
   */
  system: SiblingSystem;
};

/** @internal */
export const Sibling$inboundSchema: z.ZodMiniType<Sibling, unknown> = z.object({
  relation: SiblingRelation$inboundSchema,
  version: z.optional(z.nullable(types.number())),
  memory: types.string(),
  metadata: z.optional(z.nullable(z.record(z.string(), z.any()))),
  system: z.lazy(() => SiblingSystem$inboundSchema),
});

export function siblingFromJSON(
  jsonString: string,
): SafeParseResult<Sibling, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sibling$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sibling' from JSON`,
  );
}

/**
 * Lifecycle details for the related memory
 */
export type SiblingSystem = {
  /**
   * ISO 8601 timestamp of the related memory's latest update
   */
  updatedAt: string;
};

/** @internal */
export const SiblingSystem$inboundSchema: z.ZodMiniType<SiblingSystem, unknown> = z.object({
  updatedAt: types.string(),
});

export function siblingSystemFromJSON(
  jsonString: string,
): SafeParseResult<SiblingSystem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SiblingSystem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SiblingSystem' from JSON`,
  );
}

/**
 * Source document attached when requested and available
 */
export type PostNsByNamespaceSearchDocument = {
  /**
   * Source document identifier
   */
  id: string;
  /**
   * Source document title
   */
  title?: string | null | undefined;
  /**
   * Detected source or content type
   */
  type?: string | null | undefined;
  /**
   * Public metadata attached to the source document
   */
  metadata?: { [k: string]: any } | null | undefined;
  /**
   * Generated summary of the source document
   */
  summary?: string | null | undefined;
  /**
   * ISO 8601 timestamp when the source document was created
   */
  createdAt: string;
  /**
   * ISO 8601 timestamp of the source document's latest update
   */
  updatedAt: string;
};

/** @internal */
export const PostNsByNamespaceSearchDocument$inboundSchema: z.ZodMiniType<PostNsByNamespaceSearchDocument, unknown> = z.object({
  id: types.string(),
  title: z.optional(z.nullable(types.string())),
  type: z.optional(z.nullable(types.string())),
  metadata: z.optional(z.nullable(z.record(z.string(), z.any()))),
  summary: z.optional(z.nullable(types.string())),
  createdAt: types.string(),
  updatedAt: types.string(),
});

export function postNsByNamespaceSearchDocumentFromJSON(
  jsonString: string,
): SafeParseResult<PostNsByNamespaceSearchDocument, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostNsByNamespaceSearchDocument$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostNsByNamespaceSearchDocument' from JSON`,
  );
}
