/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 50dcbbe1c826
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type PostV3DocumentsBatchMetadata1 =
  | string
  | number
  | boolean
  | Array<string>;

/**
 * Task type: "memory" (default) for full context layer with SuperRAG built in, "superrag" for managed RAG as a service.
 */
export const PostV3DocumentsBatchTaskType1 = {
  Memory: "memory",
  Superrag: "superrag",
} as const;
/**
 * Task type: "memory" (default) for full context layer with SuperRAG built in, "superrag" for managed RAG as a service.
 */
export type PostV3DocumentsBatchTaskType1 = ClosedEnum<
  typeof PostV3DocumentsBatchTaskType1
>;

export type PostV3DocumentsBatchFilterByMetadata1 =
  | string
  | number
  | boolean
  | Array<string>;

/**
 * Processing mode. "dynamic" (default) groups related documents together so memories form from coherent, logical units rather than one isolated entry at a time. "instant" processes each document on its own right away, and bills one extra operation per document.
 */
export const PostV3DocumentsBatchDreaming1 = {
  Instant: "instant",
  Dynamic: "dynamic",
} as const;
/**
 * Processing mode. "dynamic" (default) groups related documents together so memories form from coherent, logical units rather than one isolated entry at a time. "instant" processes each document on its own right away, and bills one extra operation per document.
 */
export type PostV3DocumentsBatchDreaming1 = ClosedEnum<
  typeof PostV3DocumentsBatchDreaming1
>;

export type PostV3DocumentsBatchMetadata2 =
  | string
  | number
  | boolean
  | Array<string>;

/**
 * Task type: "memory" (default) for full context layer with SuperRAG built in, "superrag" for managed RAG as a service.
 */
export const PostV3DocumentsBatchTaskType2 = {
  Memory: "memory",
  Superrag: "superrag",
} as const;
/**
 * Task type: "memory" (default) for full context layer with SuperRAG built in, "superrag" for managed RAG as a service.
 */
export type PostV3DocumentsBatchTaskType2 = ClosedEnum<
  typeof PostV3DocumentsBatchTaskType2
>;

export type PostV3DocumentsBatchFilterByMetadata2 =
  | string
  | number
  | boolean
  | Array<string>;

/**
 * Processing mode. "dynamic" (default) groups related documents together so memories form from coherent, logical units rather than one isolated entry at a time. "instant" processes each document on its own right away, and bills one extra operation per document.
 */
export const PostV3DocumentsBatchDreaming2 = {
  Instant: "instant",
  Dynamic: "dynamic",
} as const;
/**
 * Processing mode. "dynamic" (default) groups related documents together so memories form from coherent, logical units rather than one isolated entry at a time. "instant" processes each document on its own right away, and bills one extra operation per document.
 */
export type PostV3DocumentsBatchDreaming2 = ClosedEnum<
  typeof PostV3DocumentsBatchDreaming2
>;

export type Documents = {
  /**
   * Optional tag this document should be containerized by. This can be an ID for your user, a project ID, or any other identifier you wish to use to group documents.
   */
  containerTag?: string | undefined;
  /**
   * (DEPRECATED: Use containerTag instead) Optional tags this document should be containerized by. This can be an ID for your user, a project ID, or any other identifier you wish to use to group documents.
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  containerTags?: Array<string> | undefined;
  /**
   * The content to extract and process into a document. This can be a URL to a website, a PDF, an image, or a video.
   *
   * @remarks
   *
   * Plaintext: Any plaintext format
   *
   * URL: A URL to a website, PDF, image, or video
   *
   * We automatically detect the content type from the url's response format.
   */
  content: string;
  /**
   * Optional custom ID of the document. This could be an ID from your database that will uniquely identify this document.
   */
  customId?: string | undefined;
  /**
   * Optional metadata for the document. This is used to store additional information about the document. You can use this to store any additional information you need about the document. Metadata can be filtered through. Keys must be strings and are case sensitive. Values can be strings, numbers, or booleans. You cannot nest objects.
   */
  metadata?:
    | { [k: string]: string | number | boolean | Array<string> }
    | undefined;
  /**
   * Task type: "memory" (default) for full context layer with SuperRAG built in, "superrag" for managed RAG as a service.
   */
  taskType?: PostV3DocumentsBatchTaskType2 | undefined;
  /**
   * Optional file path for the document (e.g., '/documents/reports/file.pdf'). Used by supermemoryfs to map documents to filesystem paths.
   */
  filepath?: string | undefined;
  /**
   * Optional metadata filter scoping which existing memories are pulled as context during ingestion. Scalar values match exactly (AND across keys); array values match ANY (OR within key). Only memories whose source documents match this filter are used as context.
   */
  filterByMetadata?:
    | { [k: string]: string | number | boolean | Array<string> }
    | undefined;
  /**
   * Optional entity context for this container tag. Max 1500 characters. Used during document processing to guide memory extraction.
   */
  entityContext?: string | undefined;
  /**
   * Processing mode. "dynamic" (default) groups related documents together so memories form from coherent, logical units rather than one isolated entry at a time. "instant" processes each document on its own right away, and bills one extra operation per document.
   */
  dreaming?: PostV3DocumentsBatchDreaming2 | undefined;
};

export type DocumentsUnion = Array<Documents> | Array<string>;

export type PostV3DocumentsBatchRequest = {
  /**
   * Optional tag this document should be containerized by. This can be an ID for your user, a project ID, or any other identifier you wish to use to group documents.
   */
  containerTag?: string | undefined;
  /**
   * (DEPRECATED: Use containerTag instead) Optional tags this document should be containerized by. This can be an ID for your user, a project ID, or any other identifier you wish to use to group documents.
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  containerTags?: Array<string> | undefined;
  /**
   * Optional metadata for the document. This is used to store additional information about the document. You can use this to store any additional information you need about the document. Metadata can be filtered through. Keys must be strings and are case sensitive. Values can be strings, numbers, or booleans. You cannot nest objects.
   */
  metadata?:
    | { [k: string]: string | number | boolean | Array<string> }
    | undefined;
  /**
   * Task type: "memory" (default) for full context layer with SuperRAG built in, "superrag" for managed RAG as a service.
   */
  taskType?: PostV3DocumentsBatchTaskType1 | undefined;
  /**
   * Optional file path for the document (e.g., '/documents/reports/file.pdf'). Used by supermemoryfs to map documents to filesystem paths.
   */
  filepath?: string | undefined;
  /**
   * Optional metadata filter scoping which existing memories are pulled as context during ingestion. Scalar values match exactly (AND across keys); array values match ANY (OR within key). Only memories whose source documents match this filter are used as context.
   */
  filterByMetadata?:
    | { [k: string]: string | number | boolean | Array<string> }
    | undefined;
  /**
   * Optional entity context for this container tag. Max 1500 characters. Used during document processing to guide memory extraction.
   */
  entityContext?: string | undefined;
  /**
   * Processing mode. "dynamic" (default) groups related documents together so memories form from coherent, logical units rather than one isolated entry at a time. "instant" processes each document on its own right away, and bills one extra operation per document.
   */
  dreaming?: PostV3DocumentsBatchDreaming1 | undefined;
  documents: Array<Documents> | Array<string>;
  content?: any | null | undefined;
};

export type PostV3DocumentsBatchResult = {
  /**
   * Unique identifier of the document (empty string for failed items)
   */
  id: string;
  /**
   * Status of the document (e.g. 'done', 'queued', 'error')
   */
  status: string;
  /**
   * Error message when status is 'error'
   */
  error?: string | undefined;
  /**
   * Additional error details when status is 'error'
   */
  details?: string | undefined;
};

/**
 * Documents added successfully
 */
export type PostV3DocumentsBatchResponse = {
  /**
   * Array of results for each document in the batch
   */
  results: Array<PostV3DocumentsBatchResult>;
  /**
   * Count of documents that failed to add
   */
  failed: number;
  /**
   * Count of documents successfully added
   */
  success: number;
};

/** @internal */
export type PostV3DocumentsBatchMetadata1$Outbound =
  | string
  | number
  | boolean
  | Array<string>;

/** @internal */
export const PostV3DocumentsBatchMetadata1$outboundSchema: z.ZodMiniType<
  PostV3DocumentsBatchMetadata1$Outbound,
  PostV3DocumentsBatchMetadata1
> = smartUnion([z.string(), z.number(), z.boolean(), z.array(z.string())]);

export function postV3DocumentsBatchMetadata1ToJSON(
  postV3DocumentsBatchMetadata1: PostV3DocumentsBatchMetadata1,
): string {
  return JSON.stringify(
    PostV3DocumentsBatchMetadata1$outboundSchema.parse(
      postV3DocumentsBatchMetadata1,
    ),
  );
}

/** @internal */
export const PostV3DocumentsBatchTaskType1$outboundSchema: z.ZodMiniEnum<
  typeof PostV3DocumentsBatchTaskType1
> = z.enum(PostV3DocumentsBatchTaskType1);

/** @internal */
export type PostV3DocumentsBatchFilterByMetadata1$Outbound =
  | string
  | number
  | boolean
  | Array<string>;

/** @internal */
export const PostV3DocumentsBatchFilterByMetadata1$outboundSchema:
  z.ZodMiniType<
    PostV3DocumentsBatchFilterByMetadata1$Outbound,
    PostV3DocumentsBatchFilterByMetadata1
  > = smartUnion([z.string(), z.number(), z.boolean(), z.array(z.string())]);

export function postV3DocumentsBatchFilterByMetadata1ToJSON(
  postV3DocumentsBatchFilterByMetadata1: PostV3DocumentsBatchFilterByMetadata1,
): string {
  return JSON.stringify(
    PostV3DocumentsBatchFilterByMetadata1$outboundSchema.parse(
      postV3DocumentsBatchFilterByMetadata1,
    ),
  );
}

/** @internal */
export const PostV3DocumentsBatchDreaming1$outboundSchema: z.ZodMiniEnum<
  typeof PostV3DocumentsBatchDreaming1
> = z.enum(PostV3DocumentsBatchDreaming1);

/** @internal */
export type PostV3DocumentsBatchMetadata2$Outbound =
  | string
  | number
  | boolean
  | Array<string>;

/** @internal */
export const PostV3DocumentsBatchMetadata2$outboundSchema: z.ZodMiniType<
  PostV3DocumentsBatchMetadata2$Outbound,
  PostV3DocumentsBatchMetadata2
> = smartUnion([z.string(), z.number(), z.boolean(), z.array(z.string())]);

export function postV3DocumentsBatchMetadata2ToJSON(
  postV3DocumentsBatchMetadata2: PostV3DocumentsBatchMetadata2,
): string {
  return JSON.stringify(
    PostV3DocumentsBatchMetadata2$outboundSchema.parse(
      postV3DocumentsBatchMetadata2,
    ),
  );
}

/** @internal */
export const PostV3DocumentsBatchTaskType2$outboundSchema: z.ZodMiniEnum<
  typeof PostV3DocumentsBatchTaskType2
> = z.enum(PostV3DocumentsBatchTaskType2);

/** @internal */
export type PostV3DocumentsBatchFilterByMetadata2$Outbound =
  | string
  | number
  | boolean
  | Array<string>;

/** @internal */
export const PostV3DocumentsBatchFilterByMetadata2$outboundSchema:
  z.ZodMiniType<
    PostV3DocumentsBatchFilterByMetadata2$Outbound,
    PostV3DocumentsBatchFilterByMetadata2
  > = smartUnion([z.string(), z.number(), z.boolean(), z.array(z.string())]);

export function postV3DocumentsBatchFilterByMetadata2ToJSON(
  postV3DocumentsBatchFilterByMetadata2: PostV3DocumentsBatchFilterByMetadata2,
): string {
  return JSON.stringify(
    PostV3DocumentsBatchFilterByMetadata2$outboundSchema.parse(
      postV3DocumentsBatchFilterByMetadata2,
    ),
  );
}

/** @internal */
export const PostV3DocumentsBatchDreaming2$outboundSchema: z.ZodMiniEnum<
  typeof PostV3DocumentsBatchDreaming2
> = z.enum(PostV3DocumentsBatchDreaming2);

/** @internal */
export type Documents$Outbound = {
  containerTag?: string | undefined;
  containerTags?: Array<string> | undefined;
  content: string;
  customId?: string | undefined;
  metadata?:
    | { [k: string]: string | number | boolean | Array<string> }
    | undefined;
  taskType?: string | undefined;
  filepath?: string | undefined;
  filterByMetadata?:
    | { [k: string]: string | number | boolean | Array<string> }
    | undefined;
  entityContext?: string | undefined;
  dreaming?: string | undefined;
};

/** @internal */
export const Documents$outboundSchema: z.ZodMiniType<
  Documents$Outbound,
  Documents
> = z.object({
  containerTag: z.optional(z.string()),
  containerTags: z.optional(z.array(z.string())),
  content: z.string(),
  customId: z.optional(z.string()),
  metadata: z.optional(
    z.record(
      z.string(),
      smartUnion([z.string(), z.number(), z.boolean(), z.array(z.string())]),
    ),
  ),
  taskType: z.optional(PostV3DocumentsBatchTaskType2$outboundSchema),
  filepath: z.optional(z.string()),
  filterByMetadata: z.optional(
    z.record(
      z.string(),
      smartUnion([z.string(), z.number(), z.boolean(), z.array(z.string())]),
    ),
  ),
  entityContext: z.optional(z.string()),
  dreaming: z.optional(PostV3DocumentsBatchDreaming2$outboundSchema),
});

export function documentsToJSON(documents: Documents): string {
  return JSON.stringify(Documents$outboundSchema.parse(documents));
}

/** @internal */
export type DocumentsUnion$Outbound = Array<Documents$Outbound> | Array<string>;

/** @internal */
export const DocumentsUnion$outboundSchema: z.ZodMiniType<
  DocumentsUnion$Outbound,
  DocumentsUnion
> = smartUnion([
  z.array(z.lazy(() => Documents$outboundSchema)),
  z.array(z.string()),
]);

export function documentsUnionToJSON(documentsUnion: DocumentsUnion): string {
  return JSON.stringify(DocumentsUnion$outboundSchema.parse(documentsUnion));
}

/** @internal */
export type PostV3DocumentsBatchRequest$Outbound = {
  containerTag?: string | undefined;
  containerTags?: Array<string> | undefined;
  metadata?:
    | { [k: string]: string | number | boolean | Array<string> }
    | undefined;
  taskType?: string | undefined;
  filepath?: string | undefined;
  filterByMetadata?:
    | { [k: string]: string | number | boolean | Array<string> }
    | undefined;
  entityContext?: string | undefined;
  dreaming?: string | undefined;
  documents: Array<Documents$Outbound> | Array<string>;
  content?: any | null | undefined;
};

/** @internal */
export const PostV3DocumentsBatchRequest$outboundSchema: z.ZodMiniType<
  PostV3DocumentsBatchRequest$Outbound,
  PostV3DocumentsBatchRequest
> = z.object({
  containerTag: z.optional(z.string()),
  containerTags: z.optional(z.array(z.string())),
  metadata: z.optional(
    z.record(
      z.string(),
      smartUnion([z.string(), z.number(), z.boolean(), z.array(z.string())]),
    ),
  ),
  taskType: z.optional(PostV3DocumentsBatchTaskType1$outboundSchema),
  filepath: z.optional(z.string()),
  filterByMetadata: z.optional(
    z.record(
      z.string(),
      smartUnion([z.string(), z.number(), z.boolean(), z.array(z.string())]),
    ),
  ),
  entityContext: z.optional(z.string()),
  dreaming: z.optional(PostV3DocumentsBatchDreaming1$outboundSchema),
  documents: smartUnion([
    z.array(z.lazy(() => Documents$outboundSchema)),
    z.array(z.string()),
  ]),
  content: z.optional(z.nullable(z.any())),
});

export function postV3DocumentsBatchRequestToJSON(
  postV3DocumentsBatchRequest: PostV3DocumentsBatchRequest,
): string {
  return JSON.stringify(
    PostV3DocumentsBatchRequest$outboundSchema.parse(
      postV3DocumentsBatchRequest,
    ),
  );
}

/** @internal */
export const PostV3DocumentsBatchResult$inboundSchema: z.ZodMiniType<
  PostV3DocumentsBatchResult,
  unknown
> = z.object({
  id: types.string(),
  status: types.string(),
  error: types.optional(types.string()),
  details: types.optional(types.string()),
});

export function postV3DocumentsBatchResultFromJSON(
  jsonString: string,
): SafeParseResult<PostV3DocumentsBatchResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV3DocumentsBatchResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV3DocumentsBatchResult' from JSON`,
  );
}

/** @internal */
export const PostV3DocumentsBatchResponse$inboundSchema: z.ZodMiniType<
  PostV3DocumentsBatchResponse,
  unknown
> = z.object({
  results: z.array(z.lazy(() => PostV3DocumentsBatchResult$inboundSchema)),
  failed: types.number(),
  success: types.number(),
});

export function postV3DocumentsBatchResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostV3DocumentsBatchResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV3DocumentsBatchResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV3DocumentsBatchResponse' from JSON`,
  );
}
