/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3334bcd37b58
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type PostV3ContainerTagsMergeRequest = {
  /**
   * List of container tags to merge (min: 2, max: 2). All documents from these tags will be merged into the target.
   */
  containerTags: Array<string>;
  targetContainerTag: string;
};

/**
 * The queued status of the merge job.
 */
export const PostV3ContainerTagsMergeStatus = {
  Queued: "queued",
} as const;
/**
 * The queued status of the merge job.
 */
export type PostV3ContainerTagsMergeStatus = ClosedEnum<
  typeof PostV3ContainerTagsMergeStatus
>;

/**
 * Merge queued successfully
 */
export type PostV3ContainerTagsMergeResponse = {
  /**
   * Whether the merge job was queued successfully.
   */
  success: boolean;
  /**
   * The queued status of the merge job.
   */
  status: PostV3ContainerTagsMergeStatus;
  /**
   * Identifier for the queued merge job.
   */
  mergeId: string;
  /**
   * The target container tag that documents will be merged into.
   */
  targetTag: string;
  /**
   * List of source container tags queued for merge.
   */
  sourceTags: Array<string>;
};

/** @internal */
export type PostV3ContainerTagsMergeRequest$Outbound = {
  containerTags: Array<string>;
  targetContainerTag: string;
};

/** @internal */
export const PostV3ContainerTagsMergeRequest$outboundSchema: z.ZodMiniType<
  PostV3ContainerTagsMergeRequest$Outbound,
  PostV3ContainerTagsMergeRequest
> = z.object({
  containerTags: z.array(z.string()),
  targetContainerTag: z.string(),
});

export function postV3ContainerTagsMergeRequestToJSON(
  postV3ContainerTagsMergeRequest: PostV3ContainerTagsMergeRequest,
): string {
  return JSON.stringify(
    PostV3ContainerTagsMergeRequest$outboundSchema.parse(
      postV3ContainerTagsMergeRequest,
    ),
  );
}

/** @internal */
export const PostV3ContainerTagsMergeStatus$inboundSchema: z.ZodMiniEnum<
  typeof PostV3ContainerTagsMergeStatus
> = z.enum(PostV3ContainerTagsMergeStatus);

/** @internal */
export const PostV3ContainerTagsMergeResponse$inboundSchema: z.ZodMiniType<
  PostV3ContainerTagsMergeResponse,
  unknown
> = z.object({
  success: types.boolean(),
  status: PostV3ContainerTagsMergeStatus$inboundSchema,
  mergeId: types.string(),
  targetTag: types.string(),
  sourceTags: z.array(types.string()),
});

export function postV3ContainerTagsMergeResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostV3ContainerTagsMergeResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV3ContainerTagsMergeResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV3ContainerTagsMergeResponse' from JSON`,
  );
}
