/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a6cc99b23e59
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { ClosedEnum, OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type PostV4SearchInclude = {
  documents?: boolean | undefined;
  summaries?: boolean | undefined;
  relatedMemories?: boolean | undefined;
  /**
   * If true, include forgotten memories in search results. Forgotten memories are memories that have been explicitly forgotten or have passed their expiration date.
   */
  forgottenMemories?: boolean | undefined;
  /**
   * DEPRECATED: Use searchMode='hybrid' instead. If true, automatically switches to hybrid mode. This field is kept for backward compatibility only.
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  chunks?: boolean | undefined;
};

/**
 * Search mode. 'memories' searches only memory entries (default). 'hybrid' searches both memories and document chunks. 'documents' searches only document chunks.
 */
export const SearchMode = {
  Memories: "memories",
  Hybrid: "hybrid",
  Documents: "documents",
} as const;
/**
 * Search mode. 'memories' searches only memory entries (default). 'hybrid' searches both memories and document chunks. 'documents' searches only document chunks.
 */
export type SearchMode = ClosedEnum<typeof SearchMode>;

export type PostV4SearchRequest = {
  /**
   * Optional tag this search should be containerized by. This can be an ID for your user, a project ID, or any other identifier you wish to use to filter memories.
   */
  containerTag?: string | undefined;
  /**
   * Optional tags this search should be containerized by. Search is scoped to memories under these tags.
   */
  containerTags?: Array<string> | undefined;
  /**
   * Threshold / sensitivity for memories selection. 0 is least sensitive (returns most memories, more results), 1 is most sensitive (returns lesser memories, accurate results)
   */
  threshold?: number | undefined;
  /**
   * Root query object that must contain either an AND or OR array of filter expressions
   */
  filters?: models.QueryFilterUnion | undefined;
  include?: PostV4SearchInclude | undefined;
  /**
   * Maximum number of results to return
   */
  limit?: number | undefined;
  /**
   * Search query string
   */
  q: string;
  /**
   * If true, rerank the results based on the query. This is helpful if you want to ensure the most relevant results are returned.
   */
  rerank?: boolean | undefined;
  /**
   * If true, aggregates information from multiple memories to create new synthesized memories. The result will be a mix of aggregated and non-aggregated memories, reranked by relevance to the query. Works in conjunction with reranking.
   */
  aggregate?: boolean | undefined;
  /**
   * If true, rewrites the query to make it easier to find documents. This increases the latency by about 400ms
   */
  rewriteQuery?: boolean | undefined;
  /**
   * Search mode. 'memories' searches only memory entries (default). 'hybrid' searches both memories and document chunks. 'documents' searches only document chunks.
   */
  searchMode?: SearchMode | undefined;
  /**
   * Filter search results by filepath. Exact match for full paths, prefix match if ending with /
   */
  filepath?: string | undefined;
};

/**
 * Relation type between this memory and its parent/child
 */
export const PostV4SearchParentRelation = {
  Updates: "updates",
  Extends: "extends",
  Derives: "derives",
} as const;
/**
 * Relation type between this memory and its parent/child
 */
export type PostV4SearchParentRelation = OpenEnum<
  typeof PostV4SearchParentRelation
>;

export type PostV4SearchParent = {
  /**
   * Relation type between this memory and its parent/child
   */
  relation: PostV4SearchParentRelation;
  /**
   * Relative version distance from the primary memory (-1 for direct parent, -2 for grand-parent, etc.)
   */
  version?: number | null | undefined;
  /**
   * The contextual memory content
   */
  memory: string;
  /**
   * Contextual memory metadata
   */
  metadata?: { [k: string]: any } | null | undefined;
  /**
   * Contextual memory last update date
   */
  updatedAt: string;
};

/**
 * Relation type between this memory and its parent/child
 */
export const PostV4SearchChildRelation = {
  Updates: "updates",
  Extends: "extends",
  Derives: "derives",
} as const;
/**
 * Relation type between this memory and its parent/child
 */
export type PostV4SearchChildRelation = OpenEnum<
  typeof PostV4SearchChildRelation
>;

export type PostV4SearchChild = {
  /**
   * Relation type between this memory and its parent/child
   */
  relation: PostV4SearchChildRelation;
  /**
   * Relative version distance from the primary memory (+1 for direct child, +2 for grand-child, etc.)
   */
  version?: number | null | undefined;
  /**
   * The contextual memory content
   */
  memory: string;
  /**
   * Contextual memory metadata
   */
  metadata?: { [k: string]: any } | null | undefined;
  /**
   * Contextual memory last update date
   */
  updatedAt: string;
};

/**
 * Relation type
 */
export const PostV4SearchRelatedRelation = {
  Extends: "extends",
  Derives: "derives",
} as const;
/**
 * Relation type
 */
export type PostV4SearchRelatedRelation = OpenEnum<
  typeof PostV4SearchRelatedRelation
>;

export type PostV4SearchRelated = {
  /**
   * Relation type
   */
  relation: PostV4SearchRelatedRelation;
  /**
   * The related memory content
   */
  memory: string;
  /**
   * Related memory metadata
   */
  metadata?: { [k: string]: any } | null | undefined;
  /**
   * Related memory last update date
   */
  updatedAt: string;
};

/**
 * Object containing version history (parents/children via updates) and related memories (extends/derives)
 */
export type PostV4SearchContext = {
  parents?: Array<PostV4SearchParent> | undefined;
  children?: Array<PostV4SearchChild> | undefined;
  related?: Array<PostV4SearchRelated> | undefined;
};

export type PostV4SearchDocument = {
  /**
   * Document ID
   */
  id: string;
  /**
   * Document title (only included when documents=true)
   */
  title?: string | undefined;
  /**
   * Document type (only included when documents=true)
   */
  type?: string | undefined;
  /**
   * Document metadata (only included when documents=true)
   */
  metadata?: { [k: string]: any } | null | undefined;
  /**
   * Document summary (only included when summaries=true)
   */
  summary?: string | null | undefined;
  /**
   * Document creation date
   */
  createdAt: string;
  /**
   * Document last update date
   */
  updatedAt: string;
};

export type PostV4SearchChunk = {
  /**
   * Content of the chunk
   */
  content: string;
  /**
   * Position of chunk in the document (0-indexed)
   */
  position: number;
  /**
   * ID of the document this chunk belongs to
   */
  documentId: string;
};

export type PostV4SearchResult = {
  /**
   * Memory entry ID or chunk ID
   */
  id: string;
  /**
   * The memory content (only present for memory results)
   */
  memory?: string | undefined;
  /**
   * The chunk content (only present for chunk results from hybrid search)
   */
  chunk?: string | undefined;
  /**
   * Memory metadata
   */
  metadata: { [k: string]: any } | null;
  /**
   * Memory last update date
   */
  updatedAt: string;
  /**
   * Similarity score between the query and memory entry
   */
  similarity: number;
  /**
   * Filepath of the source document this memory or chunk came from
   */
  filepath?: string | null | undefined;
  /**
   * Version number of this memory entry
   */
  version?: number | null | undefined;
  /**
   * ID of the root (first version) memory entry this one descends from. Null for memories that have never been superseded. Only present on memory results, not on standalone chunk results.
   */
  rootMemoryId?: string | null | undefined;
  /**
   * Object containing version history (parents/children via updates) and related memories (extends/derives)
   */
  context?: PostV4SearchContext | undefined;
  /**
   * Associated documents for this memory entry
   */
  documents?: Array<PostV4SearchDocument> | undefined;
  /**
   * Relevant chunks from associated documents (only included when chunks=true)
   */
  chunks?: Array<PostV4SearchChunk> | undefined;
  /**
   * Indicates if this memory was created by aggregating multiple source memories
   */
  isAggregated?: boolean | undefined;
};

/**
 * Memory search results
 */
export type PostV4SearchResponse = {
  /**
   * Array of matching memory entries and chunks with similarity scores. Contains memory results when searchMode='memories', both memory and chunk results when searchMode='hybrid', or only chunk results when searchMode='documents'. Memory results have 'memory' field, chunk results have 'chunk' field. BACKWARD COMPATIBILITY: When using deprecated include.chunks=true, only memory results are returned with chunks embedded in them (old format).
   */
  results: Array<PostV4SearchResult>;
  /**
   * Search execution time in milliseconds
   */
  timing: number;
  /**
   * Total number of results returned
   */
  total: number;
};

/** @internal */
export type PostV4SearchInclude$Outbound = {
  documents: boolean;
  summaries: boolean;
  relatedMemories: boolean;
  forgottenMemories: boolean;
  chunks: boolean;
};

/** @internal */
export const PostV4SearchInclude$outboundSchema: z.ZodMiniType<
  PostV4SearchInclude$Outbound,
  PostV4SearchInclude
> = z.object({
  documents: z._default(z.boolean(), false),
  summaries: z._default(z.boolean(), false),
  relatedMemories: z._default(z.boolean(), false),
  forgottenMemories: z._default(z.boolean(), false),
  chunks: z._default(z.boolean(), false),
});

export function postV4SearchIncludeToJSON(
  postV4SearchInclude: PostV4SearchInclude,
): string {
  return JSON.stringify(
    PostV4SearchInclude$outboundSchema.parse(postV4SearchInclude),
  );
}

/** @internal */
export const SearchMode$outboundSchema: z.ZodMiniEnum<typeof SearchMode> = z
  .enum(SearchMode);

/** @internal */
export type PostV4SearchRequest$Outbound = {
  containerTag?: string | undefined;
  containerTags?: Array<string> | undefined;
  threshold: number;
  filters?: models.QueryFilterUnion$Outbound | undefined;
  include?: PostV4SearchInclude$Outbound | undefined;
  limit: number;
  q: string;
  rerank: boolean;
  aggregate: boolean;
  rewriteQuery: boolean;
  searchMode: string;
  filepath?: string | undefined;
};

/** @internal */
export const PostV4SearchRequest$outboundSchema: z.ZodMiniType<
  PostV4SearchRequest$Outbound,
  PostV4SearchRequest
> = z.object({
  containerTag: z.optional(z.string()),
  containerTags: z.optional(z.array(z.string())),
  threshold: z._default(z.number(), 0.6),
  filters: z.optional(models.QueryFilterUnion$outboundSchema),
  include: z.optional(z.lazy(() => PostV4SearchInclude$outboundSchema)),
  limit: z._default(z.int(), 10),
  q: z.string(),
  rerank: z._default(z.boolean(), false),
  aggregate: z._default(z.boolean(), false),
  rewriteQuery: z._default(z.boolean(), false),
  searchMode: z._default(SearchMode$outboundSchema, "memories"),
  filepath: z.optional(z.string()),
});

export function postV4SearchRequestToJSON(
  postV4SearchRequest: PostV4SearchRequest,
): string {
  return JSON.stringify(
    PostV4SearchRequest$outboundSchema.parse(postV4SearchRequest),
  );
}

/** @internal */
export const PostV4SearchParentRelation$inboundSchema: z.ZodMiniType<
  PostV4SearchParentRelation,
  unknown
> = openEnums.inboundSchema(PostV4SearchParentRelation);

/** @internal */
export const PostV4SearchParent$inboundSchema: z.ZodMiniType<
  PostV4SearchParent,
  unknown
> = z.object({
  relation: PostV4SearchParentRelation$inboundSchema,
  version: z.optional(z.nullable(types.number())),
  memory: types.string(),
  metadata: z.optional(z.nullable(z.record(z.string(), z.any()))),
  updatedAt: types.string(),
});

export function postV4SearchParentFromJSON(
  jsonString: string,
): SafeParseResult<PostV4SearchParent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV4SearchParent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV4SearchParent' from JSON`,
  );
}

/** @internal */
export const PostV4SearchChildRelation$inboundSchema: z.ZodMiniType<
  PostV4SearchChildRelation,
  unknown
> = openEnums.inboundSchema(PostV4SearchChildRelation);

/** @internal */
export const PostV4SearchChild$inboundSchema: z.ZodMiniType<
  PostV4SearchChild,
  unknown
> = z.object({
  relation: PostV4SearchChildRelation$inboundSchema,
  version: z.optional(z.nullable(types.number())),
  memory: types.string(),
  metadata: z.optional(z.nullable(z.record(z.string(), z.any()))),
  updatedAt: types.string(),
});

export function postV4SearchChildFromJSON(
  jsonString: string,
): SafeParseResult<PostV4SearchChild, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV4SearchChild$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV4SearchChild' from JSON`,
  );
}

/** @internal */
export const PostV4SearchRelatedRelation$inboundSchema: z.ZodMiniType<
  PostV4SearchRelatedRelation,
  unknown
> = openEnums.inboundSchema(PostV4SearchRelatedRelation);

/** @internal */
export const PostV4SearchRelated$inboundSchema: z.ZodMiniType<
  PostV4SearchRelated,
  unknown
> = z.object({
  relation: PostV4SearchRelatedRelation$inboundSchema,
  memory: types.string(),
  metadata: z.optional(z.nullable(z.record(z.string(), z.any()))),
  updatedAt: types.string(),
});

export function postV4SearchRelatedFromJSON(
  jsonString: string,
): SafeParseResult<PostV4SearchRelated, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV4SearchRelated$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV4SearchRelated' from JSON`,
  );
}

/** @internal */
export const PostV4SearchContext$inboundSchema: z.ZodMiniType<
  PostV4SearchContext,
  unknown
> = z.object({
  parents: types.optional(
    z.array(z.lazy(() => PostV4SearchParent$inboundSchema)),
  ),
  children: types.optional(
    z.array(z.lazy(() => PostV4SearchChild$inboundSchema)),
  ),
  related: types.optional(
    z.array(z.lazy(() => PostV4SearchRelated$inboundSchema)),
  ),
});

export function postV4SearchContextFromJSON(
  jsonString: string,
): SafeParseResult<PostV4SearchContext, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV4SearchContext$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV4SearchContext' from JSON`,
  );
}

/** @internal */
export const PostV4SearchDocument$inboundSchema: z.ZodMiniType<
  PostV4SearchDocument,
  unknown
> = z.object({
  id: types.string(),
  title: types.optional(types.string()),
  type: types.optional(types.string()),
  metadata: z.optional(z.nullable(z.record(z.string(), z.any()))),
  summary: z.optional(z.nullable(types.string())),
  createdAt: types.string(),
  updatedAt: types.string(),
});

export function postV4SearchDocumentFromJSON(
  jsonString: string,
): SafeParseResult<PostV4SearchDocument, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV4SearchDocument$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV4SearchDocument' from JSON`,
  );
}

/** @internal */
export const PostV4SearchChunk$inboundSchema: z.ZodMiniType<
  PostV4SearchChunk,
  unknown
> = z.object({
  content: types.string(),
  position: types.number(),
  documentId: types.string(),
});

export function postV4SearchChunkFromJSON(
  jsonString: string,
): SafeParseResult<PostV4SearchChunk, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV4SearchChunk$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV4SearchChunk' from JSON`,
  );
}

/** @internal */
export const PostV4SearchResult$inboundSchema: z.ZodMiniType<
  PostV4SearchResult,
  unknown
> = z.object({
  id: types.string(),
  memory: types.optional(types.string()),
  chunk: types.optional(types.string()),
  metadata: types.nullable(z.record(z.string(), z.any())),
  updatedAt: types.string(),
  similarity: types.number(),
  filepath: z.optional(z.nullable(types.string())),
  version: z.optional(z.nullable(types.number())),
  rootMemoryId: z.optional(z.nullable(types.string())),
  context: types.optional(z.lazy(() => PostV4SearchContext$inboundSchema)),
  documents: types.optional(
    z.array(z.lazy(() => PostV4SearchDocument$inboundSchema)),
  ),
  chunks: types.optional(
    z.array(z.lazy(() => PostV4SearchChunk$inboundSchema)),
  ),
  isAggregated: types.optional(types.boolean()),
});

export function postV4SearchResultFromJSON(
  jsonString: string,
): SafeParseResult<PostV4SearchResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV4SearchResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV4SearchResult' from JSON`,
  );
}

/** @internal */
export const PostV4SearchResponse$inboundSchema: z.ZodMiniType<
  PostV4SearchResponse,
  unknown
> = z.object({
  results: z.array(z.lazy(() => PostV4SearchResult$inboundSchema)),
  timing: types.number(),
  total: types.number(),
});

export function postV4SearchResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostV4SearchResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV4SearchResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV4SearchResponse' from JSON`,
  );
}
