/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 35092cf96ffe
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { ClosedEnum, OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

/**
 * Number of items per page
 */
export type PostV4MemoriesListLimit = string | number;

/**
 * Sort order
 */
export const PostV4MemoriesListOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
/**
 * Sort order
 */
export type PostV4MemoriesListOrder = ClosedEnum<
  typeof PostV4MemoriesListOrder
>;

/**
 * Page number to fetch
 */
export type PostV4MemoriesListPage = string | number;

/**
 * Field to sort by
 */
export const PostV4MemoriesListSort = {
  CreatedAt: "createdAt",
  UpdatedAt: "updatedAt",
} as const;
/**
 * Field to sort by
 */
export type PostV4MemoriesListSort = ClosedEnum<typeof PostV4MemoriesListSort>;

/**
 * Query parameters for listing memory entries with history
 */
export type PostV4MemoriesListRequest = {
  /**
   * Container tags to filter memory entries. At least one tag is required.
   */
  containerTags: Array<string>;
  /**
   * Root query object that must contain either an AND or OR array of filter expressions
   */
  filters?: models.QueryFilterUnion | undefined;
  /**
   * Number of items per page
   */
  limit?: string | number | undefined;
  /**
   * Sort order
   */
  order?: PostV4MemoriesListOrder | undefined;
  /**
   * Page number to fetch
   */
  page?: string | number | undefined;
  /**
   * Field to sort by
   */
  sort?: PostV4MemoriesListSort | undefined;
};

export const MemoryRelations = {
  Updates: "updates",
  Extends: "extends",
  Derives: "derives",
} as const;
export type MemoryRelations = OpenEnum<typeof MemoryRelations>;

/**
 * Historical version of a memory entry
 */
export type History = {
  id: string;
  memory: string;
  version: number;
  createdAt: string;
  updatedAt: string;
  parentMemoryId: string | null;
  rootMemoryId: string | null;
  isLatest: boolean;
  isForgotten: boolean;
};

/**
 * Memory entry with history and document references
 */
export type MemoryEntry = {
  /**
   * Unique identifier for the memory entry
   */
  id: string;
  /**
   * The memory content/text
   */
  memory: string;
  /**
   * Version number of this memory
   */
  version: number;
  /**
   * Whether this is the latest version
   */
  isLatest: boolean;
  /**
   * Whether this memory has been forgotten
   */
  isForgotten: boolean;
  /**
   * Whether this is a static profile memory
   */
  isStatic: boolean;
  /**
   * Whether this is an inferred memory
   */
  isInference: boolean | null;
  /**
   * ISO timestamp of creation
   */
  createdAt: string;
  /**
   * ISO timestamp of last update
   */
  updatedAt: string;
  /**
   * ID of the space this memory belongs to
   */
  spaceId: string;
  /**
   * Organization ID
   */
  orgId: string;
  /**
   * Number of source documents for this memory
   */
  sourceCount: number;
  /**
   * ID of the parent memory (previous version)
   */
  parentMemoryId: string | null;
  /**
   * ID of the root memory (first version)
   */
  rootMemoryId: string | null;
  /**
   * ISO timestamp when memory should be forgotten
   */
  forgetAfter: string | null;
  /**
   * Reason for forgetting
   */
  forgetReason: string | null;
  /**
   * Metadata including temporal context and other information
   */
  metadata: { [k: string]: any } | null;
  /**
   * Relations to other memories
   */
  memoryRelations: { [k: string]: MemoryRelations } | null;
  /**
   * Temporal context metadata (alias for metadata field)
   */
  temporalContext: { [k: string]: any } | null;
  /**
   * Previous versions of this memory
   */
  history: Array<History>;
  /**
   * IDs of source documents for this memory
   */
  documentIds: Array<string>;
};

/**
 * Pagination metadata
 */
export type PostV4MemoriesListPagination = {
  currentPage: number;
  limit: number;
  totalItems: number;
  totalPages: number;
};

/**
 * List of memory entries with their history and source documents
 */
export type PostV4MemoriesListResponse = {
  memoryEntries: Array<MemoryEntry>;
  /**
   * Pagination metadata
   */
  pagination: PostV4MemoriesListPagination;
};

/** @internal */
export type PostV4MemoriesListLimit$Outbound = string | number;

/** @internal */
export const PostV4MemoriesListLimit$outboundSchema: z.ZodMiniType<
  PostV4MemoriesListLimit$Outbound,
  PostV4MemoriesListLimit
> = smartUnion([z.string(), z.number()]);

export function postV4MemoriesListLimitToJSON(
  postV4MemoriesListLimit: PostV4MemoriesListLimit,
): string {
  return JSON.stringify(
    PostV4MemoriesListLimit$outboundSchema.parse(postV4MemoriesListLimit),
  );
}

/** @internal */
export const PostV4MemoriesListOrder$outboundSchema: z.ZodMiniEnum<
  typeof PostV4MemoriesListOrder
> = z.enum(PostV4MemoriesListOrder);

/** @internal */
export type PostV4MemoriesListPage$Outbound = string | number;

/** @internal */
export const PostV4MemoriesListPage$outboundSchema: z.ZodMiniType<
  PostV4MemoriesListPage$Outbound,
  PostV4MemoriesListPage
> = smartUnion([z.string(), z.number()]);

export function postV4MemoriesListPageToJSON(
  postV4MemoriesListPage: PostV4MemoriesListPage,
): string {
  return JSON.stringify(
    PostV4MemoriesListPage$outboundSchema.parse(postV4MemoriesListPage),
  );
}

/** @internal */
export const PostV4MemoriesListSort$outboundSchema: z.ZodMiniEnum<
  typeof PostV4MemoriesListSort
> = z.enum(PostV4MemoriesListSort);

/** @internal */
export type PostV4MemoriesListRequest$Outbound = {
  containerTags: Array<string>;
  filters?: models.QueryFilterUnion$Outbound | undefined;
  limit?: string | number | undefined;
  order: string;
  page?: string | number | undefined;
  sort: string;
};

/** @internal */
export const PostV4MemoriesListRequest$outboundSchema: z.ZodMiniType<
  PostV4MemoriesListRequest$Outbound,
  PostV4MemoriesListRequest
> = z.object({
  containerTags: z.array(z.string()),
  filters: z.optional(models.QueryFilterUnion$outboundSchema),
  limit: z.optional(smartUnion([z.string(), z.number()])),
  order: z._default(PostV4MemoriesListOrder$outboundSchema, "desc"),
  page: z.optional(smartUnion([z.string(), z.number()])),
  sort: z._default(PostV4MemoriesListSort$outboundSchema, "createdAt"),
});

export function postV4MemoriesListRequestToJSON(
  postV4MemoriesListRequest: PostV4MemoriesListRequest,
): string {
  return JSON.stringify(
    PostV4MemoriesListRequest$outboundSchema.parse(postV4MemoriesListRequest),
  );
}

/** @internal */
export const MemoryRelations$inboundSchema: z.ZodMiniType<
  MemoryRelations,
  unknown
> = openEnums.inboundSchema(MemoryRelations);

/** @internal */
export const History$inboundSchema: z.ZodMiniType<History, unknown> = z.object({
  id: types.string(),
  memory: types.string(),
  version: types.number(),
  createdAt: types.string(),
  updatedAt: types.string(),
  parentMemoryId: types.nullable(types.string()),
  rootMemoryId: types.nullable(types.string()),
  isLatest: types.boolean(),
  isForgotten: types.boolean(),
});

export function historyFromJSON(
  jsonString: string,
): SafeParseResult<History, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => History$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'History' from JSON`,
  );
}

/** @internal */
export const MemoryEntry$inboundSchema: z.ZodMiniType<MemoryEntry, unknown> = z
  .object({
    id: types.string(),
    memory: types.string(),
    version: types.number(),
    isLatest: types.boolean(),
    isForgotten: types.boolean(),
    isStatic: types.boolean(),
    isInference: types.nullable(types.boolean()),
    createdAt: types.string(),
    updatedAt: types.string(),
    spaceId: types.string(),
    orgId: types.string(),
    sourceCount: types.number(),
    parentMemoryId: types.nullable(types.string()),
    rootMemoryId: types.nullable(types.string()),
    forgetAfter: types.nullable(types.string()),
    forgetReason: types.nullable(types.string()),
    metadata: types.nullable(z.record(z.string(), z.any())),
    memoryRelations: types.nullable(
      z.record(z.string(), MemoryRelations$inboundSchema),
    ),
    temporalContext: types.nullable(z.record(z.string(), z.any())),
    history: z.array(z.lazy(() => History$inboundSchema)),
    documentIds: z.array(types.string()),
  });

export function memoryEntryFromJSON(
  jsonString: string,
): SafeParseResult<MemoryEntry, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MemoryEntry$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MemoryEntry' from JSON`,
  );
}

/** @internal */
export const PostV4MemoriesListPagination$inboundSchema: z.ZodMiniType<
  PostV4MemoriesListPagination,
  unknown
> = z.object({
  currentPage: types.number(),
  limit: z._default(types.number(), 10),
  totalItems: types.number(),
  totalPages: types.number(),
});

export function postV4MemoriesListPaginationFromJSON(
  jsonString: string,
): SafeParseResult<PostV4MemoriesListPagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV4MemoriesListPagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV4MemoriesListPagination' from JSON`,
  );
}

/** @internal */
export const PostV4MemoriesListResponse$inboundSchema: z.ZodMiniType<
  PostV4MemoriesListResponse,
  unknown
> = z.object({
  memoryEntries: z.array(z.lazy(() => MemoryEntry$inboundSchema)),
  pagination: z.lazy(() => PostV4MemoriesListPagination$inboundSchema),
});

export function postV4MemoriesListResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostV4MemoriesListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV4MemoriesListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV4MemoriesListResponse' from JSON`,
  );
}
