/*
 * Generated by scripts/surface/generate.ts from fern/openapi.json. DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as types from "../../types/primitives.js";

/**
 * selected (default) syncs only files the user picks. full syncs the whole Drive.
 */
export const PostNsByNamespaceConnectorsRequestBody5ConfigSyncScope = {
  Selected: "selected",
  Full: "full",
} as const;
/**
 * selected (default) syncs only files the user picks. full syncs the whole Drive.
 */
export type PostNsByNamespaceConnectorsRequestBody5ConfigSyncScope = ClosedEnum<typeof PostNsByNamespaceConnectorsRequestBody5ConfigSyncScope>;

/** @internal */
export const PostNsByNamespaceConnectorsRequestBody5ConfigSyncScope$outboundSchema: z.ZodMiniEnum<typeof PostNsByNamespaceConnectorsRequestBody5ConfigSyncScope> = z.enum(PostNsByNamespaceConnectorsRequestBody5ConfigSyncScope);

export type PostNsByNamespaceConnectorsRequestBody =
  | PostNsByNamespaceConnectorsRequestBody1
  | PostNsByNamespaceConnectorsRequestBody2
  | PostNsByNamespaceConnectorsRequestBody3
  | PostNsByNamespaceConnectorsRequestBody4
  | PostNsByNamespaceConnectorsRequestBody5
  | PostNsByNamespaceConnectorsRequestBody6
  | PostNsByNamespaceConnectorsRequestBody7
  | PostNsByNamespaceConnectorsRequestBody8
;

/** @internal */
export type PostNsByNamespaceConnectorsRequestBody$Outbound =
  | PostNsByNamespaceConnectorsRequestBody1$Outbound
  | PostNsByNamespaceConnectorsRequestBody2$Outbound
  | PostNsByNamespaceConnectorsRequestBody3$Outbound
  | PostNsByNamespaceConnectorsRequestBody4$Outbound
  | PostNsByNamespaceConnectorsRequestBody5$Outbound
  | PostNsByNamespaceConnectorsRequestBody6$Outbound
  | PostNsByNamespaceConnectorsRequestBody7$Outbound
  | PostNsByNamespaceConnectorsRequestBody8$Outbound
;

/** @internal */
export const PostNsByNamespaceConnectorsRequestBody$outboundSchema: z.ZodMiniType<PostNsByNamespaceConnectorsRequestBody$Outbound, PostNsByNamespaceConnectorsRequestBody> = smartUnion([
  z.lazy(() => PostNsByNamespaceConnectorsRequestBody1$outboundSchema),
  z.lazy(() => PostNsByNamespaceConnectorsRequestBody2$outboundSchema),
  z.lazy(() => PostNsByNamespaceConnectorsRequestBody3$outboundSchema),
  z.lazy(() => PostNsByNamespaceConnectorsRequestBody4$outboundSchema),
  z.lazy(() => PostNsByNamespaceConnectorsRequestBody5$outboundSchema),
  z.lazy(() => PostNsByNamespaceConnectorsRequestBody6$outboundSchema),
  z.lazy(() => PostNsByNamespaceConnectorsRequestBody7$outboundSchema),
  z.lazy(() => PostNsByNamespaceConnectorsRequestBody8$outboundSchema),
]);

export function postNsByNamespaceConnectorsRequestBodyToJSON(
  postNsByNamespaceConnectorsRequestBody: PostNsByNamespaceConnectorsRequestBody,
): string {
  return JSON.stringify(PostNsByNamespaceConnectorsRequestBody$outboundSchema.parse(postNsByNamespaceConnectorsRequestBody));
}

export type PostNsByNamespaceConnectorsRequestBody1 = {
  provider: "notion";
  /**
   * Where the user returns after authorizing with the provider
   */
  redirectUrl?: string | undefined;
  /**
   * Maximum documents this connector imports
   */
  documentLimit?: number | undefined;
};

/** @internal */
export type PostNsByNamespaceConnectorsRequestBody1$Outbound = {
  provider: "notion";
  /**
   * Where the user returns after authorizing with the provider
   */
  redirectUrl?: string | undefined;
  /**
   * Maximum documents this connector imports
   */
  documentLimit?: number | undefined;
};

/** @internal */
export const PostNsByNamespaceConnectorsRequestBody1$outboundSchema: z.ZodMiniType<PostNsByNamespaceConnectorsRequestBody1$Outbound, PostNsByNamespaceConnectorsRequestBody1> = z.object({
  provider: z.literal("notion"),
  redirectUrl: z.optional(z.string()),
  documentLimit: z.optional(z.int()),
});

export function postNsByNamespaceConnectorsRequestBody1ToJSON(
  postNsByNamespaceConnectorsRequestBody1: PostNsByNamespaceConnectorsRequestBody1,
): string {
  return JSON.stringify(PostNsByNamespaceConnectorsRequestBody1$outboundSchema.parse(postNsByNamespaceConnectorsRequestBody1));
}

export type PostNsByNamespaceConnectorsRequestBody2 = {
  provider: "gmail";
  /**
   * Where the user returns after authorizing with the provider
   */
  redirectUrl?: string | undefined;
  /**
   * Maximum documents this connector imports
   */
  documentLimit?: number | undefined;
};

/** @internal */
export type PostNsByNamespaceConnectorsRequestBody2$Outbound = {
  provider: "gmail";
  /**
   * Where the user returns after authorizing with the provider
   */
  redirectUrl?: string | undefined;
  /**
   * Maximum documents this connector imports
   */
  documentLimit?: number | undefined;
};

/** @internal */
export const PostNsByNamespaceConnectorsRequestBody2$outboundSchema: z.ZodMiniType<PostNsByNamespaceConnectorsRequestBody2$Outbound, PostNsByNamespaceConnectorsRequestBody2> = z.object({
  provider: z.literal("gmail"),
  redirectUrl: z.optional(z.string()),
  documentLimit: z.optional(z.int()),
});

export function postNsByNamespaceConnectorsRequestBody2ToJSON(
  postNsByNamespaceConnectorsRequestBody2: PostNsByNamespaceConnectorsRequestBody2,
): string {
  return JSON.stringify(PostNsByNamespaceConnectorsRequestBody2$outboundSchema.parse(postNsByNamespaceConnectorsRequestBody2));
}

export type PostNsByNamespaceConnectorsRequestBody3 = {
  provider: "onedrive";
  /**
   * Where the user returns after authorizing with the provider
   */
  redirectUrl?: string | undefined;
  /**
   * Maximum documents this connector imports
   */
  documentLimit?: number | undefined;
};

/** @internal */
export type PostNsByNamespaceConnectorsRequestBody3$Outbound = {
  provider: "onedrive";
  /**
   * Where the user returns after authorizing with the provider
   */
  redirectUrl?: string | undefined;
  /**
   * Maximum documents this connector imports
   */
  documentLimit?: number | undefined;
};

/** @internal */
export const PostNsByNamespaceConnectorsRequestBody3$outboundSchema: z.ZodMiniType<PostNsByNamespaceConnectorsRequestBody3$Outbound, PostNsByNamespaceConnectorsRequestBody3> = z.object({
  provider: z.literal("onedrive"),
  redirectUrl: z.optional(z.string()),
  documentLimit: z.optional(z.int()),
});

export function postNsByNamespaceConnectorsRequestBody3ToJSON(
  postNsByNamespaceConnectorsRequestBody3: PostNsByNamespaceConnectorsRequestBody3,
): string {
  return JSON.stringify(PostNsByNamespaceConnectorsRequestBody3$outboundSchema.parse(postNsByNamespaceConnectorsRequestBody3));
}

export type PostNsByNamespaceConnectorsRequestBody4 = {
  provider: "github";
  /**
   * Where the user returns after authorizing with the provider
   */
  redirectUrl?: string | undefined;
  /**
   * Maximum documents this connector imports
   */
  documentLimit?: number | undefined;
};

/** @internal */
export type PostNsByNamespaceConnectorsRequestBody4$Outbound = {
  provider: "github";
  /**
   * Where the user returns after authorizing with the provider
   */
  redirectUrl?: string | undefined;
  /**
   * Maximum documents this connector imports
   */
  documentLimit?: number | undefined;
};

/** @internal */
export const PostNsByNamespaceConnectorsRequestBody4$outboundSchema: z.ZodMiniType<PostNsByNamespaceConnectorsRequestBody4$Outbound, PostNsByNamespaceConnectorsRequestBody4> = z.object({
  provider: z.literal("github"),
  redirectUrl: z.optional(z.string()),
  documentLimit: z.optional(z.int()),
});

export function postNsByNamespaceConnectorsRequestBody4ToJSON(
  postNsByNamespaceConnectorsRequestBody4: PostNsByNamespaceConnectorsRequestBody4,
): string {
  return JSON.stringify(PostNsByNamespaceConnectorsRequestBody4$outboundSchema.parse(postNsByNamespaceConnectorsRequestBody4));
}

export type PostNsByNamespaceConnectorsRequestBody5 = {
  provider: "google-drive";
  /**
   * Where the user returns after authorizing with the provider
   */
  redirectUrl?: string | undefined;
  /**
   * Maximum documents this connector imports
   */
  documentLimit?: number | undefined;
  config?: PostNsByNamespaceConnectorsRequestBody5Config | undefined;
};

/** @internal */
export type PostNsByNamespaceConnectorsRequestBody5$Outbound = {
  provider: "google-drive";
  /**
   * Where the user returns after authorizing with the provider
   */
  redirectUrl?: string | undefined;
  /**
   * Maximum documents this connector imports
   */
  documentLimit?: number | undefined;
  config?: PostNsByNamespaceConnectorsRequestBody5Config$Outbound | undefined;
};

/** @internal */
export const PostNsByNamespaceConnectorsRequestBody5$outboundSchema: z.ZodMiniType<PostNsByNamespaceConnectorsRequestBody5$Outbound, PostNsByNamespaceConnectorsRequestBody5> = z.object({
  provider: z.literal("google-drive"),
  redirectUrl: z.optional(z.string()),
  documentLimit: z.optional(z.int()),
  config: z.optional(z.lazy(() => PostNsByNamespaceConnectorsRequestBody5Config$outboundSchema)),
});

export function postNsByNamespaceConnectorsRequestBody5ToJSON(
  postNsByNamespaceConnectorsRequestBody5: PostNsByNamespaceConnectorsRequestBody5,
): string {
  return JSON.stringify(PostNsByNamespaceConnectorsRequestBody5$outboundSchema.parse(postNsByNamespaceConnectorsRequestBody5));
}

export type PostNsByNamespaceConnectorsRequestBody5Config = {
  /**
   * selected (default) syncs only files the user picks. full syncs the whole Drive.
   */
  syncScope?: PostNsByNamespaceConnectorsRequestBody5ConfigSyncScope | undefined;
};

/** @internal */
export type PostNsByNamespaceConnectorsRequestBody5Config$Outbound = {
  /**
   * selected (default) syncs only files the user picks. full syncs the whole Drive.
   */
  syncScope?: string | undefined;
};

/** @internal */
export const PostNsByNamespaceConnectorsRequestBody5Config$outboundSchema: z.ZodMiniType<PostNsByNamespaceConnectorsRequestBody5Config$Outbound, PostNsByNamespaceConnectorsRequestBody5Config> = z.object({
  syncScope: z.optional(PostNsByNamespaceConnectorsRequestBody5ConfigSyncScope$outboundSchema),
});

export function postNsByNamespaceConnectorsRequestBody5ConfigToJSON(
  postNsByNamespaceConnectorsRequestBody5Config: PostNsByNamespaceConnectorsRequestBody5Config,
): string {
  return JSON.stringify(PostNsByNamespaceConnectorsRequestBody5Config$outboundSchema.parse(postNsByNamespaceConnectorsRequestBody5Config));
}

export type PostNsByNamespaceConnectorsRequestBody6 = {
  provider: "s3";
  /**
   * S3 bucket to sync. Credentials are stored encrypted and never returned.
   */
  config: PostNsByNamespaceConnectorsRequestBody6Config;
  /**
   * Maximum documents this connector imports
   */
  documentLimit?: number | undefined;
};

/** @internal */
export type PostNsByNamespaceConnectorsRequestBody6$Outbound = {
  provider: "s3";
  /**
   * S3 bucket to sync. Credentials are stored encrypted and never returned.
   */
  config: PostNsByNamespaceConnectorsRequestBody6Config$Outbound;
  /**
   * Maximum documents this connector imports
   */
  documentLimit?: number | undefined;
};

/** @internal */
export const PostNsByNamespaceConnectorsRequestBody6$outboundSchema: z.ZodMiniType<PostNsByNamespaceConnectorsRequestBody6$Outbound, PostNsByNamespaceConnectorsRequestBody6> = z.object({
  provider: z.literal("s3"),
  config: z.lazy(() => PostNsByNamespaceConnectorsRequestBody6Config$outboundSchema),
  documentLimit: z.optional(z.int()),
});

export function postNsByNamespaceConnectorsRequestBody6ToJSON(
  postNsByNamespaceConnectorsRequestBody6: PostNsByNamespaceConnectorsRequestBody6,
): string {
  return JSON.stringify(PostNsByNamespaceConnectorsRequestBody6$outboundSchema.parse(postNsByNamespaceConnectorsRequestBody6));
}

/**
 * S3 bucket to sync. Credentials are stored encrypted and never returned.
 */
export type PostNsByNamespaceConnectorsRequestBody6Config = {
  bucket: string;
  region: string;
  accessKeyId: string;
  secretAccessKey: string;
  /**
   * For S3-compatible stores such as R2 or MinIO
   */
  endpoint?: string | undefined;
  /**
   * Only sync keys under this prefix
   */
  prefix?: string | undefined;
};

/** @internal */
export type PostNsByNamespaceConnectorsRequestBody6Config$Outbound = {
  bucket: string;
  region: string;
  accessKeyId: string;
  secretAccessKey: string;
  /**
   * For S3-compatible stores such as R2 or MinIO
   */
  endpoint?: string | undefined;
  /**
   * Only sync keys under this prefix
   */
  prefix?: string | undefined;
};

/** @internal */
export const PostNsByNamespaceConnectorsRequestBody6Config$outboundSchema: z.ZodMiniType<PostNsByNamespaceConnectorsRequestBody6Config$Outbound, PostNsByNamespaceConnectorsRequestBody6Config> = z.object({
  bucket: z.string(),
  region: z.string(),
  accessKeyId: z.string(),
  secretAccessKey: z.string(),
  endpoint: z.optional(z.string()),
  prefix: z.optional(z.string()),
});

export function postNsByNamespaceConnectorsRequestBody6ConfigToJSON(
  postNsByNamespaceConnectorsRequestBody6Config: PostNsByNamespaceConnectorsRequestBody6Config,
): string {
  return JSON.stringify(PostNsByNamespaceConnectorsRequestBody6Config$outboundSchema.parse(postNsByNamespaceConnectorsRequestBody6Config));
}

export type PostNsByNamespaceConnectorsRequestBody7 = {
  provider: "web-crawler";
  /**
   * Website to crawl
   */
  config: PostNsByNamespaceConnectorsRequestBody7Config;
  /**
   * Maximum documents this connector imports
   */
  documentLimit?: number | undefined;
};

/** @internal */
export type PostNsByNamespaceConnectorsRequestBody7$Outbound = {
  provider: "web-crawler";
  /**
   * Website to crawl
   */
  config: PostNsByNamespaceConnectorsRequestBody7Config$Outbound;
  /**
   * Maximum documents this connector imports
   */
  documentLimit?: number | undefined;
};

/** @internal */
export const PostNsByNamespaceConnectorsRequestBody7$outboundSchema: z.ZodMiniType<PostNsByNamespaceConnectorsRequestBody7$Outbound, PostNsByNamespaceConnectorsRequestBody7> = z.object({
  provider: z.literal("web-crawler"),
  config: z.lazy(() => PostNsByNamespaceConnectorsRequestBody7Config$outboundSchema),
  documentLimit: z.optional(z.int()),
});

export function postNsByNamespaceConnectorsRequestBody7ToJSON(
  postNsByNamespaceConnectorsRequestBody7: PostNsByNamespaceConnectorsRequestBody7,
): string {
  return JSON.stringify(PostNsByNamespaceConnectorsRequestBody7$outboundSchema.parse(postNsByNamespaceConnectorsRequestBody7));
}

/**
 * Website to crawl
 */
export type PostNsByNamespaceConnectorsRequestBody7Config = {
  startUrl: string;
  /**
   * How many links deep to follow. Defaults to 3.
   */
  crawlDepth?: number | undefined;
};

/** @internal */
export type PostNsByNamespaceConnectorsRequestBody7Config$Outbound = {
  startUrl: string;
  /**
   * How many links deep to follow. Defaults to 3.
   */
  crawlDepth?: number | undefined;
};

/** @internal */
export const PostNsByNamespaceConnectorsRequestBody7Config$outboundSchema: z.ZodMiniType<PostNsByNamespaceConnectorsRequestBody7Config$Outbound, PostNsByNamespaceConnectorsRequestBody7Config> = z.object({
  startUrl: z.string(),
  crawlDepth: z.optional(z.int()),
});

export function postNsByNamespaceConnectorsRequestBody7ConfigToJSON(
  postNsByNamespaceConnectorsRequestBody7Config: PostNsByNamespaceConnectorsRequestBody7Config,
): string {
  return JSON.stringify(PostNsByNamespaceConnectorsRequestBody7Config$outboundSchema.parse(postNsByNamespaceConnectorsRequestBody7Config));
}

export type PostNsByNamespaceConnectorsRequestBody8 = {
  provider: "granola";
  /**
   * Granola API key. Stored encrypted and never returned.
   */
  config: PostNsByNamespaceConnectorsRequestBody8Config;
  /**
   * Maximum documents this connector imports
   */
  documentLimit?: number | undefined;
};

/** @internal */
export type PostNsByNamespaceConnectorsRequestBody8$Outbound = {
  provider: "granola";
  /**
   * Granola API key. Stored encrypted and never returned.
   */
  config: PostNsByNamespaceConnectorsRequestBody8Config$Outbound;
  /**
   * Maximum documents this connector imports
   */
  documentLimit?: number | undefined;
};

/** @internal */
export const PostNsByNamespaceConnectorsRequestBody8$outboundSchema: z.ZodMiniType<PostNsByNamespaceConnectorsRequestBody8$Outbound, PostNsByNamespaceConnectorsRequestBody8> = z.object({
  provider: z.literal("granola"),
  config: z.lazy(() => PostNsByNamespaceConnectorsRequestBody8Config$outboundSchema),
  documentLimit: z.optional(z.int()),
});

export function postNsByNamespaceConnectorsRequestBody8ToJSON(
  postNsByNamespaceConnectorsRequestBody8: PostNsByNamespaceConnectorsRequestBody8,
): string {
  return JSON.stringify(PostNsByNamespaceConnectorsRequestBody8$outboundSchema.parse(postNsByNamespaceConnectorsRequestBody8));
}

/**
 * Granola API key. Stored encrypted and never returned.
 */
export type PostNsByNamespaceConnectorsRequestBody8Config = {
  apiKey: string;
};

/** @internal */
export type PostNsByNamespaceConnectorsRequestBody8Config$Outbound = {
  apiKey: string;
};

/** @internal */
export const PostNsByNamespaceConnectorsRequestBody8Config$outboundSchema: z.ZodMiniType<PostNsByNamespaceConnectorsRequestBody8Config$Outbound, PostNsByNamespaceConnectorsRequestBody8Config> = z.object({
  apiKey: z.string(),
});

export function postNsByNamespaceConnectorsRequestBody8ConfigToJSON(
  postNsByNamespaceConnectorsRequestBody8Config: PostNsByNamespaceConnectorsRequestBody8Config,
): string {
  return JSON.stringify(PostNsByNamespaceConnectorsRequestBody8Config$outboundSchema.parse(postNsByNamespaceConnectorsRequestBody8Config));
}

export type PostNsByNamespaceConnectorsRequest = {
  namespace: string;
  body: PostNsByNamespaceConnectorsRequestBody;
};

/** @internal */
export type PostNsByNamespaceConnectorsRequest$Outbound = {
  namespace: string;
  body: PostNsByNamespaceConnectorsRequestBody$Outbound;
};

/** @internal */
export const PostNsByNamespaceConnectorsRequest$outboundSchema: z.ZodMiniType<PostNsByNamespaceConnectorsRequest$Outbound, PostNsByNamespaceConnectorsRequest> = z.object({
  namespace: z.string(),
  body: z.lazy(() => PostNsByNamespaceConnectorsRequestBody$outboundSchema),
});

export function postNsByNamespaceConnectorsRequestToJSON(
  postNsByNamespaceConnectorsRequest: PostNsByNamespaceConnectorsRequest,
): string {
  return JSON.stringify(PostNsByNamespaceConnectorsRequest$outboundSchema.parse(postNsByNamespaceConnectorsRequest));
}

export type PostNsByNamespaceConnectorsResponse = {
  /**
   * Connector identifier
   */
  id: string;
  /**
   * Send the user here to authorize the provider. Null for providers that authenticate with config only.
   */
  authUrl: string | null;
  /**
   * When authUrl stops working
   */
  authUrlExpiresAt: Date | null;
};

/** @internal */
export const PostNsByNamespaceConnectorsResponse$inboundSchema: z.ZodMiniType<PostNsByNamespaceConnectorsResponse, unknown> = z.object({
  id: types.string(),
  authUrl: types.nullable(types.string()),
  authUrlExpiresAt: types.nullable(types.date()),
});

export function postNsByNamespaceConnectorsResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostNsByNamespaceConnectorsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostNsByNamespaceConnectorsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostNsByNamespaceConnectorsResponse' from JSON`,
  );
}
