/*
 * Generated by scripts/surface/generate.ts from fern/openapi.json. DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as types from "../../types/primitives.js";

export type PutNsByNamespaceProfileBucketsRequestBody = {
  /**
   * Namespace-owned bucket names mapped to descriptions that guide memory classification. Existing names are updated; new names are added.
   */
  buckets: { [k: string]: string };
};

/** @internal */
export type PutNsByNamespaceProfileBucketsRequestBody$Outbound = {
  /**
   * Namespace-owned bucket names mapped to descriptions that guide memory classification. Existing names are updated; new names are added.
   */
  buckets: { [k: string]: string };
};

/** @internal */
export const PutNsByNamespaceProfileBucketsRequestBody$outboundSchema: z.ZodMiniType<PutNsByNamespaceProfileBucketsRequestBody$Outbound, PutNsByNamespaceProfileBucketsRequestBody> = z.object({
  buckets: z.record(z.string(), z.string()),
});

export function putNsByNamespaceProfileBucketsRequestBodyToJSON(
  putNsByNamespaceProfileBucketsRequestBody: PutNsByNamespaceProfileBucketsRequestBody,
): string {
  return JSON.stringify(PutNsByNamespaceProfileBucketsRequestBody$outboundSchema.parse(putNsByNamespaceProfileBucketsRequestBody));
}

export type PutNsByNamespaceProfileBucketsRequest = {
  namespace: string;
  body: PutNsByNamespaceProfileBucketsRequestBody;
};

/** @internal */
export type PutNsByNamespaceProfileBucketsRequest$Outbound = {
  namespace: string;
  body: PutNsByNamespaceProfileBucketsRequestBody$Outbound;
};

/** @internal */
export const PutNsByNamespaceProfileBucketsRequest$outboundSchema: z.ZodMiniType<PutNsByNamespaceProfileBucketsRequest$Outbound, PutNsByNamespaceProfileBucketsRequest> = z.object({
  namespace: z.string(),
  body: z.lazy(() => PutNsByNamespaceProfileBucketsRequestBody$outboundSchema),
});

export function putNsByNamespaceProfileBucketsRequestToJSON(
  putNsByNamespaceProfileBucketsRequest: PutNsByNamespaceProfileBucketsRequest,
): string {
  return JSON.stringify(PutNsByNamespaceProfileBucketsRequest$outboundSchema.parse(putNsByNamespaceProfileBucketsRequest));
}

export type PutNsByNamespaceProfileBucketsResponse = {
  /**
   * Effective bucket definitions keyed by name. Includes organization buckets and namespace-owned additions.
   */
  buckets: { [k: string]: string };
};

/** @internal */
export const PutNsByNamespaceProfileBucketsResponse$inboundSchema: z.ZodMiniType<PutNsByNamespaceProfileBucketsResponse, unknown> = z.object({
  buckets: z.record(z.string(), types.string()),
});

export function putNsByNamespaceProfileBucketsResponseFromJSON(
  jsonString: string,
): SafeParseResult<PutNsByNamespaceProfileBucketsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PutNsByNamespaceProfileBucketsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PutNsByNamespaceProfileBucketsResponse' from JSON`,
  );
}
