// Generates types.generated.ts: for every type exported by the published
// 5.0.0-rc.5 package, a compile-time check that this package exports a type of
// the same name that is mutually assignable with it.
//
//   bun tests/rc5-compat/gen-type-tests.ts
import ts from "typescript";

const here = new URL(".", import.meta.url).pathname;
const rc5 = new URL("../../node_modules/supermemory-rc5/src/", import.meta.url).pathname;

// Public modules of rc.5 and where the same names live here.
const MODULES: Array<[string, string]> = [
  ["index.ts", "../../src/index.js"],
  ["models/index.ts", "../../src/models/index.js"],
  ["models/operations/index.ts", "../../src/models/operations/index.js"],
  ["models/errors/index.ts", "../../src/models/errors/index.js"],
  ["types/index.ts", "../../src/types/index.js"],
  ["lib/http.ts", "../../src/lib/http.js"],
  ["lib/retries.ts", "../../src/lib/retries.js"],
  ["lib/sdks.ts", "../../src/lib/sdks.js"],
  ["lib/config.ts", "../../src/lib/config.js"],
];

const program = ts.createProgram(
  MODULES.map(([m]) => rc5 + m),
  { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.ESNext, moduleResolution: ts.ModuleResolutionKind.Bundler, skipLibCheck: true, noEmit: true },
);
const checker = program.getTypeChecker();

let out = `// Generated by gen-type-tests.ts. DO NOT EDIT.
// Every type exported by supermemory@5.0.0-rc.5 must exist here and be
// mutually assignable (rc.5's open-enum brand symbol is normalized away).
/* eslint-disable */
import type { Mutual, Superset } from "./type-helpers.js";
`;
let checks = "";
let count = 0;
MODULES.forEach(([m, ours], i) => {
  const sf = program.getSourceFile(rc5 + m)!;
  const sym = checker.getSymbolAtLocation(sf)!;
  const names = checker
    .getExportsOfModule(sym)
    .map((s) => (s.flags & ts.SymbolFlags.Alias ? checker.getAliasedSymbol(s) : s))
    .filter((s) => s.flags & (ts.SymbolFlags.TypeAlias | ts.SymbolFlags.Interface | ts.SymbolFlags.Class))
    .filter((s) => !(s.declarations ?? []).some((d) => ts.getJSDocTags(d).some((t) => t.tagName.text === "internal")))
    .map((s) => s.name)
    .filter((n, j, a) => a.indexOf(n) === j && n !== "default")
    .sort();
  out += `import type * as R${i} from "../../node_modules/supermemory-rc5/src/${m.replace(/\.ts$/, ".js")}";\nimport type * as N${i} from "${ours}";\n`;
  for (const n of names) {
    // Generic helpers (Result<T, E>, OpenEnum<T>, …) are checked with their parameters erased.
    let s = checker.getExportsOfModule(sym).find((x) => x.name === n)!;
    if (s.flags & ts.SymbolFlags.Alias) s = checker.getAliasedSymbol(s);
    const d = s.declarations?.[0] as ts.TypeAliasDeclaration | ts.ClassDeclaration | ts.InterfaceDeclaration | undefined;
    const generic = d?.typeParameters?.filter((p) => !p.default).length ?? 0;
    const ref = (ns: string) => (generic ? `${ns}.${n}<${Array.from({ length: generic }, () => "any").join(", ")}>` : `${ns}.${n}`);
    // The client class gains groups for endpoints added after rc.5 (connectors),
    // so it only has to offer everything rc.5's did.
    const rel = n === "Supermemory" ? "Superset" : "Mutual";
    checks += `export const _${i}_${n}: ${rel}<${ref(`R${i}`)}, ${ref(`N${i}`)}> = true;\n`;
    count++;
  }
});
await Bun.write(`${here}types.generated.ts`, out + "\n" + checks);
console.log(`wrote ${count} type checks`);
