/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b69f4caa2ae7
 */

import * as z from "zod/v4-mini";
import { smartUnion } from "../types/smart-union.js";
import {
  FilterPredicateUnion,
  FilterPredicateUnion$Outbound,
  FilterPredicateUnion$outboundSchema,
} from "./filter-predicate-union.js";

export type FilterExpressionAnd1 = {
  /**
   * Require every nested filter expression to match
   */
  operator: "and";
  /**
   * Filter expressions combined with logical AND
   */
  operands: Array<
    FilterExpressionAnd1 | FilterExpressionOr1 | FilterPredicateUnion
  >;
};

/**
 * A type-safe metadata filter predicate or nested and/or expression. The API validates up to 5 levels of nesting.
 */
export type FilterExpression =
  | FilterExpressionAnd1
  | FilterExpressionOr1
  | FilterPredicateUnion;

export type FilterExpressionOr1 = {
  /**
   * Require at least one nested filter expression to match
   */
  operator: "or";
  /**
   * Filter expressions combined with logical OR
   */
  operands: Array<
    FilterExpressionAnd1 | FilterExpressionOr1 | FilterPredicateUnion
  >;
};

/** @internal */
export type FilterExpressionAnd1$Outbound = {
  operator: "and";
  operands: Array<
    | FilterExpressionAnd1$Outbound
    | FilterExpressionOr1$Outbound
    | FilterPredicateUnion$Outbound
  >;
};

/** @internal */
export const FilterExpressionAnd1$outboundSchema: z.ZodMiniType<
  FilterExpressionAnd1$Outbound,
  FilterExpressionAnd1
> = z.object({
  operator: z.literal("and"),
  operands: z.array(
    smartUnion([
      z.lazy(() => FilterExpressionAnd1$outboundSchema),
      z.lazy(() => FilterExpressionOr1$outboundSchema),
      FilterPredicateUnion$outboundSchema,
    ]),
  ),
});

export function filterExpressionAnd1ToJSON(
  filterExpressionAnd1: FilterExpressionAnd1,
): string {
  return JSON.stringify(
    FilterExpressionAnd1$outboundSchema.parse(filterExpressionAnd1),
  );
}

/** @internal */
export type FilterExpression$Outbound =
  | FilterExpressionAnd1$Outbound
  | FilterExpressionOr1$Outbound
  | FilterPredicateUnion$Outbound;

/** @internal */
export const FilterExpression$outboundSchema: z.ZodMiniType<
  FilterExpression$Outbound,
  FilterExpression
> = smartUnion([
  z.lazy(() => FilterExpressionAnd1$outboundSchema),
  z.lazy(() => FilterExpressionOr1$outboundSchema),
  FilterPredicateUnion$outboundSchema,
]);

export function filterExpressionToJSON(
  filterExpression: FilterExpression,
): string {
  return JSON.stringify(
    FilterExpression$outboundSchema.parse(filterExpression),
  );
}

/** @internal */
export type FilterExpressionOr1$Outbound = {
  operator: "or";
  operands: Array<
    | FilterExpressionAnd1$Outbound
    | FilterExpressionOr1$Outbound
    | FilterPredicateUnion$Outbound
  >;
};

/** @internal */
export const FilterExpressionOr1$outboundSchema: z.ZodMiniType<
  FilterExpressionOr1$Outbound,
  FilterExpressionOr1
> = z.object({
  operator: z.literal("or"),
  operands: z.array(
    smartUnion([
      z.lazy(() => FilterExpressionAnd1$outboundSchema),
      z.lazy(() => FilterExpressionOr1$outboundSchema),
      FilterPredicateUnion$outboundSchema,
    ]),
  ),
});

export function filterExpressionOr1ToJSON(
  filterExpressionOr1: FilterExpressionOr1,
): string {
  return JSON.stringify(
    FilterExpressionOr1$outboundSchema.parse(filterExpressionOr1),
  );
}
