/*
 * Generated by scripts/surface/generate.ts from fern/openapi.json. DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";
import { smartUnion } from "../types/smart-union.js";

/**
 * Compare the field for equality or inequality
 */
export const Operator1 = {
  Eq: "eq",
  Neq: "neq",
} as const;
/**
 * Compare the field for equality or inequality
 */
export type Operator1 = ClosedEnum<typeof Operator1>;

/** @internal */
export const Operator1$outboundSchema: z.ZodMiniEnum<typeof Operator1> = z.enum(Operator1);

/**
 * Compare the field for equality or inequality
 */
export const Operator2 = {
  Eq: "eq",
  Neq: "neq",
} as const;
/**
 * Compare the field for equality or inequality
 */
export type Operator2 = ClosedEnum<typeof Operator2>;

/** @internal */
export const Operator2$outboundSchema: z.ZodMiniEnum<typeof Operator2> = z.enum(Operator2);

/**
 * Numeric comparison to apply
 */
export const Operator3 = {
  Gt: "gt",
  Gte: "gte",
  Lt: "lt",
  Lte: "lte",
} as const;
/**
 * Numeric comparison to apply
 */
export type Operator3 = ClosedEnum<typeof Operator3>;

/** @internal */
export const Operator3$outboundSchema: z.ZodMiniEnum<typeof Operator3> = z.enum(Operator3);

/**
 * Require or exclude a substring match
 */
export const Operator4 = {
  Contains: "contains",
  NotContains: "notContains",
} as const;
/**
 * Require or exclude a substring match
 */
export type Operator4 = ClosedEnum<typeof Operator4>;

/** @internal */
export const Operator4$outboundSchema: z.ZodMiniEnum<typeof Operator4> = z.enum(Operator4);

/**
 * Require or exclude an exact array member
 */
export const Operator5 = {
  ArrayContains: "arrayContains",
  ArrayNotContains: "arrayNotContains",
} as const;
/**
 * Require or exclude an exact array member
 */
export type Operator5 = ClosedEnum<typeof Operator5>;

/** @internal */
export const Operator5$outboundSchema: z.ZodMiniEnum<typeof Operator5> = z.enum(Operator5);

export type FilterPredicateUnion =
  | FilterPredicate1
  | FilterPredicate2
  | FilterPredicate3
  | FilterPredicate4
  | FilterPredicate5
;

/** @internal */
export type FilterPredicateUnion$Outbound =
  | FilterPredicate1$Outbound
  | FilterPredicate2$Outbound
  | FilterPredicate3$Outbound
  | FilterPredicate4$Outbound
  | FilterPredicate5$Outbound
;

/** @internal */
export const FilterPredicateUnion$outboundSchema: z.ZodMiniType<FilterPredicateUnion$Outbound, FilterPredicateUnion> = smartUnion([
  z.lazy(() => FilterPredicate1$outboundSchema),
  z.lazy(() => FilterPredicate2$outboundSchema),
  z.lazy(() => FilterPredicate3$outboundSchema),
  z.lazy(() => FilterPredicate4$outboundSchema),
  z.lazy(() => FilterPredicate5$outboundSchema),
]);

export function filterPredicateUnionToJSON(
  filterPredicateUnion: FilterPredicateUnion,
): string {
  return JSON.stringify(FilterPredicateUnion$outboundSchema.parse(filterPredicateUnion));
}

export type FilterPredicate1 = {
  /**
   * Metadata key to evaluate, matched literally. A period is part of the key name, not a path into nested metadata.
   */
  field: string;
  /**
   * Compare the field for equality or inequality
   */
  operator: Operator1;
  /**
   * String value to compare against
   */
  value: string;
  /**
   * Whether string comparison preserves letter case
   */
  caseSensitive?: boolean | undefined;
};

/** @internal */
export type FilterPredicate1$Outbound = {
  /**
   * Metadata key to evaluate, matched literally. A period is part of the key name, not a path into nested metadata.
   */
  field: string;
  /**
   * Compare the field for equality or inequality
   */
  operator: string;
  /**
   * String value to compare against
   */
  value: string;
  /**
   * Whether string comparison preserves letter case
   */
  caseSensitive?: boolean | undefined;
};

/** @internal */
export const FilterPredicate1$outboundSchema: z.ZodMiniType<FilterPredicate1$Outbound, FilterPredicate1> = z.object({
  field: z.string(),
  operator: Operator1$outboundSchema,
  value: z.string(),
  caseSensitive: z._default(z.boolean(), true),
});

export function filterPredicate1ToJSON(
  filterPredicate1: FilterPredicate1,
): string {
  return JSON.stringify(FilterPredicate1$outboundSchema.parse(filterPredicate1));
}

export type FilterPredicate2 = {
  /**
   * Metadata key to evaluate, matched literally. A period is part of the key name, not a path into nested metadata.
   */
  field: string;
  /**
   * Compare the field for equality or inequality
   */
  operator: Operator2;
  /**
   * Numeric or boolean value to compare against
   */
  value: number | boolean;
};

/** @internal */
export type FilterPredicate2$Outbound = {
  /**
   * Metadata key to evaluate, matched literally. A period is part of the key name, not a path into nested metadata.
   */
  field: string;
  /**
   * Compare the field for equality or inequality
   */
  operator: string;
  /**
   * Numeric or boolean value to compare against
   */
  value: number | boolean;
};

/** @internal */
export const FilterPredicate2$outboundSchema: z.ZodMiniType<FilterPredicate2$Outbound, FilterPredicate2> = z.object({
  field: z.string(),
  operator: Operator2$outboundSchema,
  value: smartUnion([z.number(), z.boolean()]),
});

export function filterPredicate2ToJSON(
  filterPredicate2: FilterPredicate2,
): string {
  return JSON.stringify(FilterPredicate2$outboundSchema.parse(filterPredicate2));
}

/**
 * Numeric or boolean value to compare against
 */
export type Value =
  | number
  | boolean
;

/** @internal */
export type Value$Outbound =
  | number
  | boolean
;

/** @internal */
export const Value$outboundSchema: z.ZodMiniType<Value$Outbound, Value> = smartUnion([
  z.number(),
  z.boolean(),
]);

export function valueToJSON(
  value: Value,
): string {
  return JSON.stringify(Value$outboundSchema.parse(value));
}

export type FilterPredicate3 = {
  /**
   * Metadata key to evaluate, matched literally. A period is part of the key name, not a path into nested metadata.
   */
  field: string;
  /**
   * Numeric comparison to apply
   */
  operator: Operator3;
  /**
   * Numeric value to compare against
   */
  value: number;
};

/** @internal */
export type FilterPredicate3$Outbound = {
  /**
   * Metadata key to evaluate, matched literally. A period is part of the key name, not a path into nested metadata.
   */
  field: string;
  /**
   * Numeric comparison to apply
   */
  operator: string;
  /**
   * Numeric value to compare against
   */
  value: number;
};

/** @internal */
export const FilterPredicate3$outboundSchema: z.ZodMiniType<FilterPredicate3$Outbound, FilterPredicate3> = z.object({
  field: z.string(),
  operator: Operator3$outboundSchema,
  value: z.number(),
});

export function filterPredicate3ToJSON(
  filterPredicate3: FilterPredicate3,
): string {
  return JSON.stringify(FilterPredicate3$outboundSchema.parse(filterPredicate3));
}

export type FilterPredicate4 = {
  /**
   * Metadata key to evaluate, matched literally. A period is part of the key name, not a path into nested metadata.
   */
  field: string;
  /**
   * Require or exclude a substring match
   */
  operator: Operator4;
  /**
   * Substring to look for
   */
  value: string;
  /**
   * Whether substring matching preserves letter case
   */
  caseSensitive?: boolean | undefined;
};

/** @internal */
export type FilterPredicate4$Outbound = {
  /**
   * Metadata key to evaluate, matched literally. A period is part of the key name, not a path into nested metadata.
   */
  field: string;
  /**
   * Require or exclude a substring match
   */
  operator: string;
  /**
   * Substring to look for
   */
  value: string;
  /**
   * Whether substring matching preserves letter case
   */
  caseSensitive?: boolean | undefined;
};

/** @internal */
export const FilterPredicate4$outboundSchema: z.ZodMiniType<FilterPredicate4$Outbound, FilterPredicate4> = z.object({
  field: z.string(),
  operator: Operator4$outboundSchema,
  value: z.string(),
  caseSensitive: z._default(z.boolean(), true),
});

export function filterPredicate4ToJSON(
  filterPredicate4: FilterPredicate4,
): string {
  return JSON.stringify(FilterPredicate4$outboundSchema.parse(filterPredicate4));
}

export type FilterPredicate5 = {
  /**
   * Metadata key to evaluate, matched literally. A period is part of the key name, not a path into nested metadata.
   */
  field: string;
  /**
   * Require or exclude an exact array member
   */
  operator: Operator5;
  /**
   * Array member to look for
   */
  value: string;
};

/** @internal */
export type FilterPredicate5$Outbound = {
  /**
   * Metadata key to evaluate, matched literally. A period is part of the key name, not a path into nested metadata.
   */
  field: string;
  /**
   * Require or exclude an exact array member
   */
  operator: string;
  /**
   * Array member to look for
   */
  value: string;
};

/** @internal */
export const FilterPredicate5$outboundSchema: z.ZodMiniType<FilterPredicate5$Outbound, FilterPredicate5> = z.object({
  field: z.string(),
  operator: Operator5$outboundSchema,
  value: z.string(),
});

export function filterPredicate5ToJSON(
  filterPredicate5: FilterPredicate5,
): string {
  return JSON.stringify(FilterPredicate5$outboundSchema.parse(filterPredicate5));
}
